### ISSUE TITLE
no member trackAttributionData found

### ISSUE THREAD

**Issue by mauronate** [segmentio/analytics-ios#1001]
Hello.
We are currently using both Segment (4.1.4) and AppsFlyer together in our project. 
So I just recently removed the AppsFlyer pod, and added the pod segment-appsflyer-ios (6.2.6), to allow the integration between the two SDKs and followed the documentation found in the gitHub page.
Everything works fine regarding the deep linking but since we want in our app to track the installation attribution data through segment and AppsFlyer, I tried to set to ```true``` the attribute ```trackAttributionData``` of the AnalyticsConfiguration instance, however I get a compiler error saying:

```Value of type 'AnalyticsConfiguration' has no member 'trackAttributionData'```

I am opening the issue here since this attribute should belong to the Segment SDK

**Comment by ozgur** [comment]
I am facing the same issue, I think it is because of this PR: https://github.com/segmentio/analytics-ios/pull/941.

Can someone point us to the right direction on how to tackle that?

**Comment by mauronate** [comment]
I actually received an email from Segment customer support, telling me that is not necessary anymore to use the trackAttributionData from the SDK, since can now be managed from the destination settings.
