### ISSUE TITLE
XCode 12.5 Pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)

### ISSUE THREAD

**Issue by zbencz3** [segmentio/analytics-ios#1004]
On Xcode 12.5 the tag [4.1.4](https://github.com/segmentio/analytics-ios/releases/tag/4.1.4) has the warning: "Pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)"

<img width="1272" alt="warning" src="https://user-images.githubusercontent.com/5381246/122164217-1e553080-ce7f-11eb-9355-91bd69c75d51.png">
Since we treat warning as errors, it would show up as an actual error.
Please annotate the method to avoid the warning.

Same issue reported [here](https://github.com/segmentio/analytics-ios/issues/997).

**Comment by alanjcharles** [comment]
@zbencz3 we merged a fix and released it in `analytics-ios 4.1.5` [#999 ](https://github.com/segmentio/analytics-ios/pull/999)

please update and feel free to reopen if you are still running into issues.
