### ISSUE TITLE
Xcode 13b4: 'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.

### ISSUE THREAD

**Issue by JetForMe** [segmentio/analytics-ios#1010]
```
…/SourcePackages/checkouts/analytics-swift/Sources/Segment/Plugins/Platforms/iOS/iOSLifecycleMonitor.swift:58:37: 'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.
```

Xcode 13b4 introduced (erroneously, I think) a bug in which restrictions on APIs like being unavailable in extensions trigger errors, even when building applications. The usual fix for this is to declare the same restriction on the library's published methods.

You get this error by trying to build an iOS app in Xcode 13b4 with Segment as an SPM dependency.

**Comment by JetForMe** [comment]
I should say, segment-swift.

**Comment by bsneed** [comment]
Ok, lets move it to that repo then and close this one.
