### ISSUE TITLE
Unable to build the framework

### ISSUE THREAD

**Issue by jorlow** [segmentio/analytics-ios#115]
I have a fresh checkout of the source, an up to date cocoapods, ran "pod install", and then tried to build the "Analytics.framework" scheme and got the following error.

fatal error: lipo: fat input file (/Users/jorlow/src/segment-io/DerivedData/Analytics/Build/Products/Release/libAnalytics.a) does not contain the specified architecture (x86_64) to thin it to

Any idea what's going on or how I can fix it?  I saw this with both Xcode 5 and 5.1

**Comment by f2prateek** [comment]
Closing, feel free to reopen if you're still encountering issues.
