### ISSUE TITLE
Events are delayed from being sent to Segment.io

### ISSUE THREAD

**Issue by travisjeffery** [segmentio/analytics-ios#134]
I've seen a couple support tickets that have to do with the way that events are queued and flushed out when a certain number of them have been queued. vs. pushing them out as they come us as long as we can handle them. 

The 2nd strategy would be easier for people to understand and using an NSOperationQueue would clean up all that concurrent code quite nicely.

**Comment by f2prateek** [comment]
Is this something we still want to do? Currently the Android implementation mimics the iOS one (events go on a queue, that is flushed if it reaches a certain size or on a timer).

**Comment by f2prateek** [comment]
Also FWIW, I think most of other client libraries will follow this policy of batching messages (Go, Java, Analytics.NET and Analytics.Xamarin) do at least. 

There is indeed a tiny window we could drop messages if the user starts the app and uninstalls it right away. Maybe we could detect the first launch and adjust the queue size and flush timer to be smaller for that first session. I'm not sure if this a real issue in practice for users however.

**Comment by f2prateek** [comment]
Closing this as it's not something we want to implement currently (if ever).
