### ISSUE TITLE
assert friendly messages?

### ISSUE THREAD

**Issue by reinpk** [segmentio/analytics-ios#143]
is there a way to generate a message that explains each assertion failure?
https://github.com/segmentio/analytics-ios/blob/master/Analytics/Integrations/Segmentio/SEGSegmentioIntegration.m#L263

**Comment by FreshAatish** [comment]
This assertion is giving me an issue 
when `seg_viewDidAppear` is called, the top object is a UINavigationController and the name object is giving me <object returned empty description> which is causing the assertion to fail and the app to crash, is there any way around it?

**Comment by f2prateek** [comment]
Can you give a name to your view controller? We should be falling back to the class name though so not sure why you're seeing this error.

**Comment by f2prateek** [comment]
@FreshAatish What is the name of your view controller class and does it have a title?

**Comment by f2prateek** [comment]
@FreshAatish btw your issue should be fixed now - we've added better handling for ViewControllers that are UINavigationController https://github.com/segmentio/analytics-ios/issues/543
