### ISSUE TITLE
Unable to build with latest cocoapod

### ISSUE THREAD

**Issue by johnryan** [segmentio/analytics-ios#148]
getting build errors with the latest cocoapod

ld: library not found for -lCrittercism_v4_3_3
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by daniel-shin1104** [comment]
not sure why but I solved the exact same issue by removing `$(inherited)` from `Other Linker Flags`. The error message indicated that it had duplicating symbol errors.

using 6.3 GM and Swift
