### ISSUE TITLE
add support for localytics revenue tracking

### ISSUE THREAD

**Issue by reinpk** [segmentio/analytics-ios#162]
as requested by 
https://twitter.com/FaisalAbid/status/483677051728433152

http://support.localytics.com/Advanced_Features#Customer_Lifetime_Value_Tracking

would go here:
https://github.com/segmentio/analytics-ios/blob/master/Analytics/Integrations/Localytics/SEGLocalyticsIntegration.m#L96

**Comment by f2prateek** [comment]
Done with #210
