### ISSUE TITLE
registerForRemoteNotificationsWithDeviceToken

### ISSUE THREAD

**Issue by rubikva** [segmentio/analytics-ios#173]
I don't know where I need to write this question, so sorry if I'm wrong:) 
Why when I use
[[SEGAnalytics sharedAnalytics] registerForRemoteNotificationsWithDeviceToken:deviceToken];

I don't see token in mixpanel??? But sometimes token is present! I'm realy confused :((

**Comment by f2prateek** [comment]
Let me know if you still see this on the latest versions.
