### ISSUE TITLE
Crash in queuePayload

### ISSUE THREAD

**Issue by johnryan** [segmentio/analytics-ios#187]
http://crashes.to/s/3a50032e1d1

**Comment by alexfish** [comment]
i've just experienced this in 1.8.6

```
-[SEGSegmentioIntegration queuePayload:] (SEGSegmentioIntegration.m:349)

*** Collection <__NSDictionaryM: 0x175e43c0> was mutated while being enumerated.
```

**Comment by besbes** [comment]
We're experiencing this crash with version 1.11.8.

    Last Exception Backtrace:
    0   CoreFoundation                       0x2837c137 __exceptionPreprocess + 127
    1   libobjc.A.dylib                      0x3640cc77 objc_exception_throw + 36
    2   CoreFoundation                       0x2837bbbd __NSFastEnumerationMutationHandler + 126
    3   CoreFoundation                       0x2829b331 -[NSDictionary __apply:context:] + 122
    4   CoreFoundation                       0x28298321 CFDictionaryApplyFunction + 186
    5   CoreFoundation                       0x2833ce2f __CFPropertyListIsValidAux + 332
    6   CoreFoundation                       0x2833d6f7 __CFPropertyListIsDictPlistAux + 204
    7   CoreFoundation                       0x2829b34b -[NSDictionary __apply:context:] + 148
    8   CoreFoundation                       0x28298321 CFDictionaryApplyFunction + 186
    9   CoreFoundation                       0x2833ce2f __CFPropertyListIsValidAux + 332
    10  CoreFoundation                       0x2833d6f7 __CFPropertyListIsDictPlistAux + 204
    11  CoreFoundation                       0x2829b34b -[NSDictionary __apply:context:] + 148
    12  CoreFoundation                       0x28298321 CFDictionaryApplyFunction + 186
    13  CoreFoundation                       0x2833ce2f __CFPropertyListIsValidAux + 332
    14  CoreFoundation                       0x2833d5fb __CFPropertyListIsArrayPlistAux + 24
    15  CoreFoundation                       0x2828b411 CFArrayApplyFunction + 34
    16  CoreFoundation                       0x2833cdef __CFPropertyListIsValidAux + 268
    17  CoreFoundation                       0x2829b145 _CFPropertyListCreateXMLData + 54
    18  CoreFoundation                       0x282a3d45 CFPropertyListCreateData + 78
    19  Foundation                           0x29022e65 +[NSPropertyListSerialization dataWithPropertyList:format:options:error:] + 34
    20  Foundation                           0x290684ef -[NSArray(NSArray) writeToURL:atomically:] + 224
    21  myApp                                0x001c95a1 -[SEGSegmentioIntegration queuePayload:] (SEGSegmentioIntegration.m:370)
    22  myApp                                0x001c94bd __60-[SEGSegmentioIntegration enqueueAction:dictionary:options:]_block_invoke (SEGSegmentioIntegration.m:364)
    23  libdispatch.dylib                    0x36976c83 _dispatch_call_block_and_release + 8
    24  libdispatch.dylib                    0x369814d3 _dispatch_queue_drain$VARIANT$mp + 1460
    25  libdispatch.dylib                    0x36980da1 _dispatch_queue_invoke$VARIANT$mp + 82
    26  libdispatch.dylib                    0x36983491 _dispatch_root_queue_drain + 386
    27  libdispatch.dylib                    0x369848a3 _dispatch_worker_thread3 + 104
    28  libsystem_pthread.dylib              0x36af8da9 _pthread_wqthread + 666
    29  libsystem_pthread.dylib              0x36af8afc start_wqthread + 6

**Comment by f2prateek** [comment]
@besbes Fixed in the latest releases by https://github.com/segmentio/analytics-ios/commit/287b33166a4be78a68b0efa36872b0a0416b3ab1

**Comment by besbes** [comment]
@f2prateek Thanks for the heads up!

**Comment by f2prateek** [comment]
also made some improvements in https://github.com/segmentio/analytics-ios/commit/e10984e56e0f7fc5f869ebe70aa599dd53b6d1b0

**Comment by angela-** [comment]
experiencing this issue in 1.12.0
```
Thread : Fatal Exception: NSGenericException
0  CoreFoundation                 0x0000000187e5a59c __exceptionPreprocess
1  libobjc.A.dylib                0x00000001985b00e4 objc_exception_throw
2  CoreFoundation                 0x0000000187e59f50 -[NSException name]
3  CoreFoundation                 0x0000000187d51a04 -[NSDictionary objectForKeyedSubscript:]
4  Foundation                     0x0000000188c9e644 _NSIsPList
5  Foundation                     0x0000000188c9e678 _NSIsPList
6  Foundation                     0x0000000188c9e678 _NSIsPList
7  Foundation                     0x0000000188c9e574 _NSIsPList
8  Foundation                     0x0000000188ccadf0 -[NSArray(NSArray) writeToURL:atomically:]
9  MyApp                      0x0000000100261400 -[SEGSegmentioIntegration queuePayload:] (SEGSegmentioIntegration.m:401)
10 MyApp                      0x0000000100261298 __60-[SEGSegmentioIntegration enqueueAction:dictionary:options:]_block_invoke (SEGSegmentioIntegration.m:394)
11 libdispatch.dylib              0x0000000198bf53ac _dispatch_call_block_and_release
12 libdispatch.dylib              0x0000000198bf536c _dispatch_client_callout
13 libdispatch.dylib              0x0000000198bff4c0 _dispatch_queue_drain
14 libdispatch.dylib              0x0000000198bf8474 _dispatch_queue_invoke
15 libdispatch.dylib              0x0000000198c01224 _dispatch_root_queue_drain
16 libdispatch.dylib              0x0000000198c0275c _dispatch_worker_thread3
17 libsystem_pthread.dylib        0x0000000198dd12e4 _pthread_wqthread
18 libsystem_pthread.dylib        0x0000000198dd0fa8 start_wqthread
```
