### ISSUE TITLE
Consider switching to #if has_include()

### ISSUE THREAD

**Issue by orta** [segmentio/analytics-ios#199]
I'm moving ARAnalytics towards this soon, ( https://github.com/orta/ARAnalytics/issues/98 ) as it means a bit less magic in an already very magical Podspec and the pch file changes to transmit state kind of feel a bit icky to me. I don't think we're planning on dropping support for it in CocoaPods but it's letting the compiler do its thing instead of you.

Example of someone doing this recently:
https://github.com/AmbientStatus/AmbientStatus/commit/8104aa9da12d748ec30e9b83d448318614eb54bd

**Comment by f2prateek** [comment]
We've made bundling integrations very explicit since 3.0 https://segment.com/docs/libraries/ios/#bundling-integrations. Still can have some improvements in the future, but for now this is the best way since we don't maintain a registry of all integrations in our code.
