### ISSUE TITLE
google analytics: support custom dimensions

### ISSUE THREAD

**Issue by travisjeffery** [segmentio/analytics-ios#211]

**Comment by pasevin** [comment]
+1

**Comment by pasevin** [comment]
any news on this?

**Comment by aleffert** [comment]
:+1: This is a pretty serious limitation and it's not obvious from the UI that it doesn't work. I only didn't waste a bunch of time trying to get it to work stumbling on docs out of luck.

**Comment by aleffert** [comment]
Seems like you might be able to work around this by calling GA directly?

```
    [[[GAI sharedInstance] defaultTracker] set:[GAIFields customDimensionForIndex:someIndex] value:someValue];
```

**Comment by pasevin** [comment]
Got an email update: **"Google Analytics now supports custom dimensions and metrics on mobile for both iOS and Android. Automatically map your traits and properties."** 
Do we need to update SDK for this? I still can't see the custom dimensions data on GA. Can anyone confirm that it's working?

**Comment by f2prateek** [comment]
@pasevin please share your logs to friends@segment.com (maybe also cc prateek@segment.com) and we can debug this further. I've added some extra logging in the latest release that should help make sense of what's going in the translation.
