### ISSUE TITLE
Clean up old binary files in source control history

### ISSUE THREAD

**Issue by robertjpayne** [segmentio/analytics-ios#212]
This repo takes a good 10-20 minutes to clone and is a whopping ~180-200mb even though a tarball hardly over 100kb.

Digging a bit deeper it looks like back in history 8.9mb releases of the Analytics framework were included in Git as well as a few binary releases inside an example project.

Given these were a long time ago I'd recommend removing them from the history to allow clones to be a lot faster.

Unfortunately this isn't something that can be done and then a pull request issued, it has to be done by a contributor and forced upon the repo as it rewrites history a bit. A great guide on how to do this sort of house keeping be found here: https://confluence.atlassian.com/display/BITBUCKET/Maintaining+a+Git+Repository

Here's a list of the larger files in the repo's history. Looks like cleaning them out will at least save about 94.6 on the repo size.

size (kb)|pack (kb)|SHA|location
----|----|---|--------
31205|10475|e22ebec26399c02b2c37aef32d9d6e667130beee|Examples/Geofencing/Analytics.framework/Versions/A/Analytics
18201|6739|6666fd842ea3df5723594a97a6d9931fc892a8dd|Examples/Geofencing/Analytics.framework/Versions/A/Analytics
12558|12429|7347e3fae7cb728f478c0e6642ad35cf6e13623b|Releases/Analytics.framework.zip
9445|9345|3bb0f46fbc8f17a367c06284a3116e8d0d4047dd|Releases/Analytics.framework.zip
9445|9345|de4c12ef7680ba611aa6ad37cbb3e79daa690aa1|Releases/Analytics.framework.zip
9445|9346|595d0214c71c6a7d9070ae46b5410cb219ef7392|Releases/Analytics.framework.zip
9445|9345|87c9d62c57bef74fa902851a6258fc7b71117f42|Releases/Analytics.framework.zip
9443|9344|1b9331b8e285044fe16ff98e90669a2794096b5f|Releases/Analytics.framework.zip
9443|9344|2e229fe40c9023560f4c5e8772dd54ff057fccda|Releases/Analytics.framework.zip
9207|9116|7f9df6e9beb33a8240213f32b08317c278d8d9e1|Releases/Analytics.framework.zip

**Comment by f2prateek** [comment]
Did some work for this in https://github.com/segmentio/analytics-ios/tree/clean-history

**Comment by f2prateek** [comment]
For reference, all I did was run `bfg --delete-files Analytics.framework.zip .git`

**Comment by f2prateek** [comment]
Cleaned up the framework files in the repo.
