### ISSUE TITLE
Intercom: Add option to bundle SDK

### ISSUE THREAD

**Issue by sperand-io** [segmentio/analytics-ios#230]
For in-app messaging features, automatic rich device/os data, etc.

**Comment by naqi** [comment]
I second this we would like this for our app as well.

**Comment by billboebel** [comment]
+1

**Comment by f2prateek** [comment]
Same here @sperand-io, could we add this to the Trello board?

**Comment by f2prateek** [comment]
Added this request internally (https://trello.com/c/8Pkjj03x/114-intercom-ios-2)

**Comment by naqi** [comment]
I tried to access the card on Trello but it no longer exists. Any updates on this?

**Comment by hojberg** [comment]
Did this ship?

**Comment by f2prateek** [comment]
Not yet.

**Comment by m-revetria** [comment]
Hi! Is there any update on this issue? 

I'm having problems by using both SDKs in my iPhone app while registering anonymous users, where at the end I got duplicated users on Intercom platform.
