### ISSUE TITLE
NSNumber objects representing a NaN value result in a crash on flush.

### ISSUE THREAD

**Issue by bradhouse** [segmentio/analytics-ios#231]
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid number value (NaN) in JSON write'

The crash occurs during JSON construction of a flush operation at the following location:

https://github.com/segmentio/analytics-ios/blob/1.8.7/Analytics/Integrations/Segmentio/SEGSegmentioIntegration.m#L382

The actual value in this case is coming from an NSTimeInterval wrapped in an NSNumber.

    NSDictionary *properties = @{
        "my_key": @(anNSTimeInterval)
    };
    [[SEGAnalytics sharedAnalytics] track:@"example" properties:properties];

I'll leave it up to the audience as to whether or not the library or the clients of the library should guard against this. 

That said, once this data is stored as an event to report on, it is unrecoverable and the library will on each application launch attempt to flush and subsequently crash.

**Comment by travisjeffery** [comment]
Hey Brad, in the latest version of the sdk we now wrap JSON serialization with a try/catch so it'll just silently fail now and not crash.

**Comment by bradhouse** [comment]
Awesome. Thanks for the heads up.
