### ISSUE TITLE
KISSmetrics - add option to bundle SDK

### ISSUE THREAD

**Issue by sperand-io** [segmentio/analytics-ios#244]
to enable their ambient "Downloaded/Updated" events: http://support.kissmetrics.com/apis/ios-v2#optional-automated-tracking

this is a customer request! :)

**Comment by f2prateek** [comment]
could you add this to the Trello board?

**Comment by f2prateek** [comment]
Added https://trello.com/c/IUJdQXTt/113-kissmetrics-ios, @sperand-io if you could put the custom request in the card, that would be awesome!

**Comment by DirtyAnalytics** [comment]
@sperand-io do you have the customer's email so we can add it to the trello board?
