### ISSUE TITLE
Undefined symbols, SEGLocalyticsIntegration.o for Latest Prebuilt Framework

### ISSUE THREAD

**Issue by seenickcode** [segmentio/analytics-ios#248]
Hello, I'm trying to integrate the SDK by following the manually integration instructions as using Cocoapods is not possible for me.  When I download the latest stable SDK (as of 1/29/15) from ``https://s3.amazonaws.com/segmentio/releases/ios/Analytics-latest-stable.zip``, I get the following error and cannot build.

````
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_Localytics", referenced from:
      objc-class-ref in Analytics(SEGLocalyticsIntegration.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
````

Any ideas?  I'm following the manual install instructions exactly.

Thanks,

**Comment by seenickcode** [comment]
A fully reproduceable XCode project can be found here:  https://www.dropbox.com/s/a6t37vxvdv1py0b/Test.zip?dl=0

**Comment by travisjeffery** [comment]
Hey! Thanks for the issue. I believe I've fixed the issue in the latest build: https://s3.amazonaws.com/segmentio/releases/ios/Analytics-latest-stable.zip. Can you try it and make sure it works for you? Thanks!

**Comment by seenickcode** [comment]
@travisjeffery, I'm not sure if I'm integrating it properly but I'm getting a lot of duplicate symbol errors now.  All I did was delete the existing framework I had an then dragged in your new update.  

The previous "patched" Analytics.framework you guys had sent just a few days ago worked though.  

![screen shot 2015-02-03 at 10 35 44 am](https://cloud.githubusercontent.com/assets/75833/6023196/d6cdb556-ab90-11e4-943a-a19a0618eeb4.png)

**Comment by seenickcode** [comment]
Thanks @travisjeffery , I'll have to try this for our next release in another few weeks.

Nick,
