### ISSUE TITLE
OS X support

### ISSUE THREAD

**Issue by iosdev-republicofapps** [segmentio/analytics-ios#251]
Hi,

I like your product and I'd like to use it for one of my apps that will support both iOS and OS X.  Do you have an OS X library, and, if not, do you plan to release one and when?

Thanks!

**Comment by f2prateek** [comment]
Currently we do not have an official OS X library. We'd love to release one, but are not actively working on one currently. The best option is to directly use our [HTTP Tracking API](https://segment.com/docs/libraries/http/).

**Comment by aldenks** [comment]
I would use an OSX library if you released one.
