### ISSUE TITLE
[linker] Conflicts with SocketRocket library

### ISSUE THREAD

**Issue by dodikk** [segmentio/analytics-ios#258]
### Steps to reproduce
1. Create a project
2. Enable "-Obj-C -all_load" linker flags
3. Add a binary Analytics.framework
4. Add a SocketRocket library
5. Build

#### Case1 Both libraries are linked 
![screen shot 2015-02-13 at 2 06 52 pm](https://cloud.githubusercontent.com/assets/396451/6186981/992ec50e-b389-11e4-975e-875dc9123e2e.png)

```bash
duplicate symbol _SRHTTPResponseErrorKey in:
    /Users/dodikk/Library/Developer/Xcode/DerivedData/healthjoy-ggoeubmiinjycneahpecjojftiys/Build/Products/Debug-iphonesimulator/libSocketRocket.a(SRWebSocket.o)
    ../../lib-third-party/Analytics.framework/Analytics(SRWebSocket.o)
ld: 1 duplicate symbol for architecture x86_64
```

#### Case2 SocketRocket is not linked
![screen shot 2015-02-13 at 2 09 03 pm](https://cloud.githubusercontent.com/assets/396451/6187009/e3df1888-b389-11e4-8cb7-97f384b33a74.png)

```bash
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_SRWebSocket", referenced from:
      l_OBJC_$_CATEGORY_SRWebSocket_$_HJWebSocketAdapter in libHealthJoyChat.a(SRWebSocket+HJWebSocketAdapter.o)
ld: symbol(s) not found for architecture x86_64
```

**Comment by dodikk** [comment]
I'm unable to stop using "-Obj-C -all_load" linker flags since some of my dependencies use cathegories.

**Comment by dodikk** [comment]
@segmentio , please do not link SocketRocket and other dependencies into your framework.
All libraries should **link only to the application**. This guarantees absence of linker conflicts.

**Comment by dodikk** [comment]
Applied a workaround of converting the ```_SRHTTPResponseErrorKey``` constant to a static method.
https://github.com/healthjoy-ios-opensource/SocketRocket/blob/develop/SocketRocket/SRErrorConstants.h#L14

However, this is definitely a linker issue of @segment.io
Forcing your users patch the SocketRocket library is a terrible user experience.

**Comment by travisjeffery** [comment]
@dodikk i believe you can use our cocoapod to help with this issue, then the libs would link to your application. But we want people to do as little work as possible to get up and running, and for the static lib that means linking those dependencies.

**Comment by travisjeffery** [comment]
@dodikk just to provide more detailed info, this is happening in one of the integrations we bundle. We don't use SocketRocket in our SDK directly. I'm not sure which integration it is, but they could namespace SR to fix this, but we can't.

**Comment by travisjeffery** [comment]
@dodikk looks like Mixpanel and/or Optimizely.

**Comment by dodikk** [comment]
Is your pod based on sources or on binaries? This spec is source based according to those "{h,m}" statements.
https://github.com/CocoaPods/Specs/blob/master/Specs/Analytics/1.10.4/Analytics.podspec.json

Maybe you have a binary version elsewhere?

**Comment by dodikk** [comment]
As a user, I would prefer having binary frameworks. But I would like them to be modular in order to avoid such conflicts.

**Comment by dodikk** [comment]
>> I'm not sure which integration it is, but they could namespace SR to fix this, but we can't.

I think you could find out which plug-in uses socketrocket and forward this issue to their support rather than just closing it like this.

**Comment by dodikk** [comment]
>> But we want people to do as little work as possible to get up and running, and for the static lib that means linking those dependencies.

FYI : pods can be binary 
https://github.com/CocoaPods/Specs/blob/master/Specs/ESLocaleFramework/1.2.1/ESLocaleFramework.podspec.json

P.S. And I really do not understand why "dragging a single framework" is so much more complicated for the programmer comparing to "dragging multiple frameworks" from the single directory or tarball.

**Comment by travisjeffery** [comment]
> Is your pod based on sources or on binaries? This spec is source based according to those "{h,m}" statements.

@dodikk our code is shipped by the source. But we have integration dependencies - some of which provide the source, others only provide their static library - so our SDK has to use both.

> I think you could find out which plug-in uses socketrocket and forward this issue to their support rather than just closing it like this.

I did forward it to Mixpanel and Optimzely to see what they can do but we can't do anything about it unfortunately. 

> FYI : pods can be binary 

Having it as a binary would result in the same conflict you're running into now with the static library. Binary/static libraries is the root of the issue. 100% source based pods with declared dependencies (rather than building static libraries, each linking their dependencies - which could conflict) wouldn't have this issue.

**Comment by dodikk** [comment]
>> I did forward it to Mixpanel and Optimzely to see what they can do but we can't do anything about it unfortunately.

Thanks.
