### ISSUE TITLE
Facebook app events?

### ISSUE THREAD

**Issue by hden** [segmentio/analytics-ios#277]
It might be a good fit with [semantic events](https://segment.com/docs/spec/ecommerce/).
requirement: [Facebook SDK](http://cocoapods.org/?q=facebook)
docs: https://developers.facebook.com/docs/app-events/ios#events

**Comment by f2prateek** [comment]
Yup we're working on this. The iOS one is already published and we're switching to their server side API soon https://github.com/segment-integrations/integration-facebook-app-events
