### ISSUE TITLE
Support Push Notifications for Countly

### ISSUE THREAD

**Issue by f2prateek** [segmentio/analytics-ios#285]
http://resources.count.ly/v1.0/docs/countly-push-for-ios

**Comment by f2prateek** [comment]
Closing for irrelevance.

**Comment by leoafarias** [comment]
@f2prateek Is there a way for us to send the push notification token, to countly from segment.io? We are trying to remove the countly sdk from our apps, but we need to be able to register the push notification token

**Comment by f2prateek** [comment]
Not currently, county is only available as a bundled integration so you can only set the token via their SDK.
