### ISSUE TITLE
[urgent] Bugsnag dependancy causes pod install to fail

### ISSUE THREAD

**Issue by gileze33** [segmentio/analytics-ios#296]
Using Analytics pod version 1.11.2

It looks like the Bugsnag dependancy relies on a private git repository

$ pod install
Analyzing dependencies

CocoaPods 0.37.0.beta.1 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Downloading dependencies
Installing Amplitude-iOS (2.2.4)
Installing Analytics (1.11.2)
Installing AppsFlyer-SDK (2.5.3.10)
Using Braintree (3.6.0-rc3)
Installing Bugsnag (4.0.3)

[!] Error installing Bugsnag
[!] /usr/local/bin/git submodule update --init

Submodule 'KSCrashModule' (git@github.com:bugsnag/KSCrash.git) registered for path 'KSCrashModule'
Cloning into 'KSCrashModule'...

Permission denied (publickey).

fatal: Could not read from remote repository.

Please make sure you have the correct access rights

and the repository exists.

Clone of 'git@github.com:bugsnag/KSCrash.git' into submodule path 'KSCrashModule' failed

**Comment by gileze33** [comment]
This has completely broken our dev cycle

**Comment by f2prateek** [comment]
The repository is certainly not private https://github.com/bugsnag/KSCrash, try updating your SSH keys.

**Comment by navjotdhanawat** [comment]
Try updating your SSH keys.
https://help.github.com/articles/generating-an-ssh-key/
