### ISSUE TITLE
Crittercism Library iOS App Rejected - Invalid Signature

### ISSUE THREAD

**Issue by reddavis** [segmentio/analytics-ios#303]
Hey!

The Crittercism library used in the latest Segment cocoapod has this issue: http://support.crittercism.com/articles/knowledge_base/iOS-App-rejection-issue-for-the-Apps-built-using-CocoaPods.

Fix: "To fix this error, simply upgrade to version 5.2.0 of the cocoa pods spec"

**Comment by ryanio** [comment]
+1

**Comment by joemasilotti** [comment]
#299 addresses this.

**Comment by gileze33** [comment]
+1

**Comment by f2prateek** [comment]
We've updated the Crittercism dependency.
