### ISSUE TITLE
Amplitude session tracking workarounds

### ISSUE THREAD

**Issue by hden** [segmentio/analytics-ios#310]
Amplitude session tracking issue described [here](https://segment.com/help/getting-started/why-bundle-integrations/#features-not-available-with-server-side-integrations) can be mitigated (in a hacky way) by manually adding event tracking at the following locations at `AppDelegate.m`.

* applicationWillTerminate
* applicationDidEnterBackground
* applicationDidFinishLaunching
* applicationWillEnterForeground

e.g.

```obj-c
//  AppDelegate.m
- (void)applicationDidEnterBackground:(UIApplication *)application {
    [[SEGAnalytics sharedAnalytics] track:@"[Amplitude] End Session" properties:@{}];
}

- (void)applicationWillEnterForeground:(UIApplication *)application {
    [[SEGAnalytics sharedAnalytics] track:@"[Amplitude] Start Session" properties:@{}];
}
```

see amplitude [docs](https://amplitude.com/docs/api/http)

> the following event names are reserved for Amplitude use: "[Amplitude] Start Session", "[Amplitude] End Session", "[Amplitude] Revenue", "[Amplitude] Revenue (Verified)", "[Amplitude] Revenue (Unverified)", "[Amplitude] Merged User"

**Comment by f2prateek** [comment]
Neat, I'd also pass in a custom `integrations` map so that the event only gets sent to Amplitude. 

I don't think we'll add this feature just for Amplitude quite yet, we'd like to generalize the solution for other tools as well first.

**Comment by hden** [comment]
Awesome
