### ISSUE TITLE
AppsFlyer static library is used as transitive dependency

### ISSUE THREAD

**Issue by elaser** [segmentio/analytics-ios#318]
Hey there,
  We have our custom pod written in Swift and so we are linking it to our project via embedded frameworks.  

```ruby
link_with 'MainProject'
use_frameworks!

pod 'CustomLib', :git => '../CustomLib.git', :branch => 'master'

pod 'Analytics/AppsFlyer'
```

We cannot run pod install due to this issue: https://github.com/CocoaPods/CocoaPods/issues/2926.  Do you know if `AppsFlyer` will be changed to not be a static library or if there is a suitable workaround?

Thanks!
Anderthan

**Comment by benaneesh** [comment]
Is there any updates on this issue?

Thanks,
Ben

**Comment by travisjeffery** [comment]
AppsFlyer only provides their SDK via a static library: https://github.com/CocoaPods/Specs/blob/master/Specs/AppsFlyer-SDK/2.5.3.19/AppsFlyer-SDK.podspec.json#L27. Unfortunately we can't do anything about this. Can you contact their support and see if they will change it?
