### ISSUE TITLE
Getting error when adding Segment iOS framework manually

### ISSUE THREAD

**Issue by ruchiragile** [segmentio/analytics-ios#331]
I'm trying to add segmentio iOS framework manually in my app. When I build the project, its ended with following error, "Undefined symbols for architecture i386" and logs.

    Undefined symbols for architecture i386:
      "_OBJC_CLASS_$_Amplitude", referenced from:
          objc-class-ref in Analytics(SEGAmplitudeIntegration.o)
      "_OBJC_CLASS_$_AppsFlyerTracker", referenced from:
          objc-class-ref in Analytics(SEGAppsFlyerIntegration.o)
      "_OBJC_CLASS_$_Bugsnag", referenced from:
          objc-class-ref in Analytics(SEGBugsnagIntegration.o)
      "_OBJC_CLASS_$_Countly", referenced from:
          objc-class-ref in Analytics(SEGCountlyIntegration.o)
      "_OBJC_CLASS_$_Crittercism", referenced from:
          objc-class-ref in Analytics(SEGCrittercismIntegration.o)
      "_OBJC_CLASS_$_CrittercismConfig", referenced from:
          objc-class-ref in Analytics(SEGCrittercismIntegration.o)
      "_OBJC_CLASS_$_Flurry", referenced from:
          objc-class-ref in Analytics(SEGFlurryIntegration.o)
      "_OBJC_CLASS_$_GAI", referenced from:
          objc-class-ref in Analytics(SEGGoogleAnalyticsIntegration.o)
      "_OBJC_CLASS_$_GAIDictionaryBuilder", referenced from:
          objc-class-ref in Analytics(SEGGoogleAnalyticsIntegration.o)
      "_OBJC_CLASS_$_KahunaAnalytics", referenced from:
          objc-class-ref in Analytics(SEGKahunaIntegration.o)
      "_OBJC_CLASS_$_Localytics", referenced from:
          objc-class-ref in Analytics(SEGLocalyticsIntegration.o)
      "_OBJC_CLASS_$_Mixpanel", referenced from:
          objc-class-ref in Analytics(SEGMixpanelIntegration.o)
      "_OBJC_CLASS_$_QuantcastMeasurement", referenced from:
          objc-class-ref in Analytics(SEGQuantcastIntegration.o)
      "_OBJC_CLASS_$_TRVSDictionaryWithCaseInsensitivity", referenced from:
          objc-class-ref in Analytics(SEGAnalyticsIntegration.o)
      "_OBJC_CLASS_$_TSConfig", referenced from:
          objc-class-ref in Analytics(SEGTapstreamIntegration.o)
      "_OBJC_CLASS_$_TSEvent", referenced from:
          objc-class-ref in Analytics(SEGTapstreamIntegration.o)
      "_OBJC_CLASS_$_TSTapstream", referenced from:
          objc-class-ref in Analytics(SEGTapstreamIntegration.o)
      "_kGAIScreenName", referenced from:
          -[SEGGoogleAnalyticsIntegration screen:properties:options:] in Analytics(SEGGoogleAnalyticsIntegration.o)
    ld: symbol(s) not found for architecture i386
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

How to solve this error, I'm strictly following all instructions given [here](https://github.com/segmentio/analytics-ios/wiki/Installing-Manually). However just wont be able to solve it out.

Please help !

**Comment by f2prateek** [comment]
We're looking into this.

**Comment by manhcuong27** [comment]
I got the same error when i build with iPhone 4s/5 simulator, if i build with iPhone 5s or above i will receive same error for x86_64 architecture

**Comment by manhcuong27** [comment]
Any update for this issue please ?

**Comment by f2prateek** [comment]
Can you try with the latest release https://github.com/segmentio/analytics-ios/releases/tag/1.12.0?

**Comment by degapps** [comment]
I have exactly the same issue (with 1.12.0).

**Comment by Roy-Hub** [comment]
I have the same problem with 1.12.0

**Comment by benaneesh** [comment]
1.12.1 - same problem.

**Comment by dseravalli** [comment]
1.12.1- same problem

**Comment by rossmooney** [comment]
I got it to work.  Answer posted here:  http://stackoverflow.com/questions/30775562/getting-error-when-adding-segment-ios-framework-manually/31491997#31491997

**Comment by kineticac** [comment]
1.12.2 - same problem

**Comment by jeffdolle-sge** [comment]
Using the linker flag: ``-all_load`` resolved the issue for me.

**Comment by f2prateek** [comment]
Can you anyone affected also let us know which version they were upgrading from (i.e. the last version that was working for them)?

**Comment by gamesbydre** [comment]
Upgrading from version 1.11.3 to 1.12.5.
I performed a manual install on 1.11.3 with no issues.

**Comment by f2prateek** [comment]
This should be fixed in the latest release (v2), the instructions have changed slightly on the manual installation wiki, but you shouldn't run into this error anymore.

**Comment by DanMorganShoeboxed** [comment]
It doesn't matter how far forward or back I go in the release builds (even v2.0.2) I run into this error.  I'm also on the latest Xcode (6.4)

**Comment by dseravalli** [comment]
The latest release works for me now @f2prateek . Thanks!
