### ISSUE TITLE
Can't access DropBox linked documentation for adding integration

### ISSUE THREAD

**Issue by andyblackwell** [segmentio/analytics-ios#334]
In the README.md

* * *
## Development

[Documentation for getting starting with hacking on the SDK and adding integrations](https://segmentio.hackpad.com/Engineering-Getting-started-with-the-iOS-SDK-1LQqD1q9SKQ).
* * *

Can't access this DropBox Notes document due to DropBox Notes being in beta.
https://segmentio.hackpad.com/Engineering-Getting-started-with-the-iOS-SDK-1LQqD1q9SKQ

**Comment by f2prateek** [comment]
We have a PDF I can link you to when I get back on Monday. We're not accepting any more bundled integrations for a while though (other than the ones that are already open) to be able to focus work on improving the process to add and maintain bundled integrations.

**Comment by f2prateek** [comment]
PDF https://cloudup.com/cbcTLuCTAWx
