### ISSUE TITLE
Cannot update Optimzely SDK to 1.0.86 (Analytics 1.12.0)

### ISSUE THREAD

**Issue by shahzadmajeed** [segmentio/analytics-ios#356]
Hi I have following pods in my project (currently using Analytics 1.11.2)

pod 'Analytics/GoogleAnalytics'
pod 'Analytics/Optimizely'

and I want to update Optimizely sdk. I tried pulling update from 1.12.0 but something strange happens. I see that 1.12.0 uses 1.0.86 Optimzely version but my local pod files always have 1.0.84 version even in integrations.json file its 1.0.84. Now, It always fails pulling 1.0.84 tag probably because optimizely have removed this tag from master branch.

I get following error

[!] /usr/bin/git clone https://github.com/optimizely/Optimizely-iOS-SDK.git PROJECT_PATH/Project_Name/Pods/Optimizely-iOS-SDK --single-branch --depth 1 --branch 1.0.84
Cloning into 'PROJECT_PATH/Project_Name/Pods/Optimizely-iOS-SDK'...
warning: Could not find remote branch 1.0.84 to clone.
fatal: Remote branch 1.0.84 not found in upstream origin

I looked into my .gitignore settings and found that .lock was there. So I removed it and tried pulling again but everytime its the same thing.

Can you please help on whats going on ? Why my Analytics files are always showing 1.0.84 instead of 1.0.86 which I can see on Analytics git repository pod files.

**Comment by shahzadmajeed** [comment]
I just found that in Podfile.lock (with Analytics 1.11.2)

its - Optimizely-iOS-SDK (1.0.86) under PODS: tag and - Optimizely-iOS-SDK (1.0.84) under DEPENDENCIES: tag

Is it a mistake or you did it on purpose ?

**Comment by f2prateek** [comment]
Both are 1.0.75 (https://github.com/segmentio/analytics-ios/blob/1.11.2/Podfile.lock) in version 1.11.2

**Comment by f2prateek** [comment]
Let me know if you're still seeing this issue on the latest releases.

**Comment by shahzadmajeed** [comment]
I had fixed it. Somehow local pod files were not getting updated due to permissions.
