### ISSUE TITLE
Mixpanel resources with cocoapods integration

### ISSUE THREAD

**Issue by ldiqual** [segmentio/analytics-ios#368]
Hey there,

I'm trying to follow these instructions about adding mixpanel resources to my app: https://segment.com/docs/libraries/ios/#does-segment-support-mixpanel-in-app-notifications-and-surveys-, but since `Analytics/Segmentio` and `Analytics/Mixpanel` were added from cocoapods, there is no `Analytics.framework` with a `Resources` folder that I can link to.

What would be a workaround for this? (besides copying manually the `Resources` folder from the pre-built `Analytics.framework`)

**Comment by samgreen** [comment]
Please let me know if you need anything from us over at Mixpanel. Thanks!

**Comment by tobycox** [comment]
Did this even answer the question?
