### ISSUE TITLE
pod install fails due to MoEngage

### ISSUE THREAD

**Issue by pm-dev** [segmentio/analytics-ios#373]
Cloning the repo and attempting to pod install results in the following cocoapods error:
```
[!] Unable to satisfy the following requirements:

- `MoEngage-iOS-SDK (= 1.4.3)` required by `Podfile`
- `MoEngage-iOS-SDK (= 1.4.3)` required by `Podfile`
- `MoEngage-iOS-SDK (= 1.4.3)` required by `Podfile.lock`
```

**Comment by f2prateek** [comment]
Weird, I see that it's available here -https://github.com/CocoaPods/Specs/blob/master/Specs/MoEngage-iOS-SDK/1.4.3/MoEngage-iOS-SDK.podspec.json

**Comment by pm-dev** [comment]
Yeah, I tried running a pod install —verbose to try and figure out where the conflict is coming from but that wasn’t helpful. Couldn’t figure out the fix so I opened the issue.

**Comment by pm-dev** [comment]
happens on both cocoapods 0.38.0 and 0.37.2

**Comment by dhruv** [comment]
@pm-dev did you find a fix to this? Is there a way to remove MoEngage momentarily from the build?

**Comment by gautamMoEngage** [comment]
@f2prateek - The pod would be referenced via path and included in the Podfile.lock as well. Hence we are getting the issue - https://github.com/CocoaPods/CocoaPods/issues/1605.

**Comment by f2prateek** [comment]
@dhruv you might to be able to build the SDK if you remove the `Podfile.lock` file first. `rm Podfile.lock && make build`

**Comment by f2prateek** [comment]
Fix
