### ISSUE TITLE
Mixpanel integration doesn't identify properly

### ISSUE THREAD

**Issue by ryanio** [segmentio/analytics-ios#376]
I'm using Mixpanel through Segment, and when a user is using my app and signs up, Mixpanel thinks it's a different user after identify is called post-signup, as seen here:

<img width="964" alt="screen shot 2015-07-23 at 2 35 54 pm" src="https://cloud.githubusercontent.com/assets/22116/8862824/84929e30-3148-11e5-9ef7-26629f38e146.png">

Here are the Mixpanel docs on how to correctly alias/identify users:
https://mixpanel.com/help/reference/ios (section titled "Linking two user IDs")

The logic is a bit weird, but I believe the idea is you call mixpanel.createAlias: prior to the first identify, then from there you can use mixpanel.identify:

**Comment by f2prateek** [comment]
What are the calls you use to identify and alias the users via segment?

**Comment by ryanio** [comment]
Ah I totally missed that that the segment lib has an alias call. Will integrate it into my app, thanks!
