### ISSUE TITLE
Revenue being sent to Localytics in dollars rather than cents

### ISSUE THREAD

**Issue by eriklarson** [segmentio/analytics-ios#377]
Based on the documenation of the Eccomerce 'Completed Order' event one would assume that the revenue field is in full units of currency (ie. dollars) rather than cents.  We have implemented our Ecommerce events like this and it shows up properly in GA.

In SEGLocalyticsIntegration.m, the raw revenue value is being sent to Localytics here:
https://github.com/segmentio/analytics-ios/blob/master/Analytics/Integrations/Localytics/SEGLocalyticsIntegration.m#L114-L118

Localytics is expecting revenue to be in cents rather than dollars.  This causes the LTV reported in Localytics to be 1/100 of the actual value.  This isn't clearly outlined in there documentation but it is the case:
http://docs.localytics.com/#Dev/Instrument/customer-ltv.html

Please fix!

**Comment by f2prateek** [comment]
Fixed in 98b1f9f422a6a057043345f6c5fd98bf3c00fc74

**Comment by eriklarson** [comment]
This was supposedly fixed, but it's since been reverted:
https://github.com/segmentio/analytics-ios/blob/master/Analytics/Integrations/Localytics/SEGLocalyticsIntegration.m

Please fix guys ASAP!
