### ISSUE TITLE
Create dynamic framework target

### ISSUE THREAD

**Issue by schwa** [segmentio/analytics-ios#397]
Would love to see a dynamic framework target for this project.

Would make integration with carthage (http://github.com/carthage/carthage) so much easier

**Comment by travisjeffery** [comment]
Yeah I'm keen on that as well. iOS 8's adoption rate is way up there and so is the size of our static lib :D so we'll be pursuing it, don't have a timeline yet though.

**Comment by solidcell** [comment]
:+1:

**Comment by benwoodward** [comment]
Carthage support would be much appreciated. :+1: :+1: :+1:

**Comment by kleemedia** [comment]
So what is the best way to use carthage with this project?

**Comment by thbaja** [comment]
:+1:

**Comment by baek-jinoo** [comment]
:+1:

**Comment by markcleonard** [comment]
:+1:

**Comment by mootpointer** [comment]
:+1:

**Comment by marcvanolmen** [comment]
👍

**Comment by f2prateek** [comment]
This is available in the `dev` branch now.
