### ISSUE TITLE
Mixpanel version was reverted to 1.8.1

### ISSUE THREAD

**Issue by ldiqual** [segmentio/analytics-ios#400]
The `2.8.1 => 2.8.2` mixpanel change doesn't seem to be in `master` anymore:
 - Original issue: https://github.com/segmentio/analytics-ios/issues/368
 - PR: https://github.com/segmentio/analytics-ios/pull/371
 - Podfile.lock in master: https://github.com/segmentio/analytics-ios/blob/master/Podfile.lock#L18

Was there a force push to master recently? Looks like the last blame commit is from June 18th (way before the PR): https://github.com/segmentio/analytics-ios/blame/master/Podfile.lock#L18

**Comment by travisjeffery** [comment]
Thanks, not sure what happened there but it's fixed in the latest release.
