### ISSUE TITLE
XCode build fails for x86_64 and i386

### ISSUE THREAD

**Issue by dseravalli** [segmentio/analytics-ios#404]
Hi, I've integrated version 2.0.5 manually (as part of a Phonegap plugin I wrote) and it builds and works fine when running on an actual iOS ARM device, but fails when trying to build to run in simulator on my mac. Here's the error:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_JSContext", referenced from:
      objc-class-ref in Analytics(SIOSocket.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

It also fails when running `phonegap build ios` which is just a wrapper for `xcodebuild` afaik. Same error but with architecture i386.

analytics-ios 2.0.5
XCode 6.4
OS X 10.10.3

**Comment by dseravalli** [comment]
Adding the `JavascriptCore` framework to my Link Binary with Libraries list seems to solve this

**Comment by f2prateek** [comment]
Let me know if you still see this on master.

**Comment by Coreanodecalle** [comment]
5 years later, working in a (surely) totally different project, nothing related to segmentio, analytics or Phonegap, besides facing the same Undefined Symbol error... and your solution came just perfectly... I couldn't guess that JavascriptCore.framework was needed in my project... how? why?, doesn't matter as it solved my problem. 
Thanks again for sharing your solution!!
