### ISSUE TITLE
Optimizely-iOS-SDK folder structure change causing failure

### ISSUE THREAD

**Issue by jmejiaxogrp** [segmentio/analytics-ios#406]
When doing a pod install, with no changes to a previously working podfile - I'm getting errors for optimizely in SEGOptimizelyIntegration.m

#import <Optimizely-iOS-SDK/Optimizely.h> Cannot be found, instead I need to manually change it to #import <Optimizely-iOS-SDK/Optimizely/Optimizely.h>.

This is my podfile:
pod 'Analytics/AppsFlyer'
pod 'Analytics/GoogleAnalytics'
pod 'Analytics/Mixpanel'
pod 'Analytics/Quantcast'
pod 'Analytics/Optimizely'
pod 'Analytics/Tapstream'
end

**Comment by jmejiaxogrp** [comment]
The new version still has this issue, I have to manually change #import <Optimizely-iOS-SDK/Optimizely.h> to  #import <Optimizely-iOS-SDK/Optimizely/Optimizely.h> for everything to build.

**Comment by f2prateek** [comment]
Can you let me know which version of CocoaPods and Xcode you are using?

What were the changes you made to get it working?

**Comment by jmejiaa** [comment]
@f2prateek  - 
I'm using Xcode 6.4, Cocoapods 0.38.2

I have to change:
#import <Optimizely-iOS-SDK/Optimizely.h>
to:
#import <Optimizely-iOS-SDK/Optimizely/Optimizely.h>

**Comment by f2prateek** [comment]
Sorry not sure I see the difference...

> I have to change:
#import 
to:
#import

**Comment by jmejiaxogrp** [comment]
@f2prateek my apology, I deleted the relevant info..

I have to change every time I do an install/update:
#import <Optimizely-iOS-SDK/Optimizely.h>

to:
#import <Optimizely-iOS-SDK/Optimizely/Optimizely.h>

**Comment by promisenxu** [comment]
We had the same problem as well - Optimizely and UXCam. I have to change them into

#import Optimizely.h  // With "<" and ">"
#import "UXCam.h"  // With " and "

**Comment by moneymalone** [comment]
+1, see https://github.com/segmentio/analytics-ios/pull/382

**Comment by andresbrun** [comment]
+1 Same issue here with pod 0.38.2 and Xcode 7 GM

**Comment by gautamMoEngage** [comment]
+1 Same issue with pod 0.38.2 and Xcode 7 for MoEngage-SDK
