### ISSUE TITLE
Countly integration crashing app on background

### ISSUE THREAD

**Issue by dseravalli** [segmentio/analytics-ios#407]
Hi, I have Analytics 2.0.5 manually installed into my app, however when I background the app it crashes with this error:

```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Cannot create an NSPersistentStoreCoordinator with a nil model'
```

It is being thrown from the Countly library. I am not using Countly and don't have it enabled. My enabled integrations are Mixpanel and Appsflyer and they appear to be working fine, except Mixpanel flushes its queue on background which is currently broken by this Countly thing.

XCode 6.4
iOS 8
Analytics 2.0.5

**Comment by dseravalli** [comment]
Manually including Countly.xcdatamodeld into the project solves this.
https://github.com/Countly/countly-sdk-js/tree/master/src/ios/sdk

**Comment by f2prateek** [comment]
Is this for a Phonegap app?

**Comment by dseravalli** [comment]
Yes I wrote a Segment phonegap plugin that wraps your sdk

**Comment by sloops77** [comment]
Also have this problem with a trigger.io module

**Comment by iagomr** [comment]
I have the same issue with a Swift native app

**Comment by asoviche** [comment]
Same issue with Segment.io :)

**Comment by f2prateek** [comment]
Please reopen against the integration if this is still an issue — https://github.com/segment-integrations/analytics-ios-integration-countly
