### ISSUE TITLE
"The 'Pods' target has transitive dependencies that include static binaries.

### ISSUE THREAD

**Issue by pasevin** [segmentio/analytics-ios#410]
Hi,
We're having a huge issue, which prevents us from using Segment.io Google Analytics and Flurry integrations.
It seems that it is not possible to install these subspecs with the latest cocoapods and Swift.
Did anyone manage to make it work?

Using cocoapods 0.38.2 and "use_frameworks!" which is necessary for Swift based pods.

**Comment by f2prateek** [comment]
Flurry is distributed only as a static binary - nothing we can do about that. https://github.com/CocoaPods/Specs/blob/master/Specs/FlurrySDK/6.7.0/FlurrySDK.podspec.json#L49

Maybe try asking them if they can change their packaging?
