### ISSUE TITLE
FlurrySDK deprecated

### ISSUE THREAD

**Issue by angela-** [segmentio/analytics-ios#421]
Hi,

I'm using pod 'Analtyics/Flurry' for the cocoapods integration. I'm getting this warning on pod update:

[!] FlurrySDK has been deprecated in favor of Flurry-iOS-SDK

**Comment by julianwa** [comment]
:+1:

**Comment by MaxKramer** [comment]
+1, lets get this merged with https://github.com/segmentio/analytics-ios/issues/427

**Comment by angela-** [comment]
was able to get the updated version with the recent tag v2.0.14 but had to hard code the repo.

```pod 'Analytics/Flurry', :git => 'https://github.com/segmentio/analytics-ios.git'```

**Comment by f2prateek** [comment]
Flurry SDK updated to 7.1.0.

**Comment by charlesmchen** [comment]
+1

**Comment by 942v** [comment]
+1

**Comment by f2prateek** [comment]
We've moved off the deprecated SDK.
