### ISSUE TITLE
Google integration makes metrics based on dimension keys instead of metric keys

### ISSUE THREAD

**Issue by aleffert** [segmentio/analytics-ios#422]
See https://github.com/segmentio/analytics-ios/blob/4c4364f0bdee6064cc17656af8fe431fa6db9215/Analytics/Integrations/GoogleAnalytics/SEGGoogleAnalyticsIntegration.m#L208

I think it should say "metricString" instead of "dimensionString"

The compiler can catch errors like this if you build with the unused variable warning enabled and warnings as errors.

**Comment by f2prateek** [comment]
Ah, I think it sneaked through the refactor, sorry about that!
