### ISSUE TITLE
Bundled AppsFlyer SDK not compatible with iOS 9

### ISSUE THREAD

**Issue by julianwa** [segmentio/analytics-ios#426]
Current version: [2.5.3.15.1](https://github.com/CocoaPods/Specs/blob/master/Specs/Analytics/2.0.9/Analytics.podspec.json#L97)
Desired version: > v3.3.0
See https://support.appsflyer.com/entries/25458906-iOS-SDK-Integration-Guide-v3-3-x-New-API-

**Comment by ryanio** [comment]
+1, this is blocking me right now in upgrading to iOS 9. Can we get a quick version bump?
