### ISSUE TITLE
Bundled Flurry SDK not compatible with iOS 9

### ISSUE THREAD

**Issue by julianwa** [segmentio/analytics-ios#427]
Current version: [6.5.0](https://github.com/CocoaPods/Specs/blob/master/Specs/Analytics/2.0.9/Analytics.podspec.json#L222)
Desired version: 7.1.1
See https://developer.yahoo.com/flurry/docs/releasenotes/archived-releasenotes/ios/#version-7-1-1-9-15-2015

**Comment by johnryan** [comment]
Any update on this?

**Comment by charlesmchen** [comment]
+1

**Comment by charlesmchen** [comment]
There are well-documented crashes in the current bundled version of the Flurry SDK:

  * http://stackoverflow.com/questions/30242618/flurry-retransmitnotsentblocks-crash
  * https://github.com/flurry/FlurryIntegrationSamples-iOS/issues/1
  * https://github.com/dbgrandi/Flurry/issues/36

Please update!

**Comment by angela-** [comment]
+1

**Comment by f2prateek** [comment]
The Flurry SDK has been updated to 7.1.0 which supports iOS 9.

**Comment by julianwa** [comment]
Thanks!
