### ISSUE TITLE
Disabled Analytics still sends requests when testing

### ISSUE THREAD

**Issue by jonah-williams** [segmentio/analytics-ios#431]
Hey folks, I ran into a couple of issues updating an app to Swift 2 and while using Analytics 2.0.6 while using only the Segment subspec (`pod 'Analytics/Segmentio'`).

A call to `SEGAnalytics.setupWithConfiguration` is required. Otherwise the first access of `sharedAnalytics` hits an assert on https://github.com/segmentio/analytics-ios/blob/master/Analytics/SEGAnalytics.m#L313. That's not necessarily wrong but it means that when I disable normal app delegate behavior while running unit tests I need to still configure and disable SEGAnalytics. e.g.

        let configuration = SEGAnalyticsConfiguration(writeKey: "")
        SEGAnalytics.setupWithConfiguration(configuration)
        SEGAnalytics.sharedAnalytics().disable()

That was working great until I migrated this project to Xcode 7 and Swift 2. Now I'm finding that disable does not halt the timer declared at https://github.com/segmentio/analytics-ios/blob/master/Analytics/Integrations/Segmentio/SEGSegmentioIntegration.m#L101 so that calls `flush` and now I have to introduce a global stub for network requests to `https://api.segment.io/v1/import` to get my tests to run (I'm using https://github.com/luisobo/Nocilla which will raise in response to unexpected network requests during tests).

~~Perhaps more importantly it looks like anyone who is relying on `disable` to avoid sending data in an app will not see that intent respected.~~

**Comment by f2prateek** [comment]
`disable` will only stop accepting any further messages, but will keep continue to process and upload and previously enqueued messages.

**Comment by jonah-williams** [comment]
That seems reasonable but given that the code snipped above is the entirety of my `applicationDidFinishLaunching` method when running tests I'm not sure what could possibly have been enqueued.

**Comment by f2prateek** [comment]
Could you enable debugging and share some logs? Maybe something is cached in the queue from a previous run?

**Comment by jonah-williams** [comment]
Sure thing @f2prateek, on further testing it looks like you're right. Events queued during a debug run of the app can be sent when I then attempt to run tests for that app. This is somewhat surprising given that the events are being sent from a completely different `SEGAnalyticsConfiguration` with a different write key. It's also inconvenient that I need to guard against state leaking from debug builds into test runs.
I'm not yet sure why I never saw this occur during an Xcode 6 build of the same app.

**Comment by f2prateek** [comment]
Yeah our SDK isn't currently designed to work with multiple writeKeys in the same project, so none of the caches are namespaced by writeKey. You could call `reset` between your tests to clear the app state though. This might not work for bundled integrations that  don't expose a similar method, but it will certainly clear the queue used to upload events to Segment — https://github.com/segmentio/analytics-ios/blob/master/Analytics/Integrations/Segmentio/SEGSegmentioIntegration.m#L469.
