### ISSUE TITLE
Contributor documentation link is broken

### ISSUE THREAD

**Issue by jonah-williams** [segmentio/analytics-ios#433]
https://github.com/segmentio/analytics-ios/blob/master/README.md#development links to `https://segmentio.hackpad.com/Engineering-Getting-started-with-the-iOS-SDK-1LQqD1q9SKQ` which redirects to `https://notes.dropbox.com/48Y0gURcww1` and which is not accessible to the public. Is that intentional?

https://github.com/segmentio/analytics-ios/blob/master/CONTRIBUTING.md links to  `https://cloudup.com/cfGgfHPwVxy` which is publicly accessible.

Seems like these should be the same resource (so they don't get out of sync) and be generally available to encourage participation.

**Comment by f2prateek** [comment]
Thanks, moved that link to point to the Contributing.md file, which links to the publicly accessible doc!
