### ISSUE TITLE
TvOS Support

### ISSUE THREAD

**Issue by dbachrach** [segmentio/analytics-ios#440]
When including the analytics Pod in a TvOS app, there are failures because of the use of certain CoreLocation features and CoreTelephony features.

Are there plans to update the SDK to support TvOS?

**Comment by dbachrach** [comment]
I've pushed to my fork with the needed `#ifdef` fixes:

https://github.com/dbachrach/analytics-ios/commit/c8ef2b58af94d155ffabe49c412a89bcb4e52f1d

**Comment by f2prateek** [comment]
Ah nice! This was definitely on our roadmap but haven't had time to look into it. Mind sending this as a PR? Seems pretty easy if that's all that was need, @travisjeffery and I can review it.

**Comment by mootpointer** [comment]
This works, but there is a limitation with tvOS. You can't trust on the filesystem to be persistent. That means that things can disappear on you when the cache gets swept.

We've been using this fork for a little while, but have run into instances where users stopped being tracked for apparently no reason, then I remembered that Segment seems to store things in Application Support. That obviously is a Bad Thing™ when that's only a temporary directory.

**Comment by charlie-gbox** [comment]
we really need the support. any estimated about it?

**Comment by joeltello** [comment]
what's the status on this?

**Comment by saverchenkov** [comment]
+1 for this one!

**Comment by charlires** [comment]
We are all waiting for TvOS support :+1:

**Comment by marcopetkovski** [comment]
+1 can't wait!

**Comment by justindhill** [comment]
It looks like @mootpointer resolved the outstanding issues by augmenting the disk store with NSUserDefaults. Are you guys open to a PR that will add the appropriate ifdefs and add declaration of tvOS support in the Podspec?

**Comment by f2prateek** [comment]
@justindhill sounds good, we had to revert the changes since we don't want to use NSUserDefaults on iOS (but do want it on tvOS). Happy to review a PR that falls back to NSUserDefaults on tvOS and updates the Podspec (bonus points if it supports Carthage!).

**Comment by f2prateek** [comment]
Closed by #572 

To try it out:
`  pod 'Analytics', :git => 'https://github.com/segmentio/analytics-ios.git', :branch => 'dev'`
