### ISSUE TITLE
Is it possible to include Google Analytics without GoogleIDFSASupport?

### ISSUE THREAD

**Issue by joemasilotti** [segmentio/analytics-ios#442]
I would like to include only the Google Analytics subpod, but not it's optional dependency GoogleIDFSASupport. The latter does not yet support bitcode (as of 3.12.0) and is holding my app back from supporting it.

**Comment by gsempe** [comment]
I have the same exact issue. It's very annoying that Google did not have fixed their library build already ([ga-mobile-app-analytics](https://groups.google.com/forum/#!topic/ga-mobile-app-analytics/d6ML4BKBBeY), [analytics-issues](https://code.google.com/p/analytics-issues/issues/detail?id=671))
Maybe Segment can provide us a solution. Very, very annoying point...

**Comment by pasevin** [comment]
this is still an issue, GoogleIDFSASupport is making latest Google Analytics subpod unusable

**Comment by f2prateek** [comment]
Closed by https://github.com/segment-integrations/analytics-ios-integration-google-analytics/issues/1
