### ISSUE TITLE
Test case failing - "These headers need to be made public"

### ISSUE THREAD

**Issue by gautamMoEngage** [segmentio/analytics-ios#446]
I'm getting the error "these headers need to be made public". Also, headers which are in Pods are not copied in the Segment folder. I see that pull requests (Apptimize, Amplitude, Taplytics) are also facing issues, while all they are trying to do it update the pod, same as me. I might be wrong, but can you look at it once if there might be an issue on your end.

**Comment by f2prateek** [comment]
You need to export the headers that are public in your library to be available via Segment.
