### ISSUE TITLE
mixpanel.time_event possible in Segment?

### ISSUE THREAD

**Issue by benwoodward** [segmentio/analytics-ios#461]
Is it possible to log the data needed to measure the time of a user's session in Mixpanel, using Segment?

https://mixpanel.com/help/reference/javascript-full-api-reference#mixpanel.time_event

https://mixpanel.com/blog/2015/06/22/community-tip-session-length-tracking

**Comment by f2prateek** [comment]
Yes, you'll have to manually call the `timeEvent` method in the Mixpanel SDK, and the actual event tracking will be through Segment.

https://mixpanel.com/help/reference/ios#event-timing

```
[mixpanel timeEvent:@"Image Upload"];
// do some stuff.
[[SEGAnalytics sharedInstance] track:@"Image Upload"];
```

**Comment by alejandro-vori** [comment]
Hello, is this still necessary in 2021? I'm wondering how to track some sort of time event through Segment without requiring Mixpanel's **timeEvent**

**Comment by luiscarlin** [comment]
^ wondering the same @alejandro-vori. Did you ever find the answer? I think I will have to add the mixpanel sdk to my react-native project
