### ISSUE TITLE
Reset doesn't remove traits

### ISSUE THREAD

**Issue by jdivittorio3** [segmentio/analytics-ios#468]
Calling the reset method does not reset traits in the segment debugger. Traits remain the same as the previous user prior to sign out.

Analytics 2.0.17 (tried an older version with 1.11.0 as well)
CocoaPods version 0.39.0
Xcode 7.1

**Comment by jdivittorio3** [comment]
When using reset, the userID does get removed but traits for track calls are still associated with the previous user. Traits are still cached on the the device after reset is called and the problem occurs. When you close out of the app and reopen, traits are then removed.

**Comment by hiBrianLee** [comment]
@jdivittorio3 enabled the Segment debug logs with `[SEGAnalytics debug:YES];` and the log showed what @jdivittorio3 described above. The payload after `reset` didn't have `userID`, but still had all the `traits` which weren't cleared. It only cleared if you restarted the app. Is it possible that the in-memory traits are not being cleared on `reset`?

The test case for `reset` also doesn't seem to test for `traits` clearing - https://github.com/segmentio/analytics-ios/blob/master/AnalyticsTests/SegmentioTests.m#L217

```
- (void)testReset
{
    self.integration.configuration.flushAt = 2;
    trvs_assertNotificationsNotObserved(self, ^{
      [self.integration track:self.event properties:self.properties options:self.options];

      NSString *anonymousId = self.integration.anonymousId;

      [self.integration reset];

      EXP_expect(self.integration.queue.count).will.equal(0);
      XCTAssertNotEqualObjects(anonymousId, self.integration.anonymousId);
    }, SEGSegmentioRequestDidSucceedNotification, SEGSegmentioDidSendRequestNotification, nil);
}
```

Any ideas @f2prateek?

**Comment by mcstoufer** [comment]
Looking at the SEGSegmentIntegration.m file, it may also be that crazy closure being associated with the context["traits"] dict key. I've never seen syntax like that before, and it *may* be holding onto traits even after the traits mutable dict has been re-assigned to a new empty one.

**Comment by f2prateek** [comment]
Fixed in https://github.com/segmentio/analytics-ios/commit/7bed9eded4480034e26f3830d54d093d8ca41954 (line 460)
