### ISSUE TITLE
Manual iOS SDK install update?

### ISSUE THREAD

**Issue by gamesbydre** [segmentio/analytics-ios#477]
Hello, I was curious if there is an update on the status of the manual install download link for the Segment iOS SDK.  I wrote support an email a few weeks ago and I was told it would be back up soon.  It's been about 3 weeks since my initial contact, any update from the dev team?
Thanks.

**Comment by f2prateek** [comment]
It will still be a few more weeks, and you'll only be able to build with the Segment integration. If you need the bundled integrations, you can build an older release manually.

**Comment by f2prateek** [comment]
We've decide to depreciate manual installation going forwards. The only way to use Segment is to use CocoaPods.
