### ISSUE TITLE
Can't integrate latest stable release due to Kahuna dependency version mismatch

### ISSUE THREAD

**Issue by DimaVartanian** [segmentio/analytics-ios#480]
Follow-up to this issue:
https://github.com/segmentio/analytics-ios/issues/479

I'm trying to use the pod for `2.0.17` which is the latest stable release but I can't because the pod has a dependency on an old version of Kahuna:

     Unable to satisfy the following requirements:
     - Kahuna (= 2.3.1) required by Podfile
     - Kahuna (= 2.0.3) required by Analytics/Kahuna (2.0.17)`

Looks like the newer (alpha) versions don't seem to have this issue. Would it be possible to get a stable release with the dependency fixed?

**Comment by f2prateek** [comment]
The newer version doesn't have this issue because it doesn't contain any integrations (including Kahuna). For now you'll have to keep using Kahuna 2.0.3, at least until v3 is released (which should be by end of next week at the latest).

**Comment by f2prateek** [comment]
You can use the Kahuna integration now (https://github.com/segment-integrations/analytics-ios-integration-kahuna) with v3 of the Segment library. It's still in alpha, will be making a stable release soon.
