### ISSUE TITLE
Custom Anonymous ID

### ISSUE THREAD

**Issue by alloy** [segmentio/analytics-ios#482]
I’m wondering if there’s a reason for not allowing a custom Anonymous ID when using this SDK? [The API docs](https://segment.com/docs/spec/identify/#anonymous-id) make it seem like it’s perfectly fine to supply your own.

In our case we already have a UUID for unauthenticated users, which would make a lot of sense as the Anonymous ID.

**Comment by mcstoufer** [comment]
As long as its unique, that would be ok. The initial call to alias() that to a real authenticated will work. However, later alias() calls from the same fixed anon UUID to a new real id will then have undefined behavior. At least that is what I gleaned from the docs as well.

**Comment by alloy** [comment]
@mcstoufer I don’t really want to use the alias feature in this case, mainly because we use a lib that abstracts away details about the analytics provider (ARAnalytics).

**Comment by f2prateek** [comment]
Adding a method to set the anonymous ID should be fine. We haven't had people ask us for this or provide a strong use case yet, so it hadn't been added yet.
