### ISSUE TITLE
What is the latest stable version?

### ISSUE THREAD

**Issue by ldiqual** [segmentio/analytics-ios#486]
I'm getting really confused by what is the latest stable version available. Cocoapods says `3.0.4-alpha` is the latest version, though `3.0.1` was pushed a day after, while your changelog says that `3.0.4-alpha` was published on the same day than `3.0.1`.

Why was `3.0.2-alpha` published 13 days before `3.0.1`? Does it mean there will be `3.0.2, 3, 4` soon? What is your versioning protocol here?

**Comment by f2prateek** [comment]
Anything ending with alpha is not a stable version. As of right now 3.0.1 is the latest stable version.

Think of alpha and stable as channels that run in parallel independently of each other. So `x.y.z-alpha` has no correlation to `x.y.z`.

e.g `3.0.4-alpha` can be a release both after `3.0.1` or before. All it guarantees is that `3.0.4-alpha` was after `3.0.3-alpha`.
