### ISSUE TITLE
Analytics.framework has ihasapp in it.

### ISSUE THREAD

**Issue by abhijeetkmr** [segmentio/analytics-ios#489]
Recently got rejected by apple with message stating  
"Your app checks for all apps installed on the device by scanning all known URL schemes using a service called iHasApp."
 i was pretty sure i wasn't using anything like that.
but i made a 
"grep -r "ihasapp" on root folder and found out that segment analytics.framework has ihasapp references in it.
what should we do now ??

**Comment by f2prateek** [comment]
Where are we doing this? Please provide a link to the code on Github.

**Comment by abhijeetkmr** [comment]
its in ios sdk, manually installation.
in three files
1) Segment/Analytics.framework/Analytics matches
2)Segment/Analytics.framework/Versions/Current/Analytics
3) Segment/Analytics.framework/Versions/A/Analytics

check the manually dowload SDK.

**Comment by f2prateek** [comment]
I don't see any references in the latest version so you should be able to use that.

Also Segment is likely not referencing those in the version you are using, it's probably one of the tools.

**Comment by abhijeetkmr** [comment]
can you give me the latest version link. where we can install manually copying the framework files ?
I will check it also before use.

**Comment by f2prateek** [comment]
We're not providing a framework anymore, you can build it manually or use CocoaPods.
