### ISSUE TITLE
Pod fails to install with SWIFT use_frameworks!

### ISSUE THREAD

**Issue by snibbe** [segmentio/analytics-ios#493]
It's impossible to use this library with SWIFT and Segment-GoogleAnalytics because the Segment-GoogleAnalytics pod fails to install with this error when you have use_frameworks! set:

**[!] The 'Pods-Eyegroove' target has transitive dependencies that include static binaries: (/Users/snibbe/dev/apps/eyegroove-ios-3.0/Pods/GoogleAnalytics/Libraries/libGoogleAnalytics.a and /Users/snibbe/dev/apps/eyegroove-ios-3.0/Pods/GoogleIDFASupport/Libraries/libAdIdAccessLibrary.a)**

This seems to be a known error with static dependencies and SWIFT/Podfiles: 

https://github.com/CocoaPods/CocoaPods/issues/3194
https://github.com/CocoaPods/CocoaPods/issues/4053
https://code.google.com/p/analytics-issues/issues/detail?id=609

**Comment by f2prateek** [comment]
See https://github.com/segment-integrations/analytics-ios-integration-google-analytics/issues/3.
