### ISSUE TITLE
new libraries appending "Segment.io: false" 

### ISSUE THREAD

**Issue by hankim813** [segmentio/analytics-ios#496]
We started appending this in our newest version inside the `integrations` object to denote that you have bundled the Segment integration. Segment integration is bundled by default when you install the mobile library so this piece is only relevant in debugging process for Segment success engineers... but causes confusion to our customers.

The only time that would be `true` is if a user manually stripped that integration using manual classes... which is probably not too often since it would mean that you can't send server side events.

I would urge that we revert back to our older version's behavior and just leave that out to prevent customers from being confused.

@f2prateek @sperand-io

**Comment by ladanazita** [comment]
@f2prateek @sperand-io I've had some customers ping about this. Any ideas if we can add this to this sprint? Someone is using a WebHook to push the data back into their ElasticSearch but ElasticSearch throws an error when fields  have a dot (".") in their field name.

**Comment by f2prateek** [comment]
We have other integrations that use a . in their name (e.g. Hull.io). They should transform the `.` delimited keys in their webhook server.
