### ISSUE TITLE
How to avoid dependent libraries installation using pod Analytics ?

### ISSUE THREAD

**Issue by tariq235** [segmentio/analytics-ios#497]
pod 'Analytics', '~> 2.0.0' installed all 100s of dependent libraries but I need only MixPanel.

Installing Kahuna (2.0.3)
Installing Localytics (3.5.1)
Installing Mixpanel 2.8.3 (was 2.9.0)
Installing MoEngage-iOS-SDK (1.4.3)
Installing GoogleAnalytics (3.13.0)
Installing GoogleIDFASupport (3.12.0)

-----

Is there any way to use only mixpanel ?

**Comment by f2prateek** [comment]
Use `pod 'Analytics', '~> 3.0.0'`
