### ISSUE TITLE
Mutating method sent to immutable object

### ISSUE THREAD

**Issue by Jonovono** [segmentio/analytics-ios#501]
Hi. I am getting this error when using this library in an Swift project.

I have it set up like so:

        func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        // Override point for customization after application launch.
        LaunchKit.launchWithToken("s6jJFY3D5oQ0oZ-WslvxlwMuqVloA_BAQwnI_kOdpM-2")
        
        var segAnalyticsConfig = SEGAnalyticsConfiguration(writeKey: "TaM8RVbmneeYgowBHV1esvhApWgO54jF")
        SEGAnalytics.setupWithConfiguration(segAnalyticsConfig)
        
        return true
    }

Then I use it like:
  
            SEGAnalytics.sharedAnalytics().track(event)
        SEGAnalytics.sharedAnalytics().flush()

This seems to be the message in the logs:

    <0x13ddbf750:SEGSegmentIntegration, TaM8RVbmneeYgowBHV1esvhApWgO54jF> Error writing payload: -[__NSCFArray insertObject:atIndex:]: mutating method sent to immutable object

It was working for a bit. I saw one identity event show up in the debugger.

**Comment by f2prateek** [comment]
Should be fixed now.

**Comment by Jonovono** [comment]
Great, thanks a lot @f2prateek. It's working now :)
