### ISSUE TITLE
Crash when app entering background.

### ISSUE THREAD

**Issue by iosMileyenda** [segmentio/analytics-ios#506]
UIApplicationDidEnterBackgroundNotification on integration: Segment.io

'NSInvalidArgumentException', reason: '-[NSInvocation setArgument:atIndex:]: index (2) out of bounds [-1, 1]'

Version: Latest.

**Comment by Maxim-Inv** [comment]
I had this crash too. I have made fix and pull request https://github.com/segmentio/analytics-ios/pull/505

**Comment by iosMileyenda** [comment]
I tried your fix but the problem persists.
    
if (i + 2 <= signature.numberOfArguments)
What signature contains? It's a bad idea accessing array elements using index and "+"

Maybe is better this way...
if (i + 2 <= arguments.count)

**Comment by Maxim-Inv** [comment]
You should use if (i + 2 < signature.numberOfArguments). Sorry, fixed in a second commit https://github.com/Maxim-Inv/analytics-ios/commit/89d02d6f16231920779348922d921243103fc89b

**Comment by Maxim-Inv** [comment]
If you use cocoapods in your project you can use pod 'Analytics', :git => 'https://github.com/Maxim-Inv/analytics-ios', until pull request will be accepted

**Comment by iosMileyenda** [comment]
It's Ok now :+1:

**Comment by DimaVartanian** [comment]
Getting this crash too

**Comment by f2prateek** [comment]
I think this might be the issue - https://github.com/segmentio/analytics-ios/pull/500, might be better to just revert that.

**Comment by f2prateek** [comment]
@DimaVartanian @iosMileyenda @Maxim-Inv can you try master to verify the fix - https://github.com/segmentio/analytics-ios/commit/760be85a5119c2e8bd31a745ce2ec30385a0ad69? I can make a release after we can verify it.

`pod 'Analytics', :git => 'https://github.com/segmentio/analytics-ios'`

**Comment by Wenzhi** [comment]
@f2prateek yea it seems the crash relates to my code. I didn't know that the `didEnterBackground` is implemented in the SEGSegmentIntegration without argument. 

I think @Maxim-Inv has a good fix for this.

**Comment by f2prateek** [comment]
Fixed in 3.0.6
