### ISSUE TITLE
NSGenericException SEGSegmentioIntegration.m line 401 in [SEGSegmentioIntegration queuePayload:] 

### ISSUE THREAD

**Issue by killmyrene** [segmentio/analytics-ios#507]
Hello, 

We've been using this analytics SDK v1.12.0 and have deployed our app on the App Store and we have received crash reports pointing this SDK. Crash log is attached. 

Based on this url, https://github.com/segmentio/analytics-ios/issues/187, it has been already fixed in 1.5.x but it is still apparent in 1.12.0. So I'm considering options to try upgrading it to v3.0.5. Problem is that implementations between here and there have completely changed. Needing insights on steps to upgrade it without hassle on our end. The app is using AppsFlyer, Mixpanel Segmentio, Kahuna integrations and it is not using Cocoapods by the way. 

Thanks

[log.txt](https://github.com/segmentio/analytics-ios/files/87944/log.txt)

**Comment by f2prateek** [comment]
Upgrading docs are available here https://segment.com/docs/libraries/ios/#migrating-from-v1-or-v2

**Comment by killmyrene** [comment]
I'm missing integration support for AppsFlyer and it doesnt exist in one of your branches. There's the segmentio integration but its mentioned that its been changed to a different implementation. How would I support AppsFlyer in v3?

**Comment by f2prateek** [comment]
You can use the 2.x releases while that Appsflyer is migrated for v3 in that case.
