### ISSUE TITLE
Add delegate method for when integrations are available.

### ISSUE THREAD

**Issue by jeiting** [segmentio/analytics-ios#513]
Our app uses a couple of features in specific integrations that require us to still use the integration SDK. In order to know when the integration is ready to be used, I have to defer use until after Segment has pulled the configuration if I want to be able to remove hardcoded configuration from our app. I did this by extern-ing the `SEGAnalyticsIntegrationDidStart` and listening for the integration I'm interested in.

It would be great if this were a delegate method on a `SEGAnalytics` delegate or implemented as a documented notification. 

If this sounds like a reasonable request I can submit a PR.

**Comment by f2prateek** [comment]
That's actually exactly what the `SEGAnalyticsIntegrationDidStart` is meant for, for users to know when an integration is initialized and take some action.

**Comment by jeiting** [comment]
Ah ok, I couldn't find it exposed in any headers so I had to declare it `extern` in one of my own files to use the symbol. It would be good if it were in the header and documented, so that I know I'm not just relying on implementation details.

**Comment by f2prateek** [comment]
Makes sense, happy to accept PRs to improve the documentation!

**Comment by benmarten** [comment]
Created PR to make the notification key string extern: https://github.com/segmentio/analytics-ios/pull/520

**Comment by f2prateek** [comment]
(still keeping this open until we add docs as well)

**Comment by f2prateek** [comment]
Added docs
