### ISSUE TITLE
iOS 9 Analyzer potential leak

### ISSUE THREAD

**Issue by mruvim** [segmentio/analytics-ios#514]
Xcode analyzer returns two potential leaks on iOS 9

Version: Analytics 3.0.7

Issues:
`SEGReachability.m:115:9: Potential leak of an object stored into 'ref'`
`SEGReachability.m:131:9: Potential leak of an object stored into 'ref'`

Steps to reproduce 
- Add library to a project
- Run Xcode analyzer

**Comment by dbburgess** [comment]
I think these are fixed by #517.

**Comment by f2prateek** [comment]
Closed by #551
