### ISSUE TITLE
No way to retrieve auto-generated Anonymous ID

### ISSUE THREAD

**Issue by martinc** [segmentio/analytics-ios#527]
It doesn't look like there is a way to access the anonymous ID. We'd like to access it to send this to our backend so it can use the same Anonymous ID. Would this be possible?

Alternatively, it looks like there is a way to set a custom Anonymous ID in an identify call, but it's not well documented. How do I set a custom anonymous ID before any track or identify calls are called?

**Comment by sperand-io** [comment]
@martinc thanks for flagging! @wcjohnson11 @f2prateek mind chiming in here? If getting/setting the anon id is not currently supported let me know so we can get it on the roadmap!

**Comment by f2prateek** [comment]
It is possible to set anonymous id (use the options parameter in identify call).

**Comment by sperand-io** [comment]
@martinc does the ability to set the anonId explicitly allow a workaround for your use case? if not, let us know, and we'll get you a more realistic expectation for when we'll have a getter exposed.

Cheers!

**Comment by martinc** [comment]
@sperand-io Sorry for the delay. I would rather just have an accessor to the automatically generated anonymous ID, so that I could send it to the server first, and deal with the caching of it since you guys are already taking care of that.

**Comment by f2prateek** [comment]
Closed by #550

**Comment by martinc** [comment]
Hi, I see this is mentioned in the release notes for 3.2.6, but it looks like the redux branch is not yet merged. Was this a mistake? Is there a timetable for merging it in? Thanks.

**Comment by f2prateek** [comment]
Sorry this was accidentally overriden by the Carthage changes https://github.com/segmentio/analytics-ios/commit/addd00497bb8db20c37f61464ef6dd83d4a767ea. We'll add it back.

**Comment by f2prateek** [comment]
Closed by #577
