### ISSUE TITLE
Files are included in iTunes/iCloud backup

### ISSUE THREAD

**Issue by RetepV** [segmentio/analytics-ios#537]
Hi,

We found out that the analytics files are saved in the Library/Application Support folder. Files in this folder are included in the iTunes/iCloud backup, unless marked as 'exclude from backup'.

This can be a reason for rejection by Apple (if the files become large), so I hope you can change this.

There are two solutions:

1. Mark folder and files with NSURLIsExcludedFromBackupKey. I.e. use this: `BOOL success = [URL setResourceValue: [NSNumber numberWithBool: YES] forKey: NSURLIsExcludedFromBackupKey error: &error];`
2. Store all files in Library/Caches.

More info: https://developer.apple.com/library/ios/qa/qa1719/_index.html

Cheers!
Peter

**Comment by sperand-io** [comment]
Thanks so much for the flag and proposed solutions, @RetepV! We really appreciate it :)

cc'ing @tonyxiao and @f2prateek who will choose the best solution, and then we will let you know when we have a plan for implementing!
