### ISSUE TITLE
Flush Timer not fired in SEGSegmentIntegration.m

### ISSUE THREAD

**Issue by underscoretang** [segmentio/analytics-ios#558]
https://github.com/segmentio/analytics-ios/blob/master/Pod/Classes/Internal/SEGSegmentIntegration.m#L93

This timer is being created in the io.segment.analytics thread which doesn't have run loops so the timer never fires. 

You can either create the timer on the main thread, or add it too the mainRunLoop

http://stackoverflow.com/questions/12323531/difference-in-scheduling-nstimer-in-main-thread-and-background-thread

**Comment by f2prateek** [comment]
Thanks! I have a quick fix here — https://github.com/segmentio/analytics-ios/pull/560.

We might also investigate initializing the integration on the main thread so the integrations don't need to worry about being initialized off the main thread.
