### ISSUE TITLE
Carthage support?

### ISSUE THREAD

**Issue by barfoon** [segmentio/analytics-ios#569]
Carthage support?

We've been trying to get this library to work via Carthage and we are seeing:

Added:
`github "segmentio/analytics-ios"`

> '* Skipped building analytics-ios due to the error:
> "Dependency "analytics-ios" has no shared framework schemes"
> "If you believe this to be an error, please file an issue with the maintainers at https://github.com/segmentio/analytics-ios/issues/new"

Any help to get this resolved, or the framework file generated & linked would be greatly appreciated. Cheers,

**Comment by f2prateek** [comment]
Ah you'll need to use the `master` branch for now.

https://github.com/segmentio/analytics-ios/blob/dev/CONTRIBUTING.md#contributing

> Development occurs on the dev branch, and pull requests must be opened against the dev branch. Every second Wednesday, master is taggged and released, and dev is merged into master. In general, code will be available on master for two weeks before being tagged as a stable release.

So effectively it's on `master` now, and will be released as a tagged release on Wednesday.

So in your Cartfile you can do:

`github "segmentio/analytics-ios" "master"`
