### ISSUE TITLE
Typo in Assert on dev

### ISSUE THREAD

**Issue by martinc** [segmentio/analytics-ios#582]
You have a bug on your dev branch. There is a typo in an assert.

Line 259 of SEGAnalytics.m:
    NSCAssert2(userId.length > 0 > traits.count > 0, @"either userId (%@) or traits (%@) must be provided.", userId, traits);

Should be:
    NSCAssert2(userId.length > 0 || traits.count > 0, @"either userId (%@) or traits (%@) must be provided.", userId, traits);

**Comment by f2prateek** [comment]
Close by #583
