### ISSUE TITLE
NSData GZIP category conflict

### ISSUE THREAD

**Issue by milancermak** [segmentio/analytics-ios#584]
The [recent addition](https://github.com/segmentio/analytics-ios/commit/f933d9fa22920e154a29895723a43bd932d76372#diff-704e9c50b880f3c8d380adfce00b5ea8) or NSData+GZIP causes a conflict with another library I use (KSCrash) in my project, because it also [defines the same category](https://github.com/kstenerud/KSCrash/blob/3a905fd0e2d7261257adc9298296cce0e41381b8/Source/KSCrash/Reporting/Filters/Tools/NSData%2BGZip.h).

I'm not a Cocoapods expert, but I think this could be prevented if the podspec of this library would list [public headers](http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/#about-public-headers) correctly. I'm guessing everything inside `Internal/` should not be public anyway.

**Comment by f2prateek** [comment]
This was fixed https://github.com/segmentio/analytics-ios/blob/master/Analytics/Classes/Internal/NSData%2BGZIP.m#L54, it will be part of the next release.

Some of the internal classes are used by integrations (which are built outside of this library) which is why we can't mark them as private just yet.

**Comment by milancermak** [comment]
It's not a conflict in method names, sorry for the incorrect description of the isuse.

The problem is that the other library also has a Gzip category on NSData, so when it tries to call for example `gunzippedWithError:`, the compiler looks into the Analytics' GZip category and doesn't find it.

The error I get is `No visible @interface for 'NSData' declares the selector 'gunzippedWithError:'`.

**Comment by f2prateek** [comment]
I see - so I think renaming our extension to `NSData+SEGGZip` should work for now.

**Comment by milancermak** [comment]
Yeah, that should be fine too.
