### ISSUE TITLE
Add OS X compatibility

### ISSUE THREAD

**Issue by marsepu** [segmentio/analytics-ios#590]
Hi All, I use the `analytics-ios` cocoapod regularly for iOS projects. Currently, taking over a Mac app that needs analytics. I thought I could help by making this pod more cross platform compatible so I submitted PR #589

**Comment by toddkramer** [comment]
Hi, is there any update on when macOS support will be added? I saw that both macOS and Server-Side Swift / SPM are on the roadmap and that you're working on a Swift library with a macOS deployment target, which would be great. In the meantime, just adding basic macOS support here would be very helpful. Thanks.

@f2prateek @tonyxiao

**Comment by tonyxiao** [comment]
Hey @toddkramer It's on our roadmap but at the moment we're focusing on some other improvements (like middlewares) that are building blocks to macOS support.

**Comment by mcmurrym** [comment]
We have added support to macOS https://github.com/pluralsight/analytics-ios I some point I want to create a pull request, but I would appreciate some experience macOS devs to look it over. The major differences are not reacting to background and foreground events as they do not exist, not creating a background flush task on background event, again, doesn't exist and adding support to `- (NSDictionary *)staticContext` in `SEGSegmentIntegration.m` for macOS system information

**Comment by tonyxiao** [comment]
@mcmurrym Got it. I built a few macOS apps back in 2012 / 2013. Not sure if things have changed much since then.

**Comment by f2prateek** [comment]
Those changes sound reasonably correct to me. https://github.com/segmentio/analytics-ios/pull/589/files is example of prior art in this field (though outdated as the architecture has changed significantly).

**Comment by mcmurrym** [comment]
I just remember that it also does not have the UIViewController support that is in the iOS and tvOS version

**Comment by adamsinger** [comment]
+1 For macOS support. Would really love to integrate this when it is supported officially.

**Comment by f2prateek** [comment]
Tracking internally in JIRA as well — https://segment.atlassian.net/browse/LIB-134

**Comment by linusnyberg** [comment]
Any updates on this yet?

**Comment by tonyxiao** [comment]
@linusnyberg there's only community fork for the time being for macOS. Have you given those a try?

**Comment by linusnyberg** [comment]
@tonyxiao Thanks! But I'm afraid to use an unmaintained version of the SDK. The fork is already 58 commits behind. I'm considering rolling my own wrapper around the HTTP API just because the lack of SDK support. Needless to say, official Segment support for macOS would be a lot better.

**Comment by bsneed** [comment]
This has been done and released in 4.0.4.
