### ISSUE TITLE
Log campagin events

### ISSUE THREAD

**Issue by eJamesLin** [segmentio/analytics-ios#591]
Android sdk has the following syntax to log the google analytics campaign,
`GetAnalyticsContext().putCampaign`
such as `https://apple.com/?utm_medium=push&utm_source=app&utm_campaign=test&utm_content=test`

is this supported in iOS sdk?
thank you

**Comment by f2prateek** [comment]
You'll have to pass it in each of the events you track ->

[analytics track:@"Order Completed" properties:@{} options:@{
  @"context": @{
    @"campaign": @{ @"meidum": medium .. }
  }
}];

**Comment by eJamesLin** [comment]
@f2prateek we did the above suggestion, and do see the data appears at segment debugger page, but the campaign still not send to google analytics...

**Comment by f2prateek** [comment]
@eJamesLin can you ping friends@segment.com with your question and include whether you're using the server side integration or client side integration in the email? Most likely a bug with https://github.com/segment-integrations/integration-google-analytics or https://github.com/segment-integrations/analytics-ios-integration-google-analytics

**Comment by herbert1119** [comment]
I have the exactly same issue, but it also doesn't send to Mixpanel either.
