### ISSUE TITLE
Improved Swift Support

### ISSUE THREAD

**Issue by edowling** [segmentio/analytics-ios#605]
When compiling a Swift 2.3 app against iOS 10, `SEGAnalyticsConfiguration(writeKey: key)` triggers the following error when `-whole-module-optimization` is enabled: 

```
(writeKey: String!) -> SEGAnalyticsConfiguration' is not convertible to '(writeKey: String!) -> SEGAnalyticsConfiguration!
```

This goes away when either switching to Single-File optimisation or by declaring `+ (instancetype)configurationWithWriteKey:(NSString *)writeKey;` as `nonnullable`.

Doing this raises a lot of warnings as the compiler wants to see nullable declarations for the whole interface. I have not tested it, but I assume this is also an issue on Swift 3.0.

**Comment by f2prateek** [comment]
thanks for the report, @tonyxiao is working on making the library nicer to use via Swift so this would be great for us to tackle as part of those changes.

**Comment by tonyxiao** [comment]
@edowling Making analytics-ios nice to use from Swift is pretty high up on my priority list. Will ensure it works well with xcode 8 / iOS 10 / Swift 3! https://github.com/segmentio/analytics-ios/projects/1

**Comment by gujinku** [comment]
Hi @tonyxiao ,  is there any Swift3 demo project now?

**Comment by tonyxiao** [comment]
@gujinku not yet, but it's on the top of my list up next.

**Comment by gujinku** [comment]
@tonyxiao , thank you for the prompt response!

**Comment by tonyxiao** [comment]
Unfortunately no, but I'll follow up here when I do.

**Comment by gujinku** [comment]
Pity. Thank you anyway.

**Comment by tonyxiao** [comment]
@gujinku @edowling We have a PR for improved swift support via lightweight generics & nullability indicator. Should make it into the next beta release this week. 

https://github.com/segmentio/analytics-ios/pull/647

**Comment by gujinku** [comment]
Thanks a lot! @tonyxiao

**Comment by tonyxiao** [comment]
@gujinku it has been released. Check version `3.6.0-beta`
