### ISSUE TITLE
Crash accessing "referrer" on liveContext after calling Segment's continueUserActivity()

### ISSUE THREAD

**Issue by andrewloyola** [segmentio/analytics-ios#616]
We've got some code that handles universal links (via branch), and we're seeing a consistent crash with Analytics 3.3.0 and later releases. This is on iOS 10, both beta and public versions.

We receive the AppDelegate `continueUserActivity` call when handling a universal link. Inside the delegate call after calling `SEGAnalytics.sharedAnalytics().continueUserActivity()` which saves the referring URL, the next track call crashes in SEGSegmentIntegration.m when trying to set `context[@"referrer"] ` when accessing `liveContext`.  Commenting out the `SEGAnalytics.sharedAnalytics().continueUserActivity()` call makes the crashes stop.

So far seems to be an issue with setting the referrer dictionary with activity.webpageURL from the NSUserActivity object.  When this is accessed later, it is nonnull but it is also not a Dictionary when looking at the debugger. 

Curious to see if anyone else is seeing this behavior?  It doesnt seem to be related to the URL itself; at least i've tried substituted a new NSUserActivity with a known good url to test that part out.

**Comment by f2prateek** [comment]
Can you share the stacktrace?

**Comment by f2prateek** [comment]
Also a reproducible test case would be great!

**Comment by f2prateek** [comment]
@andrewloyola from a quick guess, it looks like [`activity.WebpageURL` might be nil](https://github.com/segmentio/analytics-ios/blob/5cad6f5dadb0f1304a12248e15ced20335204f8b/Analytics/Classes/Internal/SEGSegmentIntegration.m#L385).

I'm not entirely sure why it would be `nil`. We [check if the activityType is `NSUserActivityTypeBrowsingWeb`](https://github.com/segmentio/analytics-ios/blob/5cad6f5dadb0f1304a12248e15ced20335204f8b/Analytics/Classes/Internal/SEGSegmentIntegration.m#L383), which according to [docs](https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/Handoff/AdoptingHandoff/AdoptingHandoff.html) should contain the  `webpageURL` property.

**Comment by andrewloyola** [comment]
sure, attaching a screenshot at least of the stacktrace while I figure out how to print the equivalent.
![crash](https://cloud.githubusercontent.com/assets/1688758/19288712/567d46de-8fd5-11e6-99f6-a0cd887e87f8.png)

**Comment by andrewloyola** [comment]
@f2prateek I dont think it's nil when it writes the webpageURL, otherwise it would probably crash at write time in `SEGAnalytics.sharedAnalytics().continueUserActivity()` since you shouldnt be able to insert nil into an NSDictionary.  It is a swift optional though.

**Comment by andrewloyola** [comment]
I'll try to get a sample project going as well.

**Comment by andrewloyola** [comment]
actually, the easiest way @f2prateek is to just call `Segment.continueUserActivity()` from anywhere and then do a track call.

I put the below in our initial ViewControllerCode, and it will crash during the track call: 

 ```
    override func viewDidAppear(animated: Bool)
    {
        super.viewDidAppear(animated)
        
        var userActivity = NSUserActivity(activityType: NSUserActivityTypeBrowsingWeb)
        userActivity.webpageURL = NSURL(string: "http://www.segment.com")
        SEGAnalytics.sharedAnalytics().continueUserActivity(userActivity)
        SEGAnalytics.sharedAnalytics().track("test")
    }
```

**Comment by f2prateek** [comment]
@andrewloyola gotcha, I was able to reproduce. I *think* we have a potential fix and test case  here, do you mind trying it out as well?

https://github.com/segmentio/analytics-ios/tree/copy-referrer 

`pod 'Analytics', :git => 'https://github.com/segmentio/analytics-ios.git', :branch => ' copy-referrer'`

**Comment by andrewloyola** [comment]
confirmed, that branch doesn't crash with my similar test case @f2prateek
