### ISSUE TITLE
Wrong version in 3.5.2?

### ISSUE THREAD

**Issue by grioja** [segmentio/analytics-ios#624]
https://github.com/segmentio/analytics-ios/blob/master/Analytics/Classes/SEGAnalytics.m#L584

Hard-coded to 3.5.1 ? Will this affect anything? Noticed this in our pod diff

**Comment by f2prateek** [comment]
Ah thanks - this won't have any impact on the data quality but we'll have it fixed in the next release.

**Comment by f2prateek** [comment]
Fixed by https://github.com/segmentio/analytics-ios/pull/626
