### ISSUE TITLE
tvOS support througth carthage 

### ISSUE THREAD

**Issue by BProg** [segmentio/analytics-ios#625]
building using `carthage update analytics-ios --platform tvOS`
gives error: `Dependency "analytics-ios" has no shared framework schemes for any of the platforms: tvOS`

If use binary tagged at 3.5.2 which is built for iOS, xcode gives me error : 
`URGENT: building for tvOS simulator, but linking against dylib (/Users/admin/Workspace/tvOSApp/Analytics.framework/Analytics) built for iOS. Note: This will be an error in the future.`

**Comment by f2prateek** [comment]
tvOS is supported via CocoaPods, but support via Carthage isn't on our immediate roadmap. Happy to accept PRs that add support in the meantime though!
