### ISSUE TITLE
Leak observed when setupWithConfiguration

### ISSUE THREAD

**Issue by ionutivan** [segmentio/analytics-ios#648]
Steps to replicate:
* add below code to AppDelegate:
`      
let configuration = SEGAnalyticsConfiguration(writeKey: ***)        
        SEGAnalytics.setupWithConfiguration(configuration)`
* profile the app and the leak happens in 
`-[SEGHTTPClient settingsForWriteKey:completionHandler:]`

**Comment by tonyxiao** [comment]
@ionutivan I took a quick look and not sure what you are referring to. What do you mean by leak? Which object is retained when you expect it to be released?

**Comment by ionutivan** [comment]
I used Instruments to profile my app and I noticed there is a leak here. So I don't know exactly why it is happening, I just saw it is happening. @tonyxiao

**Comment by tonyxiao** [comment]
Typically a leak means that memory usage keeps going up but does not come down. Over time the app gets killed by the OS for too much memory usage. However this is a one-off request so that's why I'm not sure what you mean by leak here. Could you attach a screenshot of the instrument view that shows the leak you're referring to? @ionutivan

**Comment by ionutivan** [comment]
<img width="1396" alt="screen shot 2016-11-29 at 6 07 04 pm" src="https://cloud.githubusercontent.com/assets/1093056/20722592/18a09dec-b65f-11e6-94e0-56adc2bd7120.png">
@tonyxiao

**Comment by ionutivan** [comment]
Is there anything more I can do to help with this issue @tonyxiao ?

**Comment by marsepu** [comment]
I posted a new PR because I found the same problem. https://github.com/segmentio/analytics-ios/pull/652

**Comment by marsepu** [comment]
@tonyxiao && @ionutivan ^^

**Comment by tonyxiao** [comment]
@ionutivan @marsepu thank you. Let's centralize the discussion in #652 .
