### ISSUE TITLE
Can't use SEGAnalytics.shared() in Swift

### ISSUE THREAD

**Issue by cshah3** [segmentio/analytics-ios#653]
I am initializing SEGAnalytics with a SEGAnalyticsConfiguration in AppDelegate but can't access SEGAnalytics.shared() anywhere in the app (even right after initializing in AppDelegate). For example:

`let _ = SEGAnalytics(configuration: SEGAnalyticsConfiguration(writeKey: "writeKey"))`
`SEGAnalytics.shared().identify("userId")`

 Here are the error logs:

*** Assertion failure in +[SEGAnalytics sharedAnalytics](), /Users/cshah/Documents/room8/room8-ios/Pods/Analytics/Analytics/Classes/SEGAnalytics.m:575
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'library must be initialized before calling this method.'

**Comment by f2prateek** [comment]
You'll need to call the `setupWithConfiguration` (not the `initWithConfiguration` method) method to set the default instance https://github.com/segmentio/analytics-ios/blob/master/Analytics/Classes/SEGAnalytics.h#L34.

**Comment by f2prateek** [comment]
Sorry accidentally closed, but feel free to close once your issue is resolved.

**Comment by cshah3** [comment]
Thanks!

**Comment by xploit42** [comment]
It's maybe a good idea to deprecate this init 😀
