### ISSUE TITLE
Screen tracking doesn't always produce desired name for UITabBarController and UISplitViewController

### ISSUE THREAD

**Issue by markst** [segmentio/analytics-ios#654]
It seems that the output of `seg_topViewController` doesn't always pick the right view top view controller especially for instances when we have nested child view controllers.

Is this particular case we have our navigation controller nested within a `RootViewController` which results in all our screen tracking events being called: "Root"

Happy to either PR to produce better results, or perhaps inclined to not use provided `recordScreenViews` view controller swizzler. 

Thanks.

**Comment by f2prateek** [comment]
Happy to accept a PR to improve the behavior. We want automatic screen tracking wherever possible, but it definitely comes with the understanding that it might not work for every view configuration, in which case manually making screen calls is always an option.

**Comment by f2prateek** [comment]
Tracking internally in JIRA — https://segment.atlassian.net/browse/LIB-132

**Comment by bsneed** [comment]
This has been resolved in #884
