### ISSUE TITLE
Calling reset method cancels previous track event request.

### ISSUE THREAD

**Issue by aleksandergrzyb** [segmentio/analytics-ios#670]
**What's the problem:**

Tracking some event just before calling `reset` method cancels the request resulting in with no event being tracked:

**Detailed description:**

In [this line](https://github.com/segmentio/analytics-ios/blob/master/Analytics/Classes/Internal/SEGSegmentIntegration.m#L515) there is a cancellation of `self.batchRequest`. If the request is under progress the tracking event is never send into Segments. 

```swift
SEGAnalytics.shared().track(...) // Never tracked
SEGAnalytics.shared().reset() // Cancels previous tracking event
```

**How to reproduce:**

1. Turn on debugging via `SEGAnalytics.debug(true)`.
2. Track some event and on the next line call immediately `reset()` method.
3. Logs show that track event was cancelled.

**How to fix?**

To get around the issue we are using `dispatch_after` where we call `reset`. Do you have any other ideas how it could be resolved? Is it necessary to cancel the request inside of `reset`?

**Comment by tonyxiao** [comment]
@f2prateek what do you think is the right behavior here? Also what happens on analytics-android?

**Comment by tonyxiao** [comment]
Related issue https://github.com/segmentio/analytics-ios/issues/681

**Comment by f2prateek** [comment]
Reset is meant for the user logging out case, so I think the behavior should be to keep the existing events and flush them later. On Android we don't clear the queue.

**Comment by aleksandergrzyb** [comment]
Currently in production we have `flushAt` property set to `5`. When user logs out we just want to clear all user information, but we want to send previously generated events by this user. Right now we maintain [a fork](https://github.com/aleksandergrzyb/analytics-ios/commit/ae958edefc972f6510ea081976f5e24743d40433) where we implemented that for ourselves.

If you agree with it I am happy to create PR to official repository.

**Comment by tonyxiao** [comment]
I like what you have in the fork. Can you create a PR based on it? Thanks you @aleksandergrzyb

**Comment by aleksandergrzyb** [comment]
Yes, will do tomorrow. 👍

**Comment by aleksandergrzyb** [comment]
Created PR #690.
