### ISSUE TITLE
Bug: SegAnalytics.shared.identify()

### ISSUE THREAD

**Issue by chrisdhaan** [segmentio/analytics-ios#673]
#647 introduced a bug where ```nil``` could no longer be passed into any of the `SegAnalytics.shared.identify(...)` methods in Swift. Previously, userId was allowed to have a value of ```nil```. This is no longer the case as it does not include the ```_Nullable``` clause. I'm currently opening a PR with this fix. If this update was intentional and ```nil``` is no longer able to be passed as a userId value then the comments should be updated to reflect that update.

**Comment by f2prateek** [comment]
Closed by #674

**Comment by davidmarble** [comment]
Just realized this bugfix is exactly what we need for a Swift project we're working on. Will a new release be happening soon or should we manually compile dev branch for now?

**Comment by f2prateek** [comment]
@tonyxiao would know the answer to that!

**Comment by tonyxiao** [comment]
@davidmarble expect a new release within the next day.

**Comment by tonyxiao** [comment]
@davidmarble 3.6.1 has just been released.

**Comment by davidmarble** [comment]
Thanks @tonyxiao !
