### ISSUE TITLE
Application Updated is broken again

### ISSUE THREAD

**Issue by FiRiN59** [segmentio/analytics-ios#678]
Application Updated event is being sent each time I open the app. This was introduced in 3.5.6 then fixed in 3.5.7 and now it's back again in 3.6.0

From Segment Debugger:
```objective-c
[[SEGAnalytics sharedAnalytics] track:@"Application Updated", properties: @{
    @"build" : @"1125ee6-feature/appboy",
    @"previous_build" : @"1125ee6-feature/appboy",
    @"previous_version" : @"4.3.3",
    @"version" : @"4.3.3"
}];
```

**Comment by tonyxiao** [comment]
Looks like https://github.com/segmentio/analytics-ios/blob/3.5.7/Analytics/Classes/SEGAnalytics.m#L197 got missed in the merge :(. 

Fixing here - https://github.com/segmentio/analytics-ios/pull/685
