### ISSUE TITLE
Flush not sending already queued messages on server

### ISSUE THREAD

**Issue by msalmanST** [segmentio/analytics-ios#681]
Hi,

I was testing the application and in my case I am doing the following steps.

1. Perform login (internally I identify the logged in user)
> SEGAnalytics.shared().identify("user_id")
> SEGAnalytics.shared().track("logged in")
2. Perform logout, (internally first I call flush method so that all the queued messages are passed to the server and after than calling reset.)

> SEGAnalytics.shared().track("logged out")
> SEGAnalytics.shared().flush() // I expect that all the queued messages will be send to server before reset.
> SEGAnalytics.shared().reset() // will reset user identity

3. Again identify the anonymous user.
> SEGAnalytics.shared().identify("anonymous_user_id") // identifying anonymous user

If I perform this quickly i.e in 5, 6 seconds then on segment debugger I am only seeing the last identify call "3" i.e identify to the anonymous user only, and all the events in "1" and "2" are not passed to the segment.

I am not seeing flush to be working here.
segment version = 3.5.2.

**Comment by f2prateek** [comment]
Yep the issue here is that reset cancels in-flight messages. Dupicate of https://github.com/segmentio/analytics-ios/issues/670
