### ISSUE TITLE
Build instructions when not using CocoaPods or Carthage.

### ISSUE THREAD

**Issue by scalessec** [segmentio/analytics-ios#688]
One of our older projects isn't using CocoaPods or Carthage and it would be helpful to have build instructions and/or a pre-compiled lib available.

**Comment by thefaj** [comment]
I requested this over a year ago — no response from Segment.

**Comment by f2prateek** [comment]
There's an example of how to integrate the library as a framework manually https://github.com/segmentio/analytics-ios/tree/dev/Examples/ManualExample.

@tonyxiao are there any instructions we have for this as well?

There are no plans to add a static library however. (fi that's what you were looking for).

**Comment by scalessec** [comment]
@f2prateek @tonyxiao is there no way to do this without nesting the project? Seems a little excessive. The way I currently have it setup, the library works on device, but when running on the simulator I have preprocessor macros and a script that unlinks the framework -- but that also seems incredible excessive just to fire off a few events to Segment. Is there really no alternative?

**Comment by tonyxiao** [comment]
@scalessec you can totally just build the framework target using `Analytics.xcworkspace`. Then grab the `.framework` bundle and use it however you please without nesting project.

**Comment by scalessec** [comment]
@tonyxiao apologies if I'm missing something obvious, but when I follow these steps:

1. Checkout the `3.6.1` tag and open `Analytics.xcworkspace`
2. Confirm `Build Active Architecture Only` is `No` for the `Release` configuration.
3. Edit the `Analytics` scheme such that `Run` uses the `Release` build configuration.
4. Select `Generic iOS Device` and build.
5. Link my project with the resulting `.framework`

... my project will then only compile when making device builds. When I try to build for the simulator, I get:

```
: "_OBJC_CLASS_$_SEGAnalytics", referenced from:
: Objc-class-ref in MyClass.o
: "_OBJC_CLASS_$_SEGAnalyticsConfiguration", referenced from:
: Objc-class-ref in MyClass.o
: Symbol(s) not found for architecture x86_64
: Linker command failed with exit code 1 (use -v to see invocation)
```

How do I get your framework to work for both device and simulator? Not sure what I'm missing and/or doing wrong.

**Comment by scalessec** [comment]
Looks like I have to manually use `lipo`. Would be great to have this documented and/or have a universal framework script that does this. For now I think I'll just stick to using preprocessor macros to remove Segment code from simulator builds.

**Comment by tonyxiao** [comment]
Got it. Glad you were able to work it out. I'll see what I can do to create a static library build for those who do not / cannot use cocoapods / Carthage / framework target. I have some appreciation for the frustrating dependency management battle you must be fighting through when legacy constraints prevent you from using package manager.

**Comment by tonyxiao** [comment]
Closing for now, reopen if needed.

**Comment by AmitPandya007** [comment]
> There's an example of how to integrate the library as a framework manually https://github.com/segmentio/analytics-ios/tree/dev/Examples/ManualExample.
> 
> @tonyxiao are there any written instructions we have for this as well?
> 
> There are no plans to add a static library however. (fi that's what you were looking for).

This page is not available, will you please provide some different solution please.
