### ISSUE TITLE
"Application Installed" event tracked but not actually sent to Segment

### ISSUE THREAD

**Issue by neoplastic** [segmentio/analytics-ios#689]
I've been trying to track Application Installed using 3.6.0 and it doesn't show up in segment. I've had segment installed for about half a year now and 0 events for Installed, very few Application Opened and Updated.

Other events come through like page views and some of my custom events but any event that happens close to Segment's config initialisation is ignored.

**Comment by ladanazita** [comment]
Hi @neoplastic ! 

Could you send in details of your implementation to https://segment.com/contact with [logging enabled](https://segment.com/docs/sources/mobile/ios/#logging)? Some other helpful details that will help the team debug this would be an example of the event you are triggering with the corresponding log output, the source you are sending data to, and any information about your implementation that would be helpful (such as do you have lifecycle events enabled or are you triggering those events on your own?).

From there we can surface if this is an issue in the core library and go from there!
