### ISSUE TITLE
Improper use of NSURLSession creation.

### ISSUE THREAD

**Issue by thefaj** [segmentio/analytics-ios#692]
SEGHTTPClient.m improperly generates a new NSURLSession each time data is uploaded to Segment's API. Apple's recommendation on this since iOS 7 has been to generate your NSURLTasks on a limited number of reusable NSURLSessions.

Segment's current implementation causes memory leaks when measured in Instruments.

**Comment by f2prateek** [comment]
This seems reasonable. Our assumption was that most apps don't upload data more than once or twice per session — so it's not the end of the world if we create 1-2 new sessions. But does make sense people might have lower thresholds in production too, so we should guard it. cc @tonyxiao

**Comment by jdmaresco** [comment]
We're seeing memory leaks – and many crashes on older devices. We've isolated the issue to our iOS app, and the Segment SDK. It seems that a new NSURLSession is created for every event request, and then never closed. Many users stay in our app for 2-3 minutes and fire 20-30 events. 

Is there a priority fix going in for this?

**Comment by f2prateek** [comment]
Are you using a low batch/flush size or interval? That might explain why many sessions are being created, though not why there aren't being closed (we do this here https://github.com/segmentio/analytics-ios/blob/dev/Analytics/Classes/Internal/SEGHTTPClient.m#L103). Additionally we only create a single session at a time.

cc @tonyxiao on status of the fix.

**Comment by thefaj** [comment]
That's not correct @f2prateek. Your library creates a new session with every network request. This is incorrect usage of NSURLSession and causes leaks.

This plus the major security issues in the public sdk makes me question how you guard our users' extremely sensitive data inside your company. Segment.io is not safe for use.

**Comment by f2prateek** [comment]
I think you were confused by the statement "Additionally we only create a single session at a time." - what I meant to clarify there was we only make one network request at a time and hence create a single session at a time - I do agree we create multiple sessions (one per request) sequentially.

**Comment by jdmaresco** [comment]
@f2prateek Yes we have batch size to the minimum as we want it to be fairly real-time. I don't believe this should be an issue at all if NSURLSessions are used (and closed) correctly.

**Comment by jdmaresco** [comment]
@f2prateek Do you have an update on this?

**Comment by f2prateek** [comment]
@jdmaresco, @tonyxiao will let you know

**Comment by tonyxiao** [comment]
https://github.com/segmentio/analytics-ios/pull/699 @jdmaresco @f2prateek

**Comment by f2prateek** [comment]
Closed by #699

**Comment by jdmaresco** [comment]
@tonyxiao @f2prateek Is the dev branch stable? Should we be waiting for another official release?

**Comment by tonyxiao** [comment]
@jdmaresco We will be releasing a new version today with changes from dev.

**Comment by tonyxiao** [comment]
https://github.com/segmentio/analytics-ios/releases/tag/3.6.2 released
