### ISSUE TITLE
SEGClientHTTP fails to support background transfer

### ISSUE THREAD

**Issue by thefaj** [segmentio/analytics-ios#694]
NSURLSession supports background transfer, but Segment's library doesn't support it. Upload tasks work when started from a file — the current SEGClientHTTP class incorrectly loads the plist file into memory (and gzips it).

Per Apple Docs — "Only upload tasks from a file are supported (uploading from data objects or a stream will fail after the program exits)."
https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/URLLoadingSystem/Articles/UsingNSURLSession.html#//apple_ref/doc/uid/TP40013509-SW26

**Comment by f2prateek** [comment]
Tracking internally in JIRA as well — https://segment.atlassian.net/browse/LIB-129

**Comment by tonyxiao** [comment]
Currently by design SEGHTTPClient does not make use of background transfer because we don't officially support it yet. So it seems like an enhancement rather than a bug. @f2prateek can you confirm?

@thefaj Do you have a specific usecase involving it?

**Comment by thefaj** [comment]
@tonyxiao This is a bug—don’t try to cover it up. Segment doesn’t understand security or networking on iOS. I have no “usecase” because I recommend clients avoid using Segment.io at all.

**Comment by tonyxiao** [comment]
@thefaj background transfer is an optional API in iOS that implementers may choose to use if deemed appropriate. 

I've sorry you've been frustrated with our process. I would appreciate your sharing other concerns you have around security or networking on iOS with Segment library if you are willing to share.
