### ISSUE TITLE
Track event properties inconsistencies

### ISSUE THREAD

**Issue by markst** [segmentio/analytics-ios#695]
Analytics track event expects properties as `[String : Any]`:

```swift
func track(_ event: String, properties: [String : Any]?)
```

However an assertion is raised if properties are not NS objects:
```objc
AssertDictionaryTypes()
```

**Comment by f2prateek** [comment]
cc @tonyxiao

**Comment by f2prateek** [comment]
tracking internally in JIRA as well — https://github.com/segmentio/analytics-ios/issues/695

**Comment by bsneed** [comment]
This seems to have been fixed.
