### ISSUE TITLE
Crashes on new 3.6.2 version

### ISSUE THREAD

**Issue by Ataraxiis** [segmentio/analytics-ios#701]
Hi all,

Since I've updated to the new `3.6.2` version, I have some (random ?) crashes like that : 

```
Terminating app due to uncaught exception 'NSGenericException', reason: 'Task created in a session that has been invalidated'

*** First throw call stack:
(
	0   CoreFoundation                      0x0000000109a7bb0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000108dd7141 objc_exception_throw + 48
	2   CFNetwork                           0x000000010422597d -[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:] + 128
	3   CFNetwork                           0x00000001042d4ab3 -[__NSURLSessionLocal uploadTaskForRequest:uploadFile:bodyData:completion:] + 87
	4   Analytics                           0x0000000104089142 -[SEGHTTPClient upload:forWriteKey:completionHandler:] + 930
	5   Analytics                           0x0000000104099627 -[SEGSegmentIntegration sendData:] + 711
	6   Analytics                           0x0000000104098b1f __42-[SEGSegmentIntegration flushWithMaxSize:]_block_invoke + 687
	7   Analytics                           0x00000001040851a1 __seg_dispatch_specific_block_invoke + 49
	8   libdispatch.dylib                   0x000000010bc914a6 _dispatch_call_block_and_release + 12
	9   libdispatch.dylib                   0x000000010bcba05c _dispatch_client_callout + 8
	10  libdispatch.dylib                   0x000000010bc9894f _dispatch_queue_serial_drain + 221
	11  libdispatch.dylib                   0x000000010bc99669 _dispatch_queue_invoke + 1084
	12  libdispatch.dylib                   0x000000010bc99b32 _dispatch_queue_override_invoke + 654
	13  libdispatch.dylib                   0x000000010bc9bec4 _dispatch_root_queue_drain + 634
	14  libdispatch.dylib                   0x000000010bc9bbef _dispatch_worker_thread3 + 123
	15  libsystem_pthread.dylib             0x000000010c0515a2 _pthread_wqthread + 1299
	16  libsystem_pthread.dylib             0x000000010c05107d start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```
On the `3.6.1 `, no crash detected

**Comment by kszuba** [comment]
The same :/

`017-07-07 16:38:58.498 LiveNeighborlyDev[6495:1432388] Attempted to create a task in a session that has been invalidated
2017-07-07 16:38:58.502 LiveNeighborlyDev[6495:1432388] *** Terminating app due to uncaught exception 'NSGenericException', reason: 'Task created in a session that has been invalidated'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000107901b0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000107366141 objc_exception_throw + 48
	2   CFNetwork                           0x00000001094e697d -[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:] + 128
	3   CFNetwork                           0x0000000109595ab3 -[__NSURLSessionLocal uploadTaskForRequest:uploadFile:bodyData:completion:] + 87
	4   Analytics                           0x00000001046ad122 -[SEGHTTPClient upload:forWriteKey:completionHandler:] + 930
	5   Analytics                           0x00000001046bd607 -[SEGSegmentIntegration sendData:] + 711
	6   Analytics                           0x00000001046bcaff __42-[SEGSegmentIntegration flushWithMaxSize:]_block_invoke + 687
	7   Analytics                           0x00000001046a9181 __seg_dispatch_specific_block_invoke + 49
	8   libdispatch.dylib                   0x00000001091094a6 _dispatch_call_block_and_release + 12
	9   libdispatch.dylib                   0x000000010913205c _dispatch_client_callout + 8
	10  libdispatch.dylib                   0x000000010911094f _dispatch_queue_serial_drain + 221
	11  libdispatch.dylib                   0x0000000109111669 _dispatch_queue_invoke + 1084
	12  libdispatch.dylib                   0x0000000109111b32 _dispatch_queue_override_invoke + 654
	13  libdispatch.dylib                   0x0000000109113ec4 _dispatch_root_queue_drain + 634
	14  libdispatch.dylib                   0x0000000109113bef _dispatch_worker_thread3 + 123
	15  libsystem_pthread.dylib             0x00000001094c95a2 _pthread_wqthread + 1299
	16  libsystem_pthread.dylib             0x00000001094c907d start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException`

**Comment by tonyxiao** [comment]
@Ataraxiis @kszuba Really sorry about that here's the fix - https://github.com/segmentio/analytics-ios/pull/702

Turns out there were two separate PRs that introduced mutually incompatible changes and when reviewed individually it wasn't clear that the changes would end up leading to session being prematurely invalidated. Creating a new release now.

**Comment by Ataraxiis** [comment]
👍

**Comment by tonyxiao** [comment]
New release 3.6.3 is out which addresses this issue. Thank you for reporting!
https://github.com/segmentio/analytics-ios/releases/tag/3.6.3
