### ISSUE TITLE
Duplicate definition of category GZIP on interface NSData

### ISSUE THREAD

**Issue by n8tr** [segmentio/analytics-ios#703]
If you include both GZIP and segment Analytics pods, you get a duplicate category definition of ```NSData (GZIP)```.  The GZIP library should reserve the right to use the NSData (GZIP) category. Segment should rename their category to SEG_GZIP e.g.
```@interface NSData (SEG_GZIP)```

**Comment by f2prateek** [comment]
Seems reasonable. Happy to accept a PR!

**Comment by f2prateek** [comment]
Tracking internally in JIRA as well — https://segment.atlassian.net/browse/LIB-127

**Comment by f2prateek** [comment]
Closed by #749
