### ISSUE TITLE
Assertion failure in +[SEGAnalytics sharedAnalytics]()

### ISSUE THREAD

**Issue by zoufishanmehdi** [segmentio/analytics-ios#705]
Hi, I'm setting up Segment in my iOS app. After installing pod 'Analytics', '~> 3.0', I added the code below in App Delegate's `application:didFinishLaunchingWithOptions:` method. However, my app crashes with `Assertion failure in +[SEGAnalytics sharedAnalytics]()`. Any ideas?

```var configuration = SEGAnalyticsConfiguration(writeKey: "myWriteKey")
     SEGAnalytics.debug(true)
     configuration.trackApplicationLifecycleEvents = true
     configuration.recordScreenViews = true
     SEGAnalytics.shared().identify(currentUser.userId, traits: ["Full Name": currentUser.fullName(), "Email": currentUser.email, "Device ID": deviceID])
     SEGAnalytics.setup(with: configuration)

**Comment by tonyxiao** [comment]
@zoufishanmehdi what was the message of the assertion? Assertion typically means SDK isn't being instrumented correctly.

**Comment by f2prateek** [comment]
```
     SEGAnalytics.shared().identify(currentUser.userId, traits: ["Full Name": currentUser.fullName(), "Email": currentUser.email, "Device ID": deviceID])
     SEGAnalytics.setup(with: configuration)
```

the setup should be before the `identify`.

**Comment by kelvinlauKL** [comment]
@f2prateek I just encountered this error. I've identified some strange behaviors. Here's an example where this error occurs:

    let service: AnalyticsService = {
        let configuration = SEGAnalyticsConfiguration(writeKey: "<key here>")
        configuration.trackApplicationLifecycleEvents = true
        configuration.recordScreenViews = true
        return SEGAnalytics(configuration: configuration)
    }()

However, re-ordering these statements will work again:

    let service: AnalyticsService = {
        let configuration = SEGAnalyticsConfiguration(writeKey: "<key here>")
        let analytics = SEGAnalytics(configuration: configuration)
        configuration.trackApplicationLifecycleEvents = true
        configuration.recordScreenViews = true
        return analytics
    }()

Do you know why this is the case? Another surprising thing is that this behavior seems to change based on whether you use Carthage or Cocoapods. 

The assertion failure does not happen in Carthage, only Cocoapods.

**Comment by kelvinlauKL** [comment]
Further investigation suggests that `recordScreenViews` is the problem. Deleting that line seems to work fine.

**Comment by f2prateek** [comment]
hey @kelvinlauKL  - please write in to our support team (https://segment.com/contact/) and we can help. I would suggest clearly outlining the error you ran into (e.g. the stack trace) and your setup (e.g. using Swift + Xcode x.y.z. + Cocoapods a.b.c.) etc. so we can debug this quicker!
