### ISSUE TITLE
Improper use of -Warc-performSelector-leaks

### ISSUE THREAD

**Issue by casey-juul** [segmentio/analytics-ios#713]
In SEGAnalyticsConfiguration [line 61](https://github.com/segmentio/analytics-ios/blob/05baf83903b163d583bc46fae7d02dd283d5cfbd/Analytics/Classes/SEGAnalyticsConfiguration.m#L61):

The code is disabling the `performSelector leak` warning. This is bad practice and can lead to a leak. Instead, use the IMP invocations.

You can see the reasoning and code samples [here](https://stackoverflow.com/questions/7017281/performselector-may-cause-a-leak-because-its-selector-is-unknown).

**Comment by f2prateek** [comment]
Tracking internally in JIRA — https://segment.atlassian.net/browse/LIB-126

**Comment by bsneed** [comment]
Fixed in #884.
