### ISSUE TITLE
Reset without regenerating anonymousId

### ISSUE THREAD

**Issue by mihai8804858** [segmentio/analytics-ios#731]
Hi all,

I would like to have the functionality to reset any cached info without changing `anonymousId`. Is there any way I can do that or should I create a PR for this?

**Comment by f2prateek** [comment]
This isn't currently supported. Before sending a PR can you describe your use case?

**Comment by mihai8804858** [comment]
Currently, if user logs out we reset all it's persisted data, which generated a new `anonymousId`. We would like to keep `anonymousId` stable for the device and not change it, otherwise it's going to count extra users for this device.

**Comment by f2prateek** [comment]
I don't think this should be something we should add an API for. This should be a new user. Most tools will associate that logged in userId with that anonymousId. If you don't reset the ID, it will look like the same user in a lot of tools. You don't know if it's the same user or not until they login again.
