### ISSUE TITLE
Customizing every event before it's sent along to Segment

### ISSUE THREAD

**Issue by gabek** [segmentio/analytics-ios#737]
I have a scenario where I'm perfectly happy with the auto-generated navigation `screen` events that the SDK is generating, but I'd love to throw a few properties in those events before they get submitted to Segment.

Much of this is due to having a project that has a fair share of React Native screens but I don't want to add a second Segment SDK just for Javascript, and the "auto" `Screen` events are working just fine, but I need a few more values.

I know there's some middleware available, but I can't find much documentation for this.  Would that be the way to go?

**Comment by f2prateek** [comment]
hey @gabek! sorry about the lack of docs here, we're working on getting them ready but it's taken longer than expected. if you're adventurous, we have some docs in swift from when this was in beta that can still be used - 
[Public analytics-ios Middleware Docs.pdf](https://github.com/segmentio/analytics-ios/files/1529622/Public.analytics-ios.Middleware.Docs.pdf).

If you have any questions, do right into our support at https://segment.com/contact and someone from the team can help you out.

**Comment by gabek** [comment]
That seems to be exactly what I need, thanks!
