### ISSUE TITLE
[Carthage issue]: 3.6.9 binary is a pre-3.6.9 build

### ISSUE THREAD

**Issue by neilco** [segmentio/analytics-ios#738]
**Summary:** Using the binary framework associated with the [3.6.9 release](https://github.com/segmentio/analytics-ios/releases/tag/3.6.9) results in the following error when uploading apps to iTunes Connect:

> ERROR ITMS-90060: "This bundle is invalid. The value for key CFBundleShortVersionString '3.6.8-SNAPSHOT' in the Info.plist file must be a period-separated list of at most three non-negative integers."

**Additional Information:** On closer examination of the framework contained in the 3.6.9 [zip file](https://github.com/segmentio/analytics-ios/releases/download/3.6.9/Analytics.framework.zip), it looks like this is an older framework built on November 23 2017. The Info.plist in the framework in this zip file does indeed have a CFBundleShortVersionString of `3.6.8-SNAPSHOT` and not `3.6.9` as one would expect. 

**Workaround:** Use `carthage update analytics-ios --no-use-binaries` to build the framework from source.

**Comment by f2prateek** [comment]
Hmm... interesting - I just ran `git checkout 3.6.9 && make archive` - this produced a build with `CFBundleShortVersionString ` as `3.6.8-SNAPSHOT`.

**Comment by f2prateek** [comment]
So the issue was I wasn't running `make carthage` first. So it kept using the older version 🤦‍♂️ 

Updated now, and adding to the releasing steps to prevent in the future.

**Comment by neilco** [comment]
Your archive step in the Makefile should be:

```shell
archive: carthage
	carthage archive Analytics
```

**Comment by f2prateek** [comment]
Updated the 3.6.9 release and fixed the makefile to prevent this in the future.
