### ISSUE TITLE
dyld: symbol not found: _objc_class_$_mixpanel

### ISSUE THREAD

**Issue by bohachevskyy** [segmentio/analytics-ios#742]
Hello, I'm getting this error while launch app.

`dyld: symbol not found: _objc_class_$_mixpanel`

I've added segment-mixpanel with pod:

`pod ‘Segment-Mixpanel’`

My project is written with swift.
May you advice me something?

**Comment by f2prateek** [comment]
hey @bohachevskyy, I've moved the issue to our Mixpanel integration repo as that's where the error seems to be originating.

**Comment by f2prateek** [comment]
https://github.com/segment-integrations/analytics-android-integration-mixpanel/issues/21
