### ISSUE TITLE
Silent push notifications trigger Application Opened and Application Updated events

### ISSUE THREAD

**Issue by hackerjade** [segmentio/analytics-ios#745]
Sending a silent push notification (with a `content-available: 1` payload) to an app that runs in background mode triggers a launch sequence.  Segment SDK should interrogate the launch options payload for the content-available parameter in order to verify app launches are user initiated. 

see https://community.segment.com/t/k9ph7v

**Comment by f2prateek** [comment]
Seems reasonable! I don't have an immediate ETA here, but I've added this to our internal tracker (https://segment.atlassian.net/browse/LIB-208).

Apple Docs for this field: https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/PayloadKeyReference.html

```
Include this key with a value of 1 to configure a background update notification. When this key is present, the system wakes up your app in the background and delivers the notification to its app delegate. For information about configuring and handling background update notifications, see Configuring a Background Update Notification.
```

**Comment by hackerjade** [comment]
Awesome, thanks Prateek!

**Comment by f2prateek** [comment]
Just a quick update - this is still on our backlog, but we'd be happy to review a PR if someone is interested in taking a stab at this!
