### ISSUE TITLE
Allow static library usage from Cocoapods

### ISSUE THREAD

**Issue by bridger** [segmentio/analytics-ios#752]
Version [1.4.0 of Cocoapods](http://blog.cocoapods.org/CocoaPods-1.4.0/) allows a pod to be used as a static library, even in a Swift app. It requires the library's podspec to contain `s.static_framework = true`.

I believe this will help apps launch faster. Here's a blog post that explains why too many dynamic frameworks slows down launch: https://blog.automatic.com/how-we-cut-our-ios-apps-launch-time-in-half-with-this-one-cool-trick-7aca2011e2ea

**Comment by f2prateek** [comment]
Thanks for the report! I've triaged this internally (https://segment.atlassian.net/browse/LIB-234). I don't have an ETA, but we'll keep this on our radar for upcoming sprints. PRs welcome in the meantime though!

**Comment by krin-san** [comment]
It's a shame to see this issue lying around for already a year without any signs of work being done to solve it. [CocoaPods 1.5 release](http://blog.cocoapods.org/CocoaPods-1.5.0/) provides an easy solution for that issue. Both issue and solution are [well known to the community](https://github.com/ReactiveX/RxSwift/issues/1800#issuecomment-439187797).

Is there a reason not to include 1-line fix into the podspec file in 3.7.0 release?

For those who stumble upon the same issue and can't wait any longer, here a workaround:
1. For direct use in Podfile, just change the line like that:
```diff
- pod 'Analytics'
+ pod 'Analytics', :modular_headers => true
```
2. For inclusion in private library podspec:
- Download latest released `Analitycs.podspec` file
- Add this line inside:
```ruby
s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES' }
```
- Push modified podspec to your private Specs repo
- If library validation job runs on CI, ensure that `pod spec repo update` is executed to use your new shiny podspec
- In Podfile place your private Specs repo before the official one to ensure your podspec will be used

**Comment by bsneed** [comment]
I'll see if I can get this in with some other changes today.  Apologies for the time taken on this.  Our library wasn't quite in shape to be able to do this until very recently.  Supporting Cocoapods, Carthage, and SPM on multiple platforms was extremely difficult before.

**Comment by migs647** [comment]
We created a pull request: https://github.com/segmentio/analytics-ios/pull/968

Tested with Swift and Objective-C using `use_frameworks! :linkage => :static` and `use_modular_headers!` respectively.
