### ISSUE TITLE
Ability to set anonymousId removed in 3.6.0

### ISSUE THREAD

**Issue by jonah-williams** [segmentio/analytics-ios#753]
I stumbled across an unexpected change in behavior after upgrading across 3.6.0.

In https://github.com/segmentio/analytics-ios/compare/3.5.7...3.6.0#diff-90ee8062efa95f661137bf2685fd0256L271 we can see that `identify` started constructing a `SEGIdentifyPayload` with a nil `anonymousId` (and that remains true today in https://github.com/segmentio/analytics-ios/blob/master/Analytics/Classes/SEGAnalytics.m#L203) We used to be able to specify an anonymous id in the `options` argument.

https://github.com/segmentio/analytics-ios/blob/master/Analytics/Classes/Integrations/SEGIntegrationsManager.m#L155 appears to retain some of this behavior which checks `SEGIdentifyPayload.options` but that can now only ever contain `context` and `integrations` keys via https://github.com/segmentio/analytics-ios/blob/master/Analytics/Classes/Integrations/SEGIntegrationsManager.m#L526

I had found the option to specify an anonymous id useful because it allowed me to keep identifiers for crash logging and analytics in sync so I could correlate them as needed. In my case I can switch to allowing Segment to be the authority over my anonymous ids but maybe there should be some option to explicitly set this value, either via `identify` or otherwise?

**Comment by f2prateek** [comment]
Ah yep, this looks like a bug as part of the middleware changes. I think the fix should be to move that logic from `SEGIntegrationsManager` upto `SEGAnalytics.

**Comment by f2prateek** [comment]
I don't have an ETA, but I've triaged the issue internally in our JIRA https://segment.atlassian.net/browse/LIB-266
