### ISSUE TITLE
Forward enable/disable to bundled integrations

### ISSUE THREAD

**Issue by E-B-Smith** [segmentio/analytics-ios#755]
I maintain the Segment-Branch integration. 

I'm wondering if there's a something in the `SEGIntegration protocol` that is called to let the Branch SDK that the user has opted out of sending tracking info?  If so I'll add it to the next Segment-Branch integration update.

Thanks

**Comment by f2prateek** [comment]
@E-B-Smith unfortunately not really. Customers can call enable/disable for this, but we don't really surface this to the client side destinations. https://github.com/segmentio/analytics-ios/blob/master/Analytics/Classes/SEGAnalytics.m#L378-L386 

We could expose this property if you need.

**Comment by E-B-Smith** [comment]
That would be great.  The Branch SDK will still send open and close events unless we are told to stop.

Maybe add something like:
```
@protocol SEGIntegration <NSObject>
.
.
.
@optional
+ (void) setTrackingDisabled:(BOOL)disabled;
.
.
.
```

**Comment by f2prateek** [comment]
Yeah I think that's reasonable. For now, customers would have to manually call `[SEGAnalytics disable]` and `[BranchAnalytics disable]` (or whatever the equivalent in Branch is), but it would be nicer to handle it automatically.

**Comment by f2prateek** [comment]
I have triaged this internally as well https://segment.atlassian.net/browse/LIB-356

**Comment by alanjcharles** [comment]
@E-B-Smith This functionality is available in our new analytics-swift pilot. Please feel free to reach out to us there with any additional questions. 

https://github.com/segmentio/analytics-swift
