### ISSUE TITLE
Duplicated Screen events using recordScreenViews

### ISSUE THREAD

**Issue by gabek** [segmentio/analytics-ios#756]
I'm seeing an issue with analytics-ios 3.6.9 where each `screen` event gets automatically duplicated multiple times.  This event is being sent via `recordScreenViews` turned on, so there's no manual event being created and sent.

<img width="818" alt="screen shot 2018-05-10 at 3 27 02 pm" src="https://user-images.githubusercontent.com/414923/39897365-cdb2e928-5466-11e8-8f93-a59c1fda7a12.png">

I've used Segment for other projects and never ran into this, so I'm curious if this is anything that has been seen in the past and if there's anything that would resolve it.

**Comment by f2prateek** [comment]
hey @gabek - it depends quite a bit on your layout, and the screen tracking is mostly a "best effort" attempt. Whenever a new view controller appears on the screen, we basically try to detect the topmost view controller and trigger a screen call https://github.com/segmentio/analytics-ios/blob/7bd4299643e04c2821d974e8a22986b57cd7d25c/Analytics/Classes/Internal/UIViewController+SEGScreen.m#L60-L80.

It could be that you're using multiple view controllers - causing us to record multiple screen calls. In this case - you might have better mileage using manual screen tracking!

**Comment by gabek** [comment]
Thanks for the insight!
