### ISSUE TITLE
Random crash while usin Firebase

### ISSUE THREAD

**Issue by vaibhav-nickelfox** [segmentio/analytics-ios#757]
After successfully adding Firebase via pods, when running app, getting a crash.

<img width="1012" alt="screen shot 2018-05-11 at 6 38 31 pm" src="https://user-images.githubusercontent.com/23524831/39925819-c7774d62-554a-11e8-8a79-c717407ce224.png">

**Comment by f2prateek** [comment]
hey @vaibhav-nickelfox  - it looks like you're running into issues with Firebase. Could you open an issue in https://github.com/segment-integrations/analytics-ios-integration-firebase?
