### ISSUE TITLE
Can segment track screen automatically, and log screen name when sending event?

### ISSUE THREAD

**Issue by cqcn1991** [segmentio/analytics-ios#762]
I'm not very familiar with App analytics/tracking, so please forgive me if this is too basic.

From firebase, I notice it is possible to **automatically track screens**, as in https://firebase.google.com/docs/analytics/screenviews , but it seems not mentioned in Segment's docs.

Another thing I noticed, is in common field (https://segment.com/docs/spec/common/),  **page has `path`, while screen do not**. Screen only has `width` and `height`. So I want to know, when I log a event, do I need to manually log its screen name?

Thanks!

**Comment by humblehacker** [comment]
Might this be what you're looking for? [Automatic screen tracking](https://segment.com/docs/sources/mobile/ios/#automatic-screen-tracking)
