### ISSUE TITLE
Continue User Activity Not Called on Branch Integration

### ISSUE THREAD

**Issue by E-B-Smith** [segmentio/analytics-ios#764]
The Branch integration method `- (void)continueUserActivity:(NSUserActivity *)userActivity` isn't called when a the app receives a universal link, causing deep linking to fail.

**Comment by f2prateek** [comment]
This needs more detail. I'd recommend writing in via https://segment.com/contact and someone from our support team can help you debug whether this is an issue from the iOS library, the Branch integration or your configuration.

**Comment by E-B-Smith** [comment]
Here are the steps to reproduce:
1) Launch the app.
2) Put the app in the background. Click on deep link.
3) App opens, but continue activity isn't called in the Branch integration, so the deep link isn't opened.

If I add 
```swift
    @objc func application(
        _ application: UIApplication,
        continue userActivity: NSUserActivity,
        restorationHandler: @escaping ([Any]?) -> Void
    ) -> Bool {
        return Branch.getInstance().continue(userActivity)
    }
```

to my app, then the continueUserActivity payload is passed to Branch and the deep link is opened.

This used to work without adding the above lines to my app so I'm pretty sure something changed in the Segment SDK.

**Comment by f2prateek** [comment]
We don't intercept it automatically - the customer will need to invoke this method on the Segment SDK manually — https://github.com/segmentio/analytics-ios/blob/02ed37be4b749fd73e305585add8dba0c82d1c45/Analytics/Classes/SEGAnalytics.m#L334-L336.

Which version were you using before when this worked automatically?

**Comment by E-B-Smith** [comment]
Thanks.  I'll add this to the docs.

It could have been a really old version.  I don't know the full history of the integration.
