### ISSUE TITLE
Track Date() formatted with DateFormatter -> returns timeinterval

### ISSUE THREAD

**Issue by michzio** [segmentio/analytics-ios#769]
I experience odd behaviour I am tracking event using: 

```
let accountCreatedDateText = DateFormatter.iso8601Full(in: TimeZone.UTC).string(from: Date())
                        SEGAnalytics.shared().track("Account Created",
                                                    properties: [
                                                        "EmailAddress" : createdAccount.email ?? "<no email>",
                                                        "FirstName" : createdAccount.firstName,
                                                        "LastName" : createdAccount.lastName,
                                                        "DateTime" : accountCreatedDateText,
                            ])
```
![screen shot 2018-07-25 at 08 31 08](https://user-images.githubusercontent.com/10163187/43183363-22c50d1a-8fe5-11e8-8cf7-cecff72fa9d9.png)

But the problem is that Date that should be string UTC representation of date from Date() object is returned in segment as: 

```
[[SEGAnalytics sharedAnalytics] track:@"Account Created", properties: @{
    @"DateTime" : @[NSDate dateWithTimeIntervalSince1970:1532499957],
    @"EmailAddress" : @"michal+jul25segment@gmail.com",
    @"FirstName" : @"Mm",
    @"LastName" : @"Zz"
}];

```

**Comment by f2prateek** [comment]
>     @"DateTime" : @[NSDate dateWithTimeIntervalSince1970:1532499957],

Where are you seeing this? Are you seeing this in the pretty view in the Segment debugger? This is expected because date objects can be created in multiple ways, the pretty view in the debugger is our "best guess".

You can check the raw tab to see the raw JSON that was sent over the wire.
