### ISSUE TITLE
Segment tracking inconsistency

### ISSUE THREAD

**Issue by michzio** [segmentio/analytics-ios#770]
I don't know why but in debugger section of segment.com I cannot see all Track events I am sending from my app. This is very odd but sometimes one events are sent and sometimes they are not. 

Example: 
![screen shot 2018-07-25 at 08 34 43](https://user-images.githubusercontent.com/10163187/43183530-bb9833a0-8fe5-11e8-9a99-6af23b3140a6.png)
![screen shot 2018-07-25 at 08 34 52](https://user-images.githubusercontent.com/10163187/43183531-bbb473d0-8fe5-11e8-9811-689cbbe140b6.png)

I have such logs in Debugger but I am sending 2 events Identify and Track one after another. 
Like this: 

```
 #if SEGMENT_ANALYTICS
                        let identifyDateText = DateFormatter.iso8601Full(in: TimeZone.UTC).string(from: Date())
                        SEGAnalytics.shared().identify(createdAccount.id,
                                                       traits: [
                                                        "EmailAddress" : createdAccount.email ?? "<no email>",
                                                        "FirstName" : createdAccount.firstName,
                                                        "LastName" : createdAccount.lastName,
                                                        "DateTime" : identifyDateText,
                                                        ])
                        
                        let accountCreatedDateText = DateFormatter.iso8601Full(in: TimeZone.UTC).string(from: Date())
                        SEGAnalytics.shared().track("Account Created",
                                                    properties: [
                                                        "EmailAddress" : createdAccount.email ?? "<no email>",
                                                        "FirstName" : createdAccount.firstName,
                                                        "LastName" : createdAccount.lastName,
                                                        "DateTime" : accountCreatedDateText,
                            ])
                    #endif
```

But as you can see there are usually only Identify, other times there are only Account Created. 
And similar issue I have also in other screens and event cases I am sending. They should be sent and they doesn't appear in Debugger on segment.com

**Comment by f2prateek** [comment]
hey @michzio  - for support questions - could you write in to our support team via https://segment.com/contact? I think this maybe because of confusion with the batching behaviour of the library.
