### ISSUE TITLE
Timestamp cannot be configured

### ISSUE THREAD

**Issue by novemberborn** [segmentio/analytics-ios#780]
For a variety of reasons I have some screens and events that are registered with the SDK some time after they actually occur in the application. 

https://segment.com/docs/spec/common/#timestamps hints at the ability to provide a `timestamp`. It doesn't look like this value can be configured however, since it's hardcoded in the payload here: https://github.com/segmentio/analytics-ios/blob/7bd4299643e04c2821d974e8a22986b57cd7d25c/Analytics/Classes/Internal/SEGSegmentIntegration.m#L432

It's not altogether clear in the documentation whether `timestamp` (or `originalTimestamp`?) should be provided in `payload.options` or through `payload.timestamp`. I suspect it's the latter, in which case the SDK should have a means of configuring this value.

**Comment by f2prateek** [comment]
Timestamp is not meant to be configured from our client side libraries (analytics.js, analytics-ios and analytics-android). The use case for sending your own timestamp is for historical import (e.g. batch processing), which is not typically something you'd use the client side libraries for.

I'd be interested in hearing about your use case though as to why there's a delay between events occurring and before they get sent to the Segment SDK.

**Comment by novemberborn** [comment]
Ah, I can see that reasoning.

We have three use cases:

* We don't want to collect data until after we've communicated the privacy policy and terms of service, so we buffer it outside of the SDK
* We record certain screens asynchronously, after data has been loaded from the server, but if that takes too long and the user moves to another screen we still want to record the screen they were on
* We debounce event tracking for some UI interactions

For all of these we'd like to use original timestamp, not when we called the SDK.

**Comment by f2prateek** [comment]
I see. Unfortunately I don't think we have a way to do this currently, and it's not something we have heard many requests for for.  But I'll leave this open for now to give other users an opportunity to voice their use cases, so we can see if we can bump it in priority.

In the meantime, maybe it might be ok to live with a slight delay in timestamps, since it doesn't sound like in all 3 cases it would be more than a few seconds? The user's events should still be ordered correctly which is what's useful for thing like funnel analysis.

**Comment by soconnor-florio** [comment]
I second this.  I don't see why it's not allowed to provide a "segment-reserved timestamp key" and a iso8601 date format in the properties dictionary.  I have those exact same use cases.

"Provide good defaults, but allow for customization" is generally a great design principle.
