### ISSUE TITLE
WatchKit support?

### ISSUE THREAD

**Issue by kielgillard** [segmentio/analytics-ios#781]
I'd like to measure how my users are using our watchOS app. Any plans for supporting WatchKit?

If not, and say I was feeling generous, how much effort do you think this would be?

**Comment by f2prateek** [comment]
This is currently not supported. I would estimate this to be a decent amount of work - bigger than at least supporting tvOS (which was added in https://github.com/segmentio/analytics-ios/pull/572).

One thing you may be able to do to cut down some work is to send the messages from the watch to the phone, and continue to use this SDK on the phone for the heavy meat of the logic. This should reduce the complexity of the implementation quite a bit.

**Comment by joshuarcher** [comment]
Now with Apple support for independent WatchKit apps I think we should move this to a higher priority

**Comment by KelvinEC** [comment]
Any news about this issue? 
We pretend to use the service but watchOS support is really important to use.

**Comment by bsneed** [comment]
I don't expect this to happen anytime soon, however if it were to come in the form of a PR that would definitely speed things up.
