### ISSUE TITLE
Framework name and import

### ISSUE THREAD

**Issue by lordcodes** [segmentio/analytics-ios#782]
Currently, the Carthage framework and Swift import are very generic: Analytics.framework and import Analytics.

It would be better if these were more specific to Segment.

- Segment.framework or SegmentAnalytics.framework
and
- import Segment or import SegmentAnalytics

**Comment by f2prateek** [comment]
What issue does it cause if the name is left as Analytics?

I'm hesitant to change it as it would require a fair amount of work just for non-Cocoapods users (where we have the `Analytics` pod https://cocoapods.org//pods/Analytics)

**Comment by lordcodes** [comment]
It doesn't cause a huge issue, just feels pretty unclear to me when there is such a generic name. From checking the app that has been integrated its not clear that it is Segment analytics.

My "issue" was more of a question to see if it was simple / what issues there would be. Obviously if it is complicated or there is no other desire to change the name then I wouldn't recommend doing it.

I was just stating an opinion really. So if you would rather leave its name, then obviously feel free to close the issue.

**Comment by f2prateek** [comment]
I think renaming now would probably be more effort than the benefit it would provide. It's also nice to be consistent between platforms for us.
