### ISSUE TITLE
unrecognized selector sent to instance

### ISSUE THREAD

**Issue by chriswill0w** [segmentio/analytics-ios#786]
`[myapp.AppDelegate window]: unrecognized selector sent to instance 0x281998cc0`

my apps window is not located in the appdelegate and I do not want to expose it that way. The error is probably due to `@implementation UIViewController (SEGScreen)` Category trying to locate the rootViewController via
`[[SEGAnalytics sharedAnalytics] configuration].application.delegate.window.rootViewController`
Would it be possible to change "SEGAnalyticsConfiguration" to be configured with a custom rootViewController?
I would really like to use `segmentConfig.recordScreenViews = true`

**Comment by f2prateek** [comment]
This is not currently possible. I would recommend using manual screen tracking in your case for now.

@fathyb any suggestions on what we should do here?

**Comment by fathyb** [comment]
I think we can use [`application.keyWindow`](https://developer.apple.com/documentation/uikit/uiapplication/1622924-keywindow?language=objc) instead of `application.delegate.window` :

> This property holds the UIWindow object in the windows array that is most recently sent the makeKeyAndVisible message.

This should always hold the last `UIWindow` shown to the user so it should be safe to use with `screen`. @ltblueberry0 are you using complex window transitions or is just your window not defined in the delegate?

**Comment by ltblueberry0** [comment]
I do not think you are using `application.keyWindow`. You are using `[[SEGAnalytics sharedAnalytics] configuration].application.delegate.window.rootViewController`. No I do not use complex window transitions but my window does not live and is not exposed in the AppDelegate and it is also not an option. @fathyb @f2prateek

**Comment by fathyb** [comment]
@ltblueberry0 looks like a misunderstanding, I said "I think we **can** use".

Could you evaluate `[[SEGAnalytics sharedAnalytics] configuration].application.keyWindow.rootViewController` on one of your `viewDidAppear:` methods and confirm me it's the right `RootViewController`?

**Comment by ltblueberry0** [comment]
@fathyb my bad, I misunderstood.
I will look at it tomorrow and get back to you.

**Comment by ltblueberry0** [comment]
@fathyb initial tests show that `applicaiton.keyWindow.rootViewController` returns the correct viewController and should work for me.
Are you planning to change it?

**Comment by ltblueberry0** [comment]
@fathyb @f2prateek are there any plans of this bug being fixed?

**Comment by f2prateek** [comment]
Currently, no, as the changes suggested require more testing. We will post here and close this issue when the feature has been added.

 As I mentioned https://github.com/segmentio/analytics-ios/issues/786#issuecomment-424054437, you can use manual screen tracking as a workaround. You can find documentation for this at https://segment.com/docs/sources/mobile/ios/#screen.

**Comment by logananderson** [comment]
With `window` being moved out of AppDelegate and to the SceneDelegate in iOS 13, is there any plan to allow for supporting this?
