### ISSUE TITLE
WARNING: No data file for key segmentio.traits.plist

### ISSUE THREAD

**Issue by ltblueberry0** [segmentio/analytics-ios#787]
Integrated segment via carthage and setup according to docs. I am however seeing this error in the logs:
"WARNING: No data file for key segmentio.traits.plist"
Also only these "segmentConfig.trackApplicationLifecycleEvents = true" events are sent to the Source in Segment. My custom tracked events never make it.
I have already tried "flushAt = 1" to no avail.
Might this be due to also tracking events via Fabric's Answers?

**Comment by f2prateek** [comment]
I recommend reaching out to our support fo help with debugging questions https://segment.com/contact.
