### ISSUE TITLE
Fabric Answers not working together with Segment

### ISSUE THREAD

**Issue by ltblueberry0** [segmentio/analytics-ios#788]
If I use Segment together with fabrics's Answers custom event tracking via Segment does not work. Only events via Fabrics Anwers are tracked. It is interesting to note however that "trackApplicationLifecycleEvents" are tracked even if Segment and Answers run in parellel. Only my custom events cannot be tracked via Segment. If I turn off Answers then Segment works.
I integrated segment via Carthage and Fabrics's Answers via Cocoapods. How can I get Segment to work together with Fabric Answers?

**Comment by f2prateek** [comment]
I would recommend writing in to our support to help you debug this issue - https://segment.com/contact

**Comment by ltblueberry0** [comment]
@f2prateek well, is this not a bug related to the framework?
