### ISSUE TITLE
At what point is SEGAnalytics fully initialized

### ISSUE THREAD

**Issue by ltblueberry0** [segmentio/analytics-ios#789]
My first custom event is never tracked although I call it after setting up SEGAnalytics

```
let segmentConfig = SEGAnalyticsConfiguration(writeKey: key)
segmentConfig.trackApplicationLifecycleEvents = true
segmentConfig.flushAt = 5
SEGAnalytics.setup(with: segmentConfig)
SEGAnalytics.debug(true)

```

Do I have to wait for SEGAnalytics to be initialized before I can track the first event?

**Comment by f2prateek** [comment]
No the library should handle it for you. I woud recommend wirting in to our support to help debug the issue https://segment.com/contact.

**Comment by ltblueberry0** [comment]
It seems to be a bug with the framework. Should I not report bugs here? @f2prateek

**Comment by f2prateek** [comment]
I don't think this is a bug yet. I tested your code by dropping replace this section in the sample app (https://github.com/segmentio/analytics-ios/blob/master/Examples/CarthageExample/CarthageExample/AppDelegate.swift#L25-L27), and it works for me.

What I suspect here is you have not setup your application properly, and need help debugging. It may certainly be a bug, but right now the information shared is not enough to say so. Our success team can help you get debug this issue, and we can re-open this issue when a bug is confirmed.
