### ISSUE TITLE
What does not sending call mean?

### ISSUE THREAD

**Issue by ltblueberry0** [segmentio/analytics-ios#793]
What does this log output mean/indicate?

`Not sending call to Segment.io because it doesn't respond to applicationDidFinishLaunching:.`
`Not sending call to Segment.io because it doesn't respond to applicationDidBecomeActive.`

**Comment by f2prateek** [comment]
The analytics library automatically hooks into the application lifecycle and sends this to different integrations. It logs if an integration doesn't do anything with the message (https://github.com/segmentio/analytics-ios/blob/696b23d89fc3472863be2039f59c42bbb36f3e35/Analytics/Classes/Integrations/SEGIntegrationsManager.m#L444).

The Segment integration itself has no use for this lifecycle event, hence the logs.
