### ISSUE TITLE
Custom App Version

### ISSUE THREAD

**Issue by sdcoffey** [segmentio/analytics-ios#807]
Hey there!

I'm interested in being able to supply a custom app + build for segment events, instead of relying solely on information read from Info.plist. 

Let me describe the use case:

We're building a react-native app and using codepush to deploy js changes. When we deploy js changes, we need to be able to track version changes when the javascript bundle changes, but the _native version remains the same_.

What I'm proposing is adding two fields to `SEGAnalyticsConfiguration`:

```objc
/**
 * Version of the host app.
 */
@property (nonatomic, strong, nullable) NSString *appVersion;

/**
 * Build number of the host app.
 */
@property (nonatomic, strong, nullable) NSString *appBuild;
```

If present, segment will use these values in events such as `Application (Opened|Installed|Updated)`. If they're not present, we'll fall back to the values provided by the OS in `Info.plist`.

The alternative for us is to create forks of your android and iOS libraries, and we're not too keen on doing that. I'm happy to create PR to get the ball rolling. What do y'all think?

**Comment by TeresaNesteby** [comment]
hi @sdcoffey, thanks for reaching out! Please reach out to our team directly at https://segment.com/contact/.  We'd love to talk through your use case and possible next steps here.
