### ISSUE TITLE
[URL] mobile-service.segment.com/v1/attribution fail

### ISSUE THREAD

**Issue by alexis-letexier** [segmentio/analytics-ios#808]
Hello !

We have Analytics included in our app and it seems that the url `mobile-service.segment.com/v1/attribution`  called by your SDK is failing all the time (404 error)

Do you know what's happening ?

Thanks a lot

**Comment by TeresaNesteby** [comment]
hi @alexis-letexier, thanks for reaching out! Please reach out to our team directly at https://segment.com/contact/ - we'd be happy to look into it!

**Comment by seantimm** [comment]
We're seeing this as well.

**Comment by nery** [comment]
We're seeing this as well and would be good if all segment users could get a bit more context as to what the issue could be

**Comment by smn-snkl** [comment]
Same here.

**Comment by eeallen1** [comment]
Is there any update on this or what the implications are?

**Comment by twelve17** [comment]
Looks like the reference to this host was removed in the Analytics repo in version 4.1.0:

https://github.com/segmentio/analytics-ios/commits/4.1.0

Via this PR:

https://github.com/segmentio/analytics-ios/pull/941

Change:

https://github.com/segmentio/analytics-ios/pull/941/files#diff-b18d030a58b7b4151017b795dd6ae5cce891705a77871dae6026c68e2d061f30L11
