### ISSUE TITLE
Track offline events reliability

### ISSUE THREAD

**Issue by chuyeoh** [segmentio/analytics-ios#810]
Our app is commonly used in a low network environment and most events track is done when the device is offline.

We have noticed that there are times when an event was not successfully tracked.
Do you know what conditions the segment.io SDK would lose tracked events? 

We suspect that tracked events were lost when the app crashes before going online.
Can you confirm this behaviour?

**Comment by TeresaNesteby** [comment]
hi @chuyeoh! Thanks for reaching out! For support questions, please reach out to our team directly at https://segment.com/contact/.
