### ISSUE TITLE
Carthage build with --platform ios also builds tvOS

### ISSUE THREAD

**Issue by JetForMe** [segmentio/analytics-ios#814]
When I build this using `carthage update --platform ios`, is also builds the tvOS target. None of my other Carthage dependencies do this.

**Comment by bsneed** [comment]
Our Carthage support isn't the best.  I'll see if I can work this in in the near future.

**Comment by bsneed** [comment]
Closing this for now, larger changes afoot mean it won't be an issue soon enough.
