### ISSUE TITLE
Crash on Segment_Firebase

### ISSUE THREAD

**Issue by AdieOlami** [segmentio/analytics-ios#817]
The app crashes after adding 
`configuration.use(SEGFirebaseIntegrationFactory.instance())`

> 
Terminating app due to uncaught exception 'com.firebase.core', reason: 'Default app has already been configured.'

**Comment by f2prateek** [comment]
Hey @AdieOlami this doesn't seem like an issue with the core segment library, but on the Firebase side. I would suggest reaching out to our [support team](https://segment.com/contact/) so they can help you debug this.
