### ISSUE TITLE
How to check if library is initialized or not?

### ISSUE THREAD

**Issue by jayarajb1116** [segmentio/analytics-ios#818]

**Comment by f2prateek** [comment]
Generally it's recommended that the library be initialized during the application launch, so the rest of your app can assume it is initialized.

If you still need this, then you could try catching the error thrown around [`[SEGAnalytics sharedAnalytics]`](https://github.com/segmentio/analytics-ios/blob/c1583e39dada2e224194b876315c8d12b25d8f9b/Analytics/Classes/SEGAnalytics.m#L406-L410) to detect this. Or alternatively, you could set your own boolean variable to track then when you initialize the library. 

If you would like to see this more officially supported, I would suggest reaching out to our [support team](https://segment.com/contact/) to file a feature request and stay up to date on the progress
