### ISSUE TITLE
Library is not tracking Application Opened and Updated events when app launches on tvOS

### ISSUE THREAD

**Issue by mihai8804858** [segmentio/analytics-ios#821]
I'm using version 3.6.10 on an Apple TV device that runs tvOS 12.2 (Swift 5.0).
Some time ago I noticed that `Application Opened` and `Application Updated` events are not being tracked automatically.
I looked a bit in the code base and found that [this](https://github.com/segmentio/analytics-ios/blob/master/Analytics/Classes/SEGAnalytics.m#L104) method is not being called when app did finish launching, which is strange because I see that you're subscribing to `UIApplicationDidFinishLaunchingNotification` notification [here](https://github.com/segmentio/analytics-ios/blob/3be84b2a2af326a9ff502f53efeb5725e2aae142/Analytics/Classes/SEGAnalytics.m#L65).

**Comment by f2prateek** [comment]
hey @mihai8804858, sorry for the delay. We haven't seen this issue before, but I've added this to our [internal JIRA](https://segment.atlassian.net/browse/LIB-1170), I would suggest reaching out to our [support team](https://segment.com/contact/) so they can keep you updated with the progress.

**Comment by bsneed** [comment]
Please reopen if this is still occurring in the 3.8.x series.
