### ISSUE TITLE
Empty "integrations" object

### ISSUE THREAD

**Issue by mlazari** [segmentio/analytics-ios#823]
We have multiple bundled integrations in our iOS app like `Segment-Appboy`, `segment-appsflyer-ios`, `Segment-GoogleAnalytics`.

Usually when events are tracked they include a `integrations` object to indicate which integrations are bundled in app, so segment server don't send to those destinations:
```
"integrations": {
  "Appboy": false,
  "AppsFlyer": false,
  "Google Analytics": false
},
```

However, sometimes it sends an empty object for `integrations`:
`"integrations": {}`

This causes segment server to send itself those events to the destinations, but this is causing errors. For example AppsFlyer destination expects an AppsFlyer device id and segment server doesn't have it, causing errors to appear:
![Screen Shot 2019-06-03 at 5 59 59 PM](https://user-images.githubusercontent.com/4928274/58811952-78348600-8629-11e9-88c3-00e552ee7764.png)
Also happens for other destinations, see https://github.com/BranchMetrics/Segment-Branch-iOS/issues/15

We were able to reproduce for our app this way:
1. Uninstall the app;
2. Install the app;
3. Turn off internet connection;
4. Open the app;
5. Wait a little (not sure how long, 20-30 seconds should work) and turn on internet connection.
6. Navigate the app so it generate some events. Look at debugger of corresponding source on segment.com. See that all events have `"integrations": {}`.
7. Close and re-open the app. Navigate again to send some events. This time `"integrations"` is not empty (working as expected).

Is this a known issue? Can we do something to fix it? Thanks.

**Comment by bsneed** [comment]
This is because you're disabling the internet connection.  It can't get the configuration you want if the internet is off.
