### ISSUE TITLE
ETA for v3.7.0 release?

### ISSUE THREAD

**Issue by bharath2020** [segmentio/analytics-ios#828]
Hi There,
 v3.7.0 is in beta for a longer duration. Do you have an ETA when it will be released?

Thanks,
Bharath

**Comment by f2prateek** [comment]
We generally leave releases in beta a while, and track adoption with our internal metrics to decide when to promote them. I agree 3.7.0 has been in beta for a while, but am hoping we can make a stable release in the next months. In the meantime, please try the beta and report any bugs - the quickest way to speed it up is to use the beta releases!

**Comment by bharath2020** [comment]
Thanks, @f2prateek for the update. Using the beta release is out of option for us as we only use stable versions of our dependencies in our production applications so as to avoid any issues cropping up for our customers. Is there an expiration time for the beta version or is it just purely based on the metrics? Keen to know what is the average duration that the version stays on the beta?

**Comment by f2prateek** [comment]
It is primarily based on metrics. Internally we track the number of projects and number of events sent by these projects using any specific version of the library. Normally this takes a few months - unfortunately 3.7.0 has taken a bit longer because it's a big release with many patches.

**Comment by bpollman** [comment]
Think you can close this now that 3.7.0 is out 😄
