### ISSUE TITLE
Disabling default Basic Auth

### ISSUE THREAD

**Issue by kmunechika** [segmentio/analytics-ios#829]
When sending requests to Segment, our apps need to support sending them unauthenticated/with no authorization headers. We found that in [SEGHTTPClient](https://github.com/segmentio/analytics-ios/blob/c1583e39dada2e224194b876315c8d12b25d8f9b/Analytics/Classes/Internal/SEGHTTPClient.m), a basic authorization header is appended if we don't provide any auth headers. 

Is there any workaround this, or could we get a change to support disabling this behavior?

**Comment by f2prateek** [comment]
We use this for the API to know which project the data is associated with, so disabling it doesn't seem like a good idea.

If you would like to see this more officially supported, I would suggest reaching out to our [support team](https://segment.com/contact/) to file a feature request and stay up to date on the progress.
