### ISSUE TITLE
callIntegrationsWithSelector synchronously

### ISSUE THREAD

**Issue by wangjiejacques** [segmentio/analytics-ios#840]
```swift
- (void)callIntegrationsWithSelector:(SEL)selector arguments:(NSArray *)arguments options:(NSDictionary *)options sync:(BOOL)sync
{
    // TODO: Currently we ignore the `sync` argument and queue the event asynchronously.
    // For integrations that need events to be on the main thread, they'll have to do so
    // manually and hop back on to the main thread.
    // Eventually we should figure out a way to handle this in analytics-ios itself.
    seg_dispatch_specific_async(_serialQueue, ^{
        if (self.initialized) {
            [self flushMessageQueue];
            [self forwardSelector:selector arguments:arguments options:options];
        } else {
            [self queueSelector:selector arguments:arguments options:options];
        }
    });
}
```
this TODO says, For integrations that need events to be on the main thread, they'll have to do so manually and hop back on to the main thread, but I still don't know how to call this in the main thread, is there something wrong, or am I missing something?

And also, I don't understand what's the point to call this method *asynchronously*, it's just add an object in a queue, why don't we do this in the main thread?

**Comment by wangjiejacques** [comment]
my problem here is I want to track `app_kill` event.

actually, the code in the `SEGSegmentIntegration` is fine, it saves the unsend event when `applicationWillTerminate`.
```
- (void)applicationWillTerminate
{
    [self dispatchBackgroundAndWait:^{
        if (self.queue.count)
            [self persistQueue];
    }];
}
```
and it runs this code synchronously.
the `SEGIntegrationsManager` just need something like this, or maybe they can use the same `_serialQueue`...

**Comment by bsneed** [comment]
Closing this as I don't really understand what's being asked here.  Termination is an extremely brief and time-boxed process which can go sideways easily.  Please feel free to reopen if necessary.

**Comment by wangjiejacques** [comment]
Hi @bsneed, this TODO message **"manually and hop back on to the main thread."** is not clear to me, can you explain me more?
```
- (void)callIntegrationsWithSelector:(SEL)selector arguments:(NSArray *)arguments options:(NSDictionary *)options sync:(BOOL)sync {
    // TODO: Currently we ignore the `sync` argument and queue the event asynchronously.
    // For integrations that need events to be on the main thread, they'll have to do so
    // manually and hop back on to the main thread.
    // Eventually we should figure out a way to handle this in analytics-ios itself.
```
