### ISSUE TITLE
CoreTelephony is not part of tvOS -- getting link errors

### ISSUE THREAD

**Issue by skydivedan** [segmentio/analytics-ios#841]
CoreTelephony is not part of tvOS. 

Could you modify the podspec so that it doesn't include `CoreTelephony` for tvOS targets? Right now I'm getting linker errors.

**Comment by Zanchee** [comment]
Any update on when this will be released, we would like to update to 3.7 but can't. until this fix is released.

**Comment by bsneed** [comment]
It was released in 3.8.0-beta.1.  👍
