### ISSUE TITLE
Add ability to anonymize IP addresses in Lifecycle events

### ISSUE THREAD

**Issue by jain-ruchi** [segmentio/analytics-ios#843]
Hi there!

I successfully anonymized IP addresses in tracking, identify, and screen events, but noticed that it is still being collected in lifecycle events, e.g. Application Opened or Application Installed. I am hoping for a way to obscure IP addresses and other personal data in those events too.

Thanks!

**Comment by bsneed** [comment]
Hi @jain-ruchi the way to do this is to write a middleware.  

Documentation can be found here: https://segment.com/docs/connections/sources/catalog/libraries/mobile/ios/#middlewares

And example middleware can be found here:
https://github.com/segmentio/segment-braze-mobile-middleware/blob/master/iOS/Objective-C/SegmentBrazeDebounce-iOS/BrazeDebounceMiddleware.m
