### ISSUE TITLE
Can't run the TvOS version of this library in a simulator

### ISSUE THREAD

**Issue by mothaninja** [segmentio/analytics-ios#849]
# Steps to reproduce
- Build a tvOS app with this segment library.
- Run it on a tvOS simulator
- Crashes at initial load with the following error:

```
Reason: no suitable image found.  Did find: ...../Analytics.framework/Analytics: mach-o, but not built for tvOS simulator
Program ended with exit code: 9
```

# Environment

MacOS 10.14.6 (18G95)
Xcode 11.1
iOS 13 / TvOS 13

**Comment by bsneed** [comment]
If your configuration names aren't the standard "Debug" and "Release" it may not find it to build and defaulting back to iOS.  Also of note, if you're manually adding this library to your list of linked binaries, make sure you're selecting the tvOS one as each platform, the lib has the same name.

Also, I know you're not using cocoa pods, but for posterity's sake, one would need to set tvOS as the platform in the pod file.

I wasn't able to reproduce this, as a demo tvOS app does indeed run in the simulator
