### ISSUE TITLE
iOS Segment.io SDK does not allow `null` in Event's properties

### ISSUE THREAD

**Issue by abodnyaUA** [segmentio/analytics-ios#852]
We use the SDK to send analytics on Segment.io by calling
```[SEGAnalytics - (void)track:(NSString *)event properties:(SERIALIZABLE_DICT _Nullable)properties]``` method. This method uses `SEGCoerceJSONObject` method to serialize properties in JSON and during the serialization, it drops all the NSNull values.
Because of this we cannot send as a `properties` a dictionary with the value for key equals null, for example `{ "name": null }`

Android's implementation of Segment.io SDK **ALLOWS** sending null values.

In the comment of SEGCoerceJSONObject method it says that dropping NSNull is a HOTFIX
```// Hotfix for issue where SEGFileStorage uses plist which does NOT support NSNull```
This "HOTFIX" was added more than 2 years ago in the pr https://github.com/segmentio/analytics-ios/pull/707

Could you please provide normal fix for the issue and stop dropping NSNull values?
The iOS SDK is inconsistent with Android one and behave differently.

Thanks!

**Comment by abodnyaUA** [comment]
cc @tonyxiao @ladanazita @f2prateek @TeresaNesteby @myclamm

**Comment by bsneed** [comment]
Switched the underlying storage from plist to json.  Null's are now coming across correctly.  PR to be attached shortly.

**Comment by abodnyaUA** [comment]
@bsneed, wait for the pull-request. Thanks!

**Comment by bsneed** [comment]
Fixed, but leaving this open until we roll out another release soon.

**Comment by bsneed** [comment]
Released in 3.8.0-beta.1
