### ISSUE TITLE
Context screen height and width does not respond to rotation

### ISSUE THREAD

**Issue by smpeleato** [segmentio/analytics-ios#858]
In my testing I've found that the screen height and width information included in the context dictionary is not accurate if the device is rotated while the app is in the foreground. As far as I can tell height and width only update when the app is foregrounded and any subsequent changes are missed.

This makes the information unreliable for determining screen orientation.

**Comment by bsneed** [comment]
The information there is directly from UIScreen for simple display size reporting.  It's not intended to be used for the purpose you suggest.  You can either ...

A) track a new event providing the data you want.
B) write a middleware to append said data to events.

**Comment by smpeleato** [comment]
Right, I was planning on implementing both suggestions so I can get the information I need, but I'm still left with information in the event that I have to remember (and remind others) to ignore.

Any chance we can have a way to disable context screen then? If it's not going to be accurate then I'd prefer it not be included.
