### ISSUE TITLE
"Invalid type. Expected: integer, given: string" for Field `build` for event `Application Installed`

### ISSUE THREAD

**Issue by rnagella** [segmentio/analytics-ios#870]
For the `Application Installed` event, the Segment dashboard reports the `build` field as a violation.

<img width="787" alt="ApplicationInstalled-build_filed_voilation" src="https://user-images.githubusercontent.com/3255325/78201523-abf95b80-7446-11ea-8881-acfde48b7c13.png">
 
`Actual`: It should not consider as a violation because
1. CFBundleVersion should be a String according to [Apple documentation](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion)
2. Segment iOS SDK sends it as a String https://github.com/segmentio/analytics-ios/blob/master/Analytics/Classes/SEGAnalytics.m#L136

**Comment by bsneed** [comment]
Thanks @rnagella for both filing the issue and looking into the cause.  I'll find out who owns this on the Segment side and get it fixed.  Will report back here once I have more information.

**Comment by bsneed** [comment]
Hi @rnagella, I looked into this some more.  You should be able to change your tracking plan to interpret Build as a string instead of an integer.  This was most likely happening because a 2 year old version of Android did sent this value as an integer.  This is no longer the case.
