### ISSUE TITLE
Maximum Request Size

### ISSUE THREAD

**Issue by cristi-lupu** [segmentio/analytics-ios#871]
Hey. We are using Segment iOS and Android SDK's and were wondering why the iOS client did not get the limit implemented when [Android did]( https://github.com/segmentio/analytics-android/pull/575) and [official documentation has such a limit](https://segment.com/docs/connections/sources/catalog/libraries/server/http-api/#max-request-size).
Was there a particular reason for not having it implemented for iOS?
I'm willing to open a PR to add this functionality to the iOS library (similar to Android PR).

**Comment by cristi-lupu** [comment]
I opened a PR for this: https://github.com/segmentio/analytics-ios/pull/874

**Comment by bsneed** [comment]
@cristi-lupu thanks so much for this!!  Merged!

**Comment by bsneed** [comment]
I'll release a new beta next week most likely that will include this.
