### ISSUE TITLE
Provide a way to modify context properties being sent in Event

### ISSUE THREAD

**Issue by eric-melo** [segmentio/analytics-ios#872]
SEGSegmentIntegration adds extra `context` properties inside `enqueueAction:dictionary:context:integrations:` method. These properties come from `[self liveContext]` and `self.cachedStaticContext`.

Since these properties are added only way down the line, there's no way to edit what is going to be sent in the Event payload. Neither via SEGAnalytics configuration, nor via Middleware.

On the Android version, the Middleware is able to modify the data being sent in the context payload.
We would like to get the same behavior on iOS.

**Comment by bsneed** [comment]
Thanks @eric-melo!  I've noticed this too.  Can you describe your use case?

**Comment by eric-melo** [comment]
Hi @bsneed,
We setup our own `requestFactory` in SEGAnalyticsConfiguration to send the events to our BI infrastructure. The data there is thrown into a data lake, and all properties in an event are mapped as columns in the event tables.

Now, for every "Track" type event we send, SEGSegmentIntegration is adding everything from `[SEGSegmentIntegration staticContext]` and `[SEGSegmentIntegration liveContext]` into the `context` section of the event, and that is polluting our tables with information we don't need.
The ideal scenario for us is to choose in which events we send these context infos.
Through Middlewares in Android this is perfectly achievable, but in iOS there's no way to get to that. (not without ugly hacks, at least).

Was it clear?

**Comment by bsneed** [comment]
@eric-melo ok, I think I understand.  I've got an experimental branch going right now that might help you.  It's not the best way to do this, but might help you in the interim.  If you have a look at the `bsneed/destmiddleware` branch, you can insert middleware specific to a destination where you'd be able to see the context as it goes out.  Usage would look something like this...

```
        let segmentIntegration = SEGSegmentIntegrationFactory()

        let customizeMixpanelTrackCalls = SEGBlockMiddleware { (context, next) in
          if context.eventType == .track {
            next(context.modify { ctx in
              guard let track = ctx.payload as? SEGTrackPayload else {
                return
              }
              let newEvent = "[Mixpanel] \(track.event)"
              var newProps = track.properties ?? [:]
              newProps["customAttribute"] = "Sausage"
              ctx.payload = SEGTrackPayload(
                event: newEvent,
                properties: newProps,
                context: track.context,
                integrations: track.integrations
              )
            })
          } else {
            next(context)
          }
        }

        configuration.integrationMiddleware = [SEGIntegrationMiddleware(key: segmentIntegration.key(), middleware: [customizeSegmentTrackCalls]]

```

The Segment integration is added automatically, so you don't need to call `use` like you would with other integrations.  Please lets me know if this gets you moving until we move the context modifications further up the chain of events (it is on our radar).

**Comment by eric-melo** [comment]
That looks great, @bsneed! I'll give it a try and let you know if it suits my needs.
Thanks.

**Comment by eric-melo** [comment]
@bsneed,
I just tried out your changes, but unfortunately it doesn't solve the issue.
The event context gets populated with unwanted data only at this point :
https://github.com/segmentio/analytics-ios/blob/master/Analytics/Classes/Internal/SEGSegmentIntegration.m#L479

And the `integrationMiddlewares` are executed before that. So, I'm still not able to shape the event the way I need.

**Comment by bsneed** [comment]
@eric-melo ok, gotcha.  lemme see what I can do.

**Comment by bsneed** [comment]
@eric-melo pushed another commit.  this is experimental and it will be removed in the future, but should cover you in the meantime.

```/**
 Experimental support for transformation of raw dictionaries prior to being sent to segment.
 This should generally NOT be used, but is a current stop-gap measure for some customers who need to filter
 payload data prior to being received by segment.com.  This property will go away in future versions when context
 object data is made available earlier in the event pipeline.
 */
@property (nonatomic, strong, nullable) SEGRawModificationBlock rawSegmentModificationBlock;
```

Example usage: 

```
        configuration.experimental.rawSegmentModificationBlock = { (payload: [AnyHashable: Any]) -> [AnyHashable: Any] in
            print(payload)
            
            var newPayload = payload
            if var context = newPayload["context"] as? [String: Any] {
                context["myValue"] = "booya"
                newPayload["context"] = context
            }
            
            return newPayload
        }
```

**Comment by eric-melo** [comment]
@bsneed, this last commit does exactly what we need! It's letting me customize the payload at the right moment now.
Thank you so much for all the attention and putting up with this back and forth!

**Comment by bsneed** [comment]
@eric-melo no problem, my pleasure!!  glad that got you moving!  Just a reminder, this is completely temporary.  In a later release, that flag will get removed, but we will have moved the context data up in the flow so a destination middleware (see my first example) would get you the same capabilities.
