### ISSUE TITLE
LIB-1554

### ISSUE THREAD

**Issue by arietis** [segmentio/analytics-ios#877]
@arietis this change is already in the latest beta.

_Originally posted by @bsneed in https://github.com/segmentio/analytics-ios/issues/846#issuecomment-613668709_

I'm sorry but either I'm missing something or there is no beta with this fix included. :)

![image](https://user-images.githubusercontent.com/887107/79273665-07e2cc00-7eac-11ea-9cb8-0d58f7257b4f.png)

**Comment by bsneed** [comment]
Ah, my mistake.  I'm getting confused with the react-native project. :(

My apologies.  Will try and put a new beta out this week that includes this.

**Comment by bsneed** [comment]
3.8.0-beta.2 is out now!
