### ISSUE TITLE
Swift UUID causes SIGABRT in AssertDictionaryTypes

### ISSUE THREAD

**Issue by russellbstephens** [segmentio/analytics-ios#878]
![Screen Shot 2020-04-15 at 4 49 18 PM](https://user-images.githubusercontent.com/6198867/79387151-2a6ef680-7f39-11ea-854f-87698b4329b0.png)

**Comment by russellbstephens** [comment]
I am able to resolve this locally via the code below.

`private extension Dictionary where Value == Any {
    var stringifyUUID: [Key: Value] {
        return mapValues { value in
            guard value is UUID else {
                return value
            }
            return "\(value)"
        }
    }
}`

In a release configuration the UUID evaluates to a string, I would propose the assert list could include NSConcreteUUID since it is a valid Any object in swift.

**Comment by russellbstephens** [comment]
pod 'Analytics', '3.7.0'

**Comment by bsneed** [comment]
Hi @russellbstephens can you verify if this happens with the latest 3.8.0-beta.2 that was just released?  If so, I'll include a fix for this in the next version.

**Comment by russellbstephens** [comment]
I can confirm this does not happen on `3.8.0-beta.2`

**Comment by russellbstephens** [comment]
it does happen on `3.7.1`

**Comment by bsneed** [comment]
@russellbstephens ok, good to know, thanks so much for checking that!  I'm going to go ahead and close this as a fix probably won't be made to the 3.7.1 series.  Are you able to use 3.8.0-beta.2?
