### ISSUE TITLE
Application Opened event parameters

### ISSUE THREAD

**Issue by xavierjurado** [segmentio/analytics-ios#882]
Is it expected behavior that when the application returns from background Segment tracks an "Application Opened" with only a single parameter `from_background: false`?

I'm asking that because when the same event is triggered from an application launch, it includes at least two other parameters: `version` and `build`. On previous (3.7.x) versions of the SDK both events included the aforementioned parameters. As far as I can tell the change was introduced in https://github.com/segmentio/analytics-ios/commit/6dd748d567b6470fc48a74e3cbcf01ba18a48b92.

Thanks!

**Comment by bsneed** [comment]
@xavierjurado nice find!  the removal of version and build is definitely not correct.  I'll fix this.  However, re "Application Opened" and from_background being false doesn't seem possible (applicationWillEnterForeground is hard-coded to true).  Could it be that the app in question isn't actually returning from the background and has been shut down by the system?

**Comment by bsneed** [comment]
those two fields are added back in #884, which will come out at 3.8.1.

**Comment by xavierjurado** [comment]
Thanks for the prompt answer, looking forward the next release 👍 

(Regarding the `from_background` value I copy&pasted the wrong line of code, it is indeed `true` in this scenario).
