### ISSUE TITLE
device Token not sent to customer.io

### ISSUE THREAD

**Issue by eljamali** [segmentio/analytics-ios#883]
Hi, 
I am using Segment in my iOS app, I registred the token using analytics.registeredForRemoteNotifications, and I see in Segment debugger that token is there, in the device dictionary (inside context).
I linked segment to customer.io, the only way to send them a device token is to trigger a "trackApplicationLifecycle" events and the first App Oppenned does not contain the user id because he is not signed up yet, so if I want to send the token the user needs to complete the signup, close the app, open it again and now segment trigger another "App Opened" and customer.io received the device token...
there is a tracking in each step of the signup flow, and I see the token is in context dictionary but never arrived to customer.io 
can you please check on your side what's happening? 

thank you

**Comment by bsneed** [comment]
By device token, you mean what is registered for push notifications?
