### ISSUE TITLE
Not able to fallback and use the barebones config.

### ISSUE THREAD

**Issue by asoneji** [segmentio/analytics-ios#887]
We updated from `pod 'Analytics', '3.6.10'` to: `pod 'Analytics', '3.8.0'` and notice our events stop flowing.

I debugged the issue and may know the cause of the issue: https://github.com/segmentio/analytics-ios/commit/0891ee340046291279d842b37d92f0b430d18d16#diff-75d33076ee62b3feac17dcea1ee72f73

**Comment by bsneed** [comment]
Great catch!!!  I'll get this into a 3.8.2.

**Comment by asoneji** [comment]
I have created a https://github.com/segmentio/analytics-ios/pull/890 with a fix. When is 3.8.2 planned for release?

**Comment by bsneed** [comment]
Looks like PR #889 covered this right before you; they neglected to tag this issue though. Doh!  Either way, thanks both for this issue report and the PR!!!  3.8.2 is coming out today.  Prepping it now.

**Comment by asoneji** [comment]
Thanks!
