### ISSUE TITLE
Issue with Rubymotion

### ISSUE THREAD

**Issue by killion** [segmentio/analytics-ios#89]
Hi, I'm trying to install the Analytics podfile and use it with Rubymotion. I added the following to my rakefile:

```
  app.pods do
    pod 'Reachability'
    pod 'JMImageCache'
    pod 'Analytics'
  end
```

In my AppDelegate I added the following to on load:

```
    Analytics.debug(true)
    Analytics.initializeWithSecret("redacted")
```

When I compile I get the following error:

```
*** Terminating app due to uncaught exception 'NameError', reason: 'app_delegate.rb:12:in `on_load:': uninitialized constant AppDelegate::Analytics (NameError)
```

When I look at the headers for Analytics I don't see @class Analytics defined.

I know this is out of the normal scope for most, but I was hoping someone might have some insight. Thanks!

**Comment by poc7667** [comment]
how could you know we should at that ~~ RM seems terrible that you should better know all the tricks
