### ISSUE TITLE
MacCatalyst isn't building

### ISSUE THREAD

**Issue by RVijay007** [segmentio/analytics-ios#898]
I tried to build the library for MacCatalyst, but it is failing saying it's unsupported. Does anyone know how I can build a fat framework that would support iOS, iOS simulator, and macOS via macCatalyst? Thanks!

**Comment by bsneed** [comment]
We're going to be adding Mac support soon and will make sure this gets addressed as well.  cc @migs647

**Comment by migs647** [comment]
@RVijay007 We have added Catalyst support (recommended to use SPM) and MacOS support in our 4.0.4 prerelease.
