### ISSUE TITLE
Support for Window Scenes

### ISSUE THREAD

**Issue by ay8s** [segmentio/analytics-ios#903]
Just been exploring adding screen view tracking to our iOS app. Our app makes use of the Window Scenes introduced in iOS 13. It looks like Segment is unable to track screen views due to `seg_topViewController` looking at the UIApplication Delegate to retrieve the window which is no longer there for scene based apps.

Is there any plan to support screen views for scene windows? Especially as that will be the default for more apps once iOS 14 comes round and people start supporting iOS 13+.

Issue was also mentioned here... https://github.com/segmentio/analytics-ios/issues/786

**Comment by bsneed** [comment]
@migs647 do your latest changes address this?

**Comment by ay8s** [comment]
Looks like they might :)

**Comment by migs647** [comment]
Yah our latest changed address this as we moved from the application delegate to passing in the view to retrieve the window.

**Comment by bsneed** [comment]
Eggscellent!  Thanks @migs647 and @ay8s !  Closing.
