### ISSUE TITLE
Test target fails to build after switching from Carthage to SPM with 4.0.1

### ISSUE THREAD

**Issue by danmurrelljr** [segmentio/analytics-ios#908]
After switching to using 4.0.1 and Swift Package Manager, I'm not able to link a build for the test target, with the errors:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_SEGAnalyticsConfiguration", referenced from:
      objc-class-ref in SegmentAnalytics.o
  "_OBJC_CLASS_$_SEGAnalytics", referenced from:
      objc-class-ref in SegmentAnalytics.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

SegmentAnalytics is a simple swift class that uses and imports Analytics, and the only file in the app using the framework. There are no actual references to SEGAnalytics or SEGAnalyticsConfiguration, only Analytics and AnalyticsConfiguration. It seems like an issue with the NS_SWIFT_NAME() macros for these two renamed classes.

I've checked all the build settings, and nothing jumps out. Any ideas?

**Comment by bsneed** [comment]
cc @migs647

**Comment by danmurrelljr** [comment]
I noticed the Analytics library was linked in the main executable, but not in the test target. After adding it to the test target as well, tests now build and run without those undefined symbols.

So that fixes my build (although I'm unclear as to why). Before closing this, could someone explain this? Thanks!

**Comment by migs647** [comment]
@danmurrelljr Is it possible you can try our current `master` branch? We changed up our Package.swift to allow swift package to determine to build as dynamic or static.

**Comment by layoutSubviews** [comment]
@migs647 My project was affected by the same issue and I can confirm that the `master` branch now builds and links successfully. Thanks!

**Comment by migs647** [comment]
@layoutSubviews Awesome! 4.0.2 is released so feel free to revert back to versioning. I will close this out. Thanks everyone for their feedback and help.
