### ISSUE TITLE
Import fail in 4.0.1

### ISSUE THREAD

**Issue by af-margot** [segmentio/analytics-ios#910]
Hi, 

In SEGAnalyticsUtils, the import for SEGSerializableValue.h failed. 
It used to be #import <Analytics/SEGSerializableValue.h>, but I see it was changed to #import <SEGSerializableValue.h> in the latest version. 
![Xnip2020-06-24_18-11-29](https://user-images.githubusercontent.com/48682256/85582482-26043f80-b646-11ea-8438-a83696824eac.jpg)

**Comment by migs647** [comment]
@af-margot Can you try deleting your Carthage cache with 'rm -rf ./Carthage/Build' and try again? We aren't seeing this on our side with our Carthage application.

**Comment by af-margot** [comment]
Cleaning the cache does not help.
I'm getting the error when trying to add [segment-appsflyer-ios]( https://github.com/AppsFlyerSDK/segment-appsflyer-ios), because it uses this file.

**Comment by migs647** [comment]
@af-margot I'll look into it today, thanks for providing a demo.

**Comment by bsneed** [comment]
Looks like there was some ambiguity between private/public bits.  This is resolved in #913
