### ISSUE TITLE
Crash on app startup with Segment 4.0.1

### ISSUE THREAD

**Issue by jbelkins** [segmentio/analytics-ios#916]
The Analytics SDK is crashing my app on startup, starting with version 4.  (Crashes on 4.0.0 and 4.0.1)
Everything ran just fine for us on version 3.

A representative crash log from my crash reporter and a Xcode screenshot showing the originating thread are attached.

It appears that you're enqueueing a synchronous task from within a task on the same queue, hence: deadlock.  The point of entry to the Analytics SDK was when we called `registeredForRemoteNotifications(withDeviceToken:)`

[Crash log](https://github.com/segmentio/analytics-ios/files/4854750/bugsnag_error_stacktrace_EXC_BREAKPOINT_event_5ef4b14d005b713de55f0000.txt)
[Xcode screen shot](https://user-images.githubusercontent.com/863266/86185279-95bd7300-bafb-11ea-81a7-ce0efebc1e96.png)

**Comment by bsneed** [comment]
@jbelkins thanks for reporting this!  We'll get this fixed ASAP.

**Comment by bsneed** [comment]
Fixed on master.  Release coming soon.
