### ISSUE TITLE
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Attempt to insert non-property list object in Swift 5

### ISSUE THREAD

**Issue by Prathap-iOS** [segmentio/analytics-ios#944]
I am getting this error while saving user details in UserDefaults and, some of my values are nil. My array contains array of dictionaries. 

I am getting response from GraphQL and trying to save it in UserDefaults.
Here is my response that I'm trying to save in UserDefaults

`FetchUserDetailsQueryQuery.Data.Account.Me(resultMap: ["dob": nil, "role": Optional(Role.dev), "__typename": Optional("User"), "altPhone2": nil, "status": Optional(statusType.active), "altPhone1": nil, "phone": Optional("+91 585825555"), "firstName": Optional("user name"), "lastName": nil, "id": Optional("8568165fwef8793"), "email": nil, "gender": Optional(genderType.male)])`

And I'm trying to convert this using NSKeyedArchiver. But, My result is printing nil
Here is my code which I'm converting to data.

`if let userInfo = GraphQLResult.data?.account?.me {
              let userData = try? NSKeyedArchiver.archivedData(withRootObject: userInfo, requiringSecureCoding: true)
              UserDefaults.standard.set(userData, forKey: "userProfile")
  }` 

userData is printing nil.

@f2prateek  or Can someone please help me with this?

**Comment by bsneed** [comment]
We can't really help you with this.  It doesn't seem related to the Segment analytics-ios library.  Please reopen if that's incorrect.
