### ISSUE TITLE
SPM: Allow iOS 10 for iPhone (mismatch between project and SPM)

### ISSUE THREAD

**Issue by lluisgerard** [segmentio/analytics-ios#946]
You have a deployment target of iOS 10 and yet the SPM has a minimum version of iOS 12.
https://github.com/segmentio/analytics-ios/blob/7a8387b1048915b22bbc971ff308baa6a0e7e13a/Package.swift#L9

**Comment by bsneed** [comment]
Looking at this today along with some other things, thanks @lluisgerard !

**Comment by migs647** [comment]
@lluisgerard This should be resolved as of 4.1.2: https://github.com/segmentio/analytics-ios/releases/tag/4.1.2
