### ISSUE TITLE
[Question] Is there is an SPM support yet?

### ISSUE THREAD

**Issue by SocialKitLtd** [segmentio/analytics-ios#948]
Hey there,

Is there is an SPM support yet?

**Comment by migs647** [comment]
@SocialKitLtd Swift Package Manager support was added to our pre-release version 4.0.3. We will be releasing a stable release of 4.1 soon. In the meantime you're free to start transitioning with 4.0.5.

**Comment by SocialKitLtd** [comment]
Thanks!
