### ISSUE TITLE
Documentation wrong

### ISSUE THREAD

**Issue by gtokman** [segmentio/analytics-ios#951]
I'm updating our SDK to a new version of `Analytics` becuase of changes to IDFA.

I see in the doucmenation [here](https://segment.com/docs/connections/sources/catalog/libraries/mobile/ios/)
> analytics-ios-4.1 and later, Segment doesn’t auto-collect IDFA

I tried installing `pod 'Analytics', '~> 4.1.0' but get an error: 
```
None of your spec sources contain a spec satisfying the dependency: `Analytics (~> 4.1.0)`
```

Then I tried installing from the master branch and see the version in the spec is `4.0.5`.

Are the docs wrong? And will I be okay with a version >= 4 for the auto collect IDFA to be off by default?

**Comment by bsneed** [comment]
We'll be pushing this release out within the next 20-30 minutes.  The docs landed a little early.  If you point your pod to `master` you'll get all the changes that are about to be released.
