### ISSUE TITLE
Feature request: Expose SEGState.sharedInstance().userInfo.userId via setter or method on Segment.Analytics instance

### ISSUE THREAD

**Issue by rromanchuk** [segmentio/analytics-ios#952]
Use case: 
A server to server source has already triggered an identify call and i would like the ability to set set the userId, on the client, (to be included in future track calls) without requiring another `identify` call on the client

```swift
Segment.Analytics.shared().userId = "a userId i want included in track and other payloads"
```

**Comment by bsneed** [comment]
Hi @rromanchuk, unfortunately we won't be able to do this right now.  As a workaround, you could probably make an extension to flip that property to read/write.  SEGState is a stop-gap measure for some pending work and not something we want to support longer term.
