### ISSUE TITLE
CocoaPods doesn't support version 4.1.1

### ISSUE THREAD

**Issue by hieumidoplay** [segmentio/analytics-ios#958]
I update to the latest version but CocoaPods only support up to version 4.0.5.
Please help me take a look at this issue.

**Comment by bsneed** [comment]
You probably need to do ... `pod install --repo-update`.

**Comment by hieumidoplay** [comment]
> You probably need to do ... `pod install --repo-update`.

Thanks @bsneed , I found the problem. It looks like the new version only supports iOS 11 and above. Why aren't we supporting the lower version?
