### ISSUE TITLE
While I call indentify with a my traits contains a NSDate object , it will crash because  'Invalid type in JSON write (__NSTaggedDate)'

### ISSUE THREAD

**Issue by sanhue0302** [segmentio/analytics-ios#959]
as title, I got this problem on 4.1

after look into the source code
I notice that function SEGCoerceDictionary in SEGAnalyticsUtils on 3.9, it was

```
NSDictionary *SEGCoerceDictionary(NSDictionary *dict)
{
    // make sure that a new dictionary exists even if the input is null
    dict = dict ?: @{};
    // assert that the proper types are in the dictionary
    dict = [dict serializableDeepCopy];
    // coerce urls, and dates to the proper format
    return SEGCoerceJSONObject(dict);
}
```

but on 4.1.1, it became

```
NSDictionary *SEGCoerceDictionary(NSDictionary *dict)
{
    // make sure that a new dictionary exists even if the input is null
    dict = dict ?: @{};
    // assert that the proper types are in the dictionary
    dict = [dict serializableDeepCopy];
    return dict;
}
```

I found that the conversion code was moving into serializableDeepCopy
and the implementation is in - (id)serializableDeepCopy:(BOOL)mutable 

```
       ...

        if ([aValue conformsToProtocol:@protocol(SEGSerializableDeepCopy)]) {
            theCopy = [aValue serializableDeepCopy:mutable];
        } else if ([aValue conformsToProtocol:@protocol(NSCopying)]) {
            theCopy = [aValue copy];
        } else if ([aValue conformsToProtocol:@protocol(SEGSerializable)]) {
            theCopy = [aValue serializeToAppropriateType];
        } else {
            theCopy = aValue;
        }
        
```

In my case, when aValue is kind of class NSDate, it run into conforms to protocol NSCoping. 
I think it should run into conforms to SEGSerializable first to convert NSDate to NSString

For now, I will convert NSDate to NSString myself. 

Why does it dismiss on 4.1?

**Comment by bsneed** [comment]
Thanks @sanhue0302 !  I'll get this fixed ASAP.

**Comment by bsneed** [comment]
Fixed!  Currently on `master` to try out.  Release coming soon.

**Comment by allreddy** [comment]
Hello there, we just upgraded to `4.1.1` via Carthage and running into this crash.

Any timeline for when this fix will be released, ie. `4.1.2`?

**Comment by iosjillian** [comment]
We're also experiencing this issue and wondering about a timeline since we're preparing an app store release. Thanks for tracking this down and fixing it so quickly!

**Comment by bsneed** [comment]
@iosjillian @allreddy we're going to do a 4.1.2 release today.
