### ISSUE TITLE
identify() has unnecessary code, potential bug setting "traits.userId"

### ISSUE THREAD

**Issue by cayleyh** [segmentio/analytics-ios#961]
Reviewing the changes for the `identify()` method that fixed the incorrect traits issue (https://github.com/segmentio/analytics-ios/commit/b82f0ed082ee28e33504c9f543d1e75f7da90c5e), I noticed the following:

The code was updated to base it's underlying call based on updating `existingTraitsCopy` to fix the identified issue. It still creates a mutable copy of the `traits` argument (`traitsCopy`). There is still some checks & assignments to this mutable copy, but it appears it is not actually used.

I'm not an expert in the code base, but looks like the creation of that mutable copy `traitsCopy` and all subsequent uses can just be removed.

Also, if the action in line 290 to copy the user id to the traits is actually needed, it looks like this is a bug that will need to be fixed, as that copy goes nowhere. This explains inconsistencies I see in the availability of the `userId` property on traits in services getting data from Segment.

**Comment by bsneed** [comment]
Looking at this today along with some other things.  Thanks for the report @cayleyh ! 👍

**Comment by bsneed** [comment]
Fixed in master.  Release coming soon.  Thanks again @cayleyh !
