### ISSUE TITLE
Crash "Invalid type in JSON write (NSURL)"

### ISSUE THREAD

**Issue by rogerluan** [segmentio/analytics-ios#964]
Hello!

We just upgraded to v4.1.1 and it's crashing randomly. I can provide some stack trace but not much more info other than that.

<img width="1343" alt="image" src="https://user-images.githubusercontent.com/8419048/98365186-c87af900-2010-11eb-834b-20eac8bcd417.png">

<img width="1335" alt="image" src="https://user-images.githubusercontent.com/8419048/98365263-eb0d1200-2010-11eb-972e-7dba29c90688.png">

Hope this helps. I had to revert to 4.0.5, that is not crashing.

**Comment by bsneed** [comment]
This has been fixed on master.
