### ISSUE TITLE
Question: How can I do screen tracking for SwiftUI apps

### ISSUE THREAD

**Issue by jzeisweiss** [segmentio/analytics-ios#965]
Is there support for screen tracking in SwiftUI similar to the view controller tracking you can from adding `configuration.recordScreenViews = true` to the AppDelegate?

**Comment by migs647** [comment]
We'll be looking into this shortly

**Comment by jzeisweiss** [comment]
@migs647 - Do you know if this issue will be solved by https://github.com/segmentio/analytics-swift?

**Comment by alanjcharles** [comment]
@jzeisweiss yeah, you can check out the SwiftUI example here: https://github.com/segmentio/analytics-swift/tree/main/Examples/apps/SegmentSwiftUIExample

Closing this with that in mind. Please feel free to reach out to us there with any additional questions.

**Comment by loganblevins** [comment]
Bumping this. We long to hav auto screen tracking for SwiftUI just like UIKit. Adding breadcrumbs to view lifecycles is highly verbose and adds a lot of clutter to our views.
