### ISSUE TITLE
Braze Integration - AppBoy object of "Integrations" is always false

### ISSUE THREAD

**Issue by danielhorv** [segmentio/analytics-ios#967]
Hi Guys!
We already have a functional Segment tracking in our iOS app, but we also need to integrate Braze (https://github.com/Appboy/appboy-segment-ios).
We have a problem, when the events are tracked, they include an "integrations" object with "Appboy" which is always false:

```
,"integrations": {
  "Appboy": false
},
```

This means, that Segment doesn't send the tracked events to Braze. I just looked into the source code and it will always set to false. Is there any reason why? 

```objective-c
- (NSDictionary *)integrationsDictionary:(NSDictionary *)integrations
{
    NSMutableDictionary *dict = [integrations ?: @{} mutableCopy];
    for (NSString *integration in self.analytics.bundledIntegrations) {
        // Don't record Segment.io in the dictionary. It is always enabled.
        if ([integration isEqualToString:@"Segment.io"]) {
            continue;
        }
        dict[integration] = @NO;
    }
    return [dict copy];
}
```

I just changed `dict[integration]` to `@YES` and now it seems to work.
Android just send an empty object and it's also working.

BR
Daniel

**Comment by bsneed** [comment]
@danielhorv is your intent for braze to be delivered via cloud mode, or via device mode?

**Comment by danielhorv** [comment]
I think we need both because we want to see all our events in Segment, but also want to use Braze for the push notifications and in-app messaging. Which requires some extra configuration for Braze.

Without the Appboy-Segment SDK, we receive every event out of the box in our Braze dashboard (destination is configured in Segment) - It's the cloud mode if I'm right. 

But we need the Appboy-Segment SDK (because of the push registration) and then `"Appboy": false` will be sent in every Analytics track/screen event. In this case, we don't receive any events on the Braze dashboard.

**Comment by alanjcharles** [comment]
Closing since there has been no response in 10 months. Please feel free to reopen with additional information if this is still an issue.
