### ISSUE TITLE
__deprecated__ define in SEGMacros.h may cause issues

### ISSUE THREAD

**Issue by heikkikoivikkotrov** [segmentio/analytics-ios#969]
Hello,

We noticed that when updating to latest version of the iOS SDK, we started getting complication errors due to the __deprecated__(s) macro definition in SEGMacros.h. After looking into this a bit, it may be possible that this definition is not required? I am not too familiar with this project to have a better opinion at this point, but looks like `DEPRECATED_MSG_ATTRIBUTE` is used elsewhere.

Please take a look at the conflicting definition in include/sys/cdefs.h:
`/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.2.sdk/usr/include/sys/cdefs.h:200:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^

/Users/dev/Library/Developer/Xcode/DerivedData/TrovAuto-bidwivivgcthupaagppwqsopvxbh/Build/Products/Develop-iphonesimulator/Analytics/Segment.framework/Headers/SEGMacros.h:14:42: note: expanded from macro '__deprecated__'
#define __deprecated__(s) __attribute__((deprecated(s)))`

For now we have a workaround but would be good to be able to remove it in the future.

**Comment by bsneed** [comment]
What is your build setup?  We're not seeing that here on Xcode 12.

**Comment by bsneed** [comment]
Also would be interested in what your workaround is.

**Comment by bsneed** [comment]
Closing.
