### ISSUE TITLE
How to set advertisingId after User set promission

### ISSUE THREAD

**Issue by sanhue0302** [segmentio/analytics-ios#971]
In iOS 14, We need permission to use adTracking.
As document said, I setup SEGAnalytics in delegate application:didFinishLaunchingWithOptions as below

```
    SEGAnalyticsConfiguration *configuration = [SEGAnalyticsConfiguration configurationWithWriteKey:{SEGMENT_KEY}];

    configuration.enableAdvertisingTracking = YES;
    
    configuration.adSupportBlock = ^NSString * _Nonnull{
        
        NSString *uuidString = [[[ASIdentifierManager sharedManager] advertisingIdentifier] UUIDString];
        return uuidString;
    };
    [SEGAnalytics setupWithConfiguration:configuration];
```

however,
when we got user's permission using requestTrackingAuthorizationWithCompletionHandler:
we can't do the configuration again.
The only way to apply the configuration is removing the app from background, and launch again

Is there another way to set advertisingId after "[SEGAnalytics setupWithConfiguration:configuration];"?

**Comment by migs647** [comment]
Hello @sanhue0302... thanks for reaching out

We suggest expanding your adSupportBlock to contain the ATTrackingManager logic. Please let us know if this does not work for you...

`
if ([ATTrackingManager trackingAuthorizationStatus] == ATTrackingManagerAuthorizationStatusNotDetermined) {
        
        [ATTrackingManager requestTrackingAuthorizationWithCompletionHandler:^(ATTrackingManagerAuthorizationStatus status) {
            
            NSString *idfa = [[[ASIdentifierManager sharedManager] advertisingIdentifier] UUIDString];
            NSString *idfv = [[[UIDevice currentDevice] identifierForVendor] UUIDString];
            if (status == ATTrackingManagerAuthorizationStatusAuthorized) {
                [SEGAnalytics.sharedAnalytics track:@"iOS14 Tracking enabled" properties:@{@"IDFA": idfa, @"IDFV": idfv}];
            } else {
                [SEGAnalytics.sharedAnalytics track:@"iOS14 Tracking disabled" properties:@{@"IDFA": idfa, @"IDFV": idfv}];
            }
        }];
    } else {
        NSString *idfa = [[[ASIdentifierManager sharedManager] advertisingIdentifier] UUIDString]; // Will be 0000-0000-0000-0000 if denied
        NSString *idfv = [[[UIDevice currentDevice] identifierForVendor] UUIDString];
        [SEGAnalytics.sharedAnalytics track:@"iOS14 Tracking after being asked" properties:@{@"IDFA": idfa, @"IDFV": idfv}];
    }
`

**Comment by bsneed** [comment]
One other alternative is to capture it and store it somewhere.  And your adSupportBlock just returns whatever the value that's stored (initially nil I suppose).

**Comment by sanhue0302** [comment]
> One other alternative is to capture it and store it somewhere. And your adSupportBlock just returns whatever the value that's stored (initially nil I suppose).

Since I Setup SEGAnalytics when didFinishLaunchingWithOptions, the adSupportBlock will only run one time
So, if I store it after user confirm it, We still need to restart app to let didFinishLaunchingWithOptions run again to setup SEGAnalytics

**Comment by sanhue0302** [comment]
> Hello @sanhue0302... thanks for reaching out
> 
> We suggest expanding your adSupportBlock to contain the ATTrackingManager logic. Please let us know if this does not work for you and re-open the issue.
> 
> ```
> if ([ATTrackingManager trackingAuthorizationStatus] == ATTrackingManagerAuthorizationStatusNotDetermined) {
>     
>     [ATTrackingManager requestTrackingAuthorizationWithCompletionHandler:^(ATTrackingManagerAuthorizationStatus status) {
>         
>         NSString *idfa = [[[ASIdentifierManager sharedManager] advertisingIdentifier] UUIDString];
>         NSString *idfv = [[[UIDevice currentDevice] identifierForVendor] UUIDString];
>         if (status == ATTrackingManagerAuthorizationStatusAuthorized) {
>             [SEGAnalytics.sharedAnalytics track:@"iOS14 Tracking enabled" properties:@{@"IDFA": idfa, @"IDFV": idfv}];
>         } else {
>             [SEGAnalytics.sharedAnalytics track:@"iOS14 Tracking disabled" properties:@{@"IDFA": idfa, @"IDFV": idfv}];
>         }
>     }];
> } else {
>     NSString *idfa = [[[ASIdentifierManager sharedManager] advertisingIdentifier] UUIDString]; // Will be 0000-0000-0000-0000 if denied
>     NSString *idfv = [[[UIDevice currentDevice] identifierForVendor] UUIDString];
>     [SEGAnalytics.sharedAnalytics track:@"iOS14 Tracking after being asked" properties:@{@"IDFA": idfa, @"IDFV": idfv}];
> }
> ```

Yes, I am using code like you said. and it work.
But I am thinking that is there a way to set the IDFA after SEGAnalytics setup.

**Comment by bsneed** [comment]
> > One other alternative is to capture it and store it somewhere. And your adSupportBlock just returns whatever the value that's stored (initially nil I suppose).
> 
> Since I Setup SEGAnalytics when didFinishLaunchingWithOptions, the adSupportBlock will only run one time
> So, if I store it after user confirm it, We still need to restart app to let didFinishLaunchingWithOptions run again to setup SEGAnalytics

That’s not how it works. The adsupportblock is called multiple times. You’re giving us a block we’ll call anytime we need the idfa value, which is likely every event that goes thru the system.

**Comment by sanhue0302** [comment]
> > > One other alternative is to capture it and store it somewhere. And your adSupportBlock just returns whatever the value that's stored (initially nil I suppose).
> > 
> > 
> > Since I Setup SEGAnalytics when didFinishLaunchingWithOptions, the adSupportBlock will only run one time
> > So, if I store it after user confirm it, We still need to restart app to let didFinishLaunchingWithOptions run again to setup SEGAnalytics
> 
> That’s not how it works. The adsupportblock is called multiple times. You’re giving us a block we’ll call anytime we need the idfa value, which is likely every event that goes thru the system.

Ok, I did trace into the code.
The adsupportblock is called in the method updateStaticContext.
It will be called on each time applicationWillEnterForeground be called.
