### ISSUE TITLE
SEGContext overwrites UIViewRepresentableContext

### ISSUE THREAD

**Issue by Paul-Svetlichny** [segmentio/analytics-ios#975]
NS_SWIFT_NAME(Context)
@interface SEGContext : NSObject

This part in the header SEGContext.h overwrites SwiftUI UIViewRepresentable
typealias Context = UIViewRepresentableContext

Leads to application using SwiftUI and UIViewRepresetableContext as Context building fails.

**Comment by migs647** [comment]
Thanks @Paul-Svetlichny -- we are looking into SwiftUI compatibility currently.

**Comment by dmiluski** [comment]
Any update on this? Anybody find a work-a-round for the time being?

**Comment by dmiluski** [comment]
@Paul-Svetlichny ,

With help from @bsneed , I was able to get Segment + SwiftUI Representable working. Hopefully this gets you moving forward too.

https://github.com/segmentio/analytics-ios/pull/985#issuecomment-776903974

```diff
import AuthenticationServices
import Segment
import SwiftUI
final class SignInWithApple: UIViewRepresentable {
-    func makeUIView(context: SignInWithApple.Context) -> ASAuthorizationAppleIDButton {
+    func makeUIView(context: SignInWithApple.Context) -> ASAuthorizationAppleIDButton {
        // 3
        return ASAuthorizationAppleIDButton()
    }
    // 4
-    func updateUIView(_ uiView: ASAuthorizationAppleIDButton, context: Context) {}
+    func updateUIView(_ uiView: ASAuthorizationAppleIDButton, context: SignInWithApple.Context) {}
}
```

**Comment by bsneed** [comment]
Ah, didn't see this here, thanks @dmiluski !!
