### ISSUE TITLE
iOS manual track screen doesn't show category

### ISSUE THREAD

**Issue by TripwireNL** [segmentio/analytics-ios#980]
Hi,

I've been implementing manual screen tracking in our iOS app through Segment (v4.1.2) by using this code:
```[[SEGAnalytics sharedAnalytics] screen:event category:category];```

But I don't seen the category coming in. I saw an issue mentioning this was deprecated and we should use the properties dictionary to pass the category. Though in the documentation I couldn't find any properties regarding category while making a track screen event.

Thx!

**Comment by alanjcharles** [comment]
Hi @TripwireNL you can pass a `category` property like so: 

`Analytics.shared().screen("Photo Feed", properties: ["category": category])`

Please feel free to reach out to us at friends@segment.com for additional support and quicker response times if you have any other questions or issues. Thanks!
