### ISSUE TITLE
Add method for including options in Segment SDK Events

### ISSUE THREAD

**Issue by cerupcat** [segmentio/analytics-ios#984]
I'm currently adding options to tracking events in my code.

For example:

`        shared.analytics.track(eventName,
                               properties: eventProperties,
                               options: ["integrations": [
                                "Amplitude": [
                                    "session_id": sessionId
                                ]
                               ]]`

However, the events built into the SDK have no way of including options. This breaks Amplitude session tracking for example. The alternative is to include the Amplitude SDK integration, but that includes other tradeoffs we're trying to avoid.

**Comment by alanjcharles** [comment]
@cerupcat I think our new Amplitude Action Plugin would solve a lot of this for you. Check it out and let me know what you think:

[Swift Plugin Example](https://github.com/segmentio/analytics-swift/blob/main/Examples/destination_plugins/AmplitudeSession.swift
)
[Documentation](https://segment.com/docs/connections/destinations/catalog/actions-amplitude/)

**Comment by cerupcat** [comment]
Thanks! I'll take a look soon.

**Comment by alanjcharles** [comment]
@cerupcat no problem! I'm going to close this out for now as we're making a push to clean up the issues section here and use it more strictly for bug reporting moving forward. If you have other implementation questions or potential issues please feel free to reach out to us at friends@segment.com so we can prioritize it appropriately. If you have any questions on the Swift Pilot or the Swift Amplitude Action Plugin please feel free to leave an issue on that repo directly as we are actively monitoring it. Thanks!
