### ISSUE TITLE
Xcode 12.5 Beta 3: Umbrella header for module 'Segment' does not include header 'SEGReachability.h'

### ISSUE THREAD

**Issue by sebastian-foreflight** [segmentio/analytics-ios#988]
I'm trying to build with Xcode 12.5 Beta 3 and I'm encountering this error

> Umbrella header for module 'Segment' does not include header 'SEGReachability.h'

I'm not sure if this is new in Beta 3 or not as I haven't tried to build with the previous betas.

I'm using SPM and am currently including commit `ce4280d514ef55f7b46f507714c5924ce0e83af0`. The SDK is included as a module with `@import Segment;`

**Comment by Camji55** [comment]
Try pointing SPM to the `master` branch until the next release is published.

**Comment by sebastian-foreflight** [comment]
The commit I'm using, `ce4280d514ef55f7b46f507714c5924ce0e83af0`, is the current tip of the master branch. Looking at https://github.com/segmentio/analytics-ios/blob/master/Segment/Classes/Segment.h I also see that `SEGReachability.h` is not currently included there. To be sure, I've tested with SPM set to `master` and hit the same build error.

From the commit history, it looks like some other Xcode 12.5 issues have been recently fixed, but this one is still an issue as far as I can tell. I've fixed similar issues in SPM packages under my control by adding the missing headers.

**Comment by sebastian-foreflight** [comment]
As an update, I've replicated this in a sample project that includes `master` via SPM I can upload it if that's helpful.

One finding, the issue is actually a warning in Xcode, but it's converted to an error because we have `Treat Warnings as Errors` set to `Yes` like I suspect many others do.
