### ISSUE TITLE
Release of `master` needed for Xcode 12.5 compatibility

### ISSUE THREAD

**Issue by koleson** [segmentio/analytics-ios#990]
`master` contains fixes to the library (removing `TARGET_OS_IPHONE`, among other things) that make it work with Xcode 12.5.  However, these fixes are not accessible through a release version.

Contributing guidelines state that the library will be released every second Wednesday; however, this has not occurred since January 27th (4.1.3).

Xcode 12.5's release is coming so I would like to be prepared in advance.  Thanks!

WORKAROUND:  Pinning the package to `master` is a temporary solution, but doesn't provide much library / API stability to apps using the package.

**Comment by sebastian-foreflight** [comment]
As far as I can tell #988 will also be a blocker for Xcode 12.5, at least for anyone integrating with SPM and with `Treat Warnings as Errors` set to `Yes`.

**Comment by koleson** [comment]
Contacted support.  Sounds like a release is coming in the next 2 weeks.

**Comment by fishcharlie** [comment]
Any updates on this? iOS 14.5 was just released, and Xcode 12.5 was recently recently as well.

**Comment by koleson** [comment]
I was told the release would happen by now.  I have forked the repo and made a dummy release to hold my apps over until the release actually happens.

**Comment by fishcharlie** [comment]
The fact that no one from Segment has replied to this thread is also very disappointing.

**Comment by Camji55** [comment]
I too contacted support and got a fresh 2-week timeline 😞 Support is recommending pointing our releases to `master` but it's less than ideal. Holding back the whole team from upgrading to Xcode 12.5.

**Comment by koleson** [comment]
Well, if you want to Trust A Random Guy On The Internet:  https://github.com/koleson/analytics-ios/releases/tag/4.1.4

You have my solemn pinky-swear that I'm too lazy to do anything nefarious with it.

**Comment by koleson** [comment]
Starting to question my own sanity, so maybe folks can confirm:

Does the Segment SDK 4.1.3 build just fine on Xcode 12.5 GM/App Store for anyone else?

It was broken in the betas, but now it seems to be building and working.

**Comment by Camji55** [comment]
@koleson, seems okay to me now too. Must've been an Xcode Beta bug causing the library to not build.

**Comment by koleson** [comment]
@Camji55 thanks for confirming.  

I think it was an error in the iOS 14.5 SDK specifically, and it was present through all the betas - the issue might reappear in the future if some feature or change got scrubbed from the iOS 14.5 release at the last moment, but for now, the SDK works on the latest released tools so I will close the issue.

**Comment by JagCesar** [comment]
@koleson I'm still seeing this error. macOS 11.3 (20E232) and Xcode 12.5 (12E262). 😢

<img width="356" alt="Screenshot 2021-04-30 at 13 41 52" src="https://user-images.githubusercontent.com/923548/116690554-d440ea00-a9b9-11eb-99ca-11a38c7948aa.png">

**Comment by koleson** [comment]
@JagCesar 4.1.4 went live yesterday - does that fix it?

**Comment by JagCesar** [comment]
@koleson Thanks for reaching out, I'm no longer working on said project so can't verify. :(
