### ISSUE TITLE
Unable to install SDK using CocoaPods on the latest version Analytics 4.1.3, fails with transitive dependencies error 

### ISSUE THREAD

**Issue by Aditi3** [segmentio/analytics-ios#991]
Getting the following error when updated to Analytics 4.1.3. It seems to be working fine for version(s) 4.1.2 and below.

`[!] The 'Pods-ExampleSwift' target has transitive dependencies that include statically linked binaries: (Analytics)`

<img width="808" alt="CocoaPods" src="https://user-images.githubusercontent.com/11608002/113546235-3c91eb00-9609-11eb-87a2-363360d389a3.png">

Environment:
* Xcode version: 12.4
* Analytics Version: 4.1.3
* CocoaPods version: 1.10.1

Podfile: https://github.com/CleverTap/clevertap-segment-ios/blob/master/ExampleSwift/Podfile

Any steps to resolve this would be helpful.

**Comment by Aditi3** [comment]
@bsneed Can you please help here?

**Comment by rwgrier** [comment]
Dup of https://github.com/segmentio/analytics-ios/issues/989?

**Comment by bsneed** [comment]
@Aditi3 looking into this today, FYI.

**Comment by dhiren92** [comment]
+1 this update appears to have broken our ability to update the segment pod

**Comment by anuvednayakzc** [comment]
Anu update here?

**Comment by bsneed** [comment]
Yeah, still trying to figure out the best way to move forward.  A device mode destination requires the pod to be marked as a static lib, others need the opposite and some work fine either way.  Will post back once I have a decent solution.

**Comment by bsneed** [comment]
see discussion here:  https://github.com/segmentio/analytics-ios/pull/968

while modifying options in your pod file can be made to work, it's proving to be user-unfriendly.

**Comment by bsneed** [comment]
4.1.4 coming shortly.
