### ISSUE TITLE
SEGAnalyticsIntegrationDidStart Notification Private

### ISSUE THREAD

**Issue by justinswart** [segmentio/analytics-ios#996]
Hi, I'm using Segment and Braze in a side-by-side integration. I need to know when Segment has initialized integrations so that I can set the Braze instance's delegate property.

I noticed that in #513 it's mentioned that the `SEGAnalyticsIntegrationDidStart` notification was made public but I'm using the Segment SDK via Carthage and in my case this notification appears to be declared in headers that are private to my code:

<img width="827" alt="image" src="https://user-images.githubusercontent.com/3735375/117081045-ef7e6300-acf3-11eb-91c5-2e744e8e5cd6.png">

<img width="989" alt="image" src="https://user-images.githubusercontent.com/3735375/117081078-045af680-acf4-11eb-9766-b0fb1ab142ab.png">

`SEGIntegrationsManager.h` is not a header exposed to my Swift code via the framework built by Carthage.

<img width="354" alt="image" src="https://user-images.githubusercontent.com/3735375/117081098-0f158b80-acf4-11eb-8792-40c51f0d451e.png">

For now I'm able to observe this notification by hard-coding the observation of `io.segment.analytics.integration.did.start` but it would of course be better to not rely on this implementation detail.

Thanks!

**Comment by bsneed** [comment]
Hi @justinswart, what is your use case here?  I might be able to recommend some alternative options.

**Comment by justinswart** [comment]
Hi @bsneed thanks for getting back to me. We want to do some custom action handling with Braze's in-app messages and in order to receive the delegate callbacks we need to set the delegate property on `Appboy.sharedInstance()`. It seems that accessing `Appboy.sharedInstance()` immediately after initializing Segment with Braze in a side-by-side integration displays a warning that Appboy has not yet been initialized. Observing the `SEGAnalyticsIntegrationDidStart` works reliably but of course just has the aforementioned problem for me.

I'm initializing Segment with:

```swift
configuration.use(SEGAppboyIntegrationFactory.instance())
configuration.sourceMiddleware = [BrazeDebounceMiddleware()]
Analytics.setup(with: configuration)
```

Some related Braze docs: https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/in-app_messaging/customization/

**Comment by bsneed** [comment]
Oh, gotcha.  So you're using that debounce middleware, but then you also want to call into Appboy on your own outside of that.  Yeah, so what you're doing is the way to go for the time being.  I'll leave this issue open for next release in the meantime.

**Comment by justinswart** [comment]
Thanks @bsneed. Is ours an unusual use case? Just curious - do most folks using Braze in side-by-side config not reach out to the `Appboy` instance and just make use of default in-app message handling etc?

**Comment by justinswart** [comment]
Hey @bsneed not to worry, we found the correct way to set the delegate:

`SEGAppboyIntegrationFactory.instance()?.appboyOptions = [ABKInAppMessageControllerDelegateKey: self]`

This solves our use case, thanks!

**Comment by bsneed** [comment]
oh nice!!!  that's awesome.  I had no idea that was even there!
